### ISSUE TITLE
RCS1255 for net6+ only

### ISSUE THREAD

**Issue by sungam3r** [JosefPihrt/Roslynator#1009]
RCS1255 lights up even for `netstandard2.0/netstandard2.1` . Should work only for net6+.

**Comment by JosefPihrt** [comment]
Hi,

RCS1255 should not show up if the method `ThrowIfNull` is not available (< .NET.6):
 https://github.com/JosefPihrt/Roslynator/blob/9ccf997f5ef38d0a3cf4a513a44615fb7cea112a/src/Analyzers/CSharp/Analysis/SimplifyArgumentNullCheckAnalyzer.cs#L74-L75

I just checked that it won't show up if the project targets `netstandard2.0` or `netstandard2.1`.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/pull/3438

![изображение](https://user-images.githubusercontent.com/21261007/205630931-67e469cb-0dcb-4f4c-9025-5668195fa0d7.png)

**Comment by JosefPihrt** [comment]
I just cloned GraphQL repository I enabled RCS1255 and the diagnostics are reported only for .NET 6:

![image](https://user-images.githubusercontent.com/11931318/205635319-87d61621-de4f-4ac2-b1ed-a373818aa913.png)
