### ISSUE TITLE
DefaultCodeRefactoringProvider encountered an error and has been disabled [roslynator refactorings]

### ISSUE THREAD

**Issue by micdenny** [JosefPihrt/Roslynator#102]
seems the same problem as #99 for Roslynator Refactorings on Visual Studio 2015 Update 3 but I can only download 1.4.0, maybe you only need to push the new version for vs2015?

**Comment by micdenny** [comment]
as a hotfix I simple installed the full "Roslynator" that as the `Roslynator.Common.dll`

**Comment by JosefPihrt** [comment]
@micdenny Please install latest version 1.4.12 that fixes the issue.

**Comment by micdenny** [comment]
Thank you!!
