### ISSUE TITLE
Analysis seems to ignore #if DEBUG statements, throwing RCS1163 when variables are not used in debug

### ISSUE THREAD

**Issue by teatime** [JosefPihrt/Roslynator#1028]
**Product and Version Used**: 
Roslynator.CodeAnalysis.Analyzers 4.20

**Steps to Reproduce**:
1. Create a new function
```csharp
private static bool DoSomething(string value)
{
#if DEBUG
    return true;
#else
    return DoSomethingWithValue(value);
#endif
}
```
2. Run code analysis

**Actual Behavior**:
Warning "RCS1163": Unused parameter" shown

**Expected Behavior**:
No warning

**Comment by JosefPihrt** [comment]
If you are compiling your code sample in debug mode then the RCS1163 will be reported. That's by design.
