### ISSUE TITLE
Installation instructions for Roslynator.Analyzers and Roslynator.CodeAnalysis.Analyzers on NuGet are incorrect

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#1036]
https://www.nuget.org/packages/Roslynator.Analyzers
https://www.nuget.org/packages/Roslynator.CodeAnalysis.Analyzers

Both tell you to run `dotnet add package roslynator.formatting.analyzers` when they should be `dotnet add package roslynator.analyzers` and `dotnet add package roslynator.codeanalysis.analyzers` respectively.

**Comment by JosefPihrt** [comment]
Fix with https://github.com/JosefPihrt/Roslynator/commit/262f3b419defeea6e7a8f01ddcbcdf03c0d4caf6, but not released yet.
