### ISSUE TITLE
Immediate invocation on casted value using as operator

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#104]
Consider the following code snippet

    var value = (obj as MyClass).MyProperty;

It is ambiguous in its intentions.
The use of `as` indicates that `obj` might not be of type `MyClass`,
but without checking the casted object `MyProperty` is invoked.

As the programmer is apparently sure that `obj` *is* of type `MyClass` a more clear way would be to use 

    var value = ((MyClass)obj).MyProperty;

The semantic difference is, that in case `obj` *is not* of type `MyClass` I get an `InvalidCastException` instead of a `NullReferenceException`.

Would such a analyzer+codefix be within the scope of Roslynator?

**Comment by JosefPihrt** [comment]
Moved to #110
