### ISSUE TITLE
RCS1206 fixer produces invalid code when returning ref structs

### ISSUE THREAD

**Issue by ovska** [JosefPihrt/Roslynator#1048]
**Product and Version Used**: 
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4

Roslynator 2022
Version 4.2.0

> RCS1206: Use conditional access instead of conditional expression

**Steps to Reproduce**:
```csharp
static ReadOnlySpan<byte> GetData(IDummy? dummy)
{
    return dummy is not null ? dummy.Data : default;
    //     ^ suggestion is here
}

interface IDummy
{
    ReadOnlySpan<byte> Data { get; }
}
```

**Actual Behavior**:
```csharp
static ReadOnlySpan<byte> GetData(IDummy? dummy)
{
    return (dummy?.Data) ?? default;
    //           ^ Error: ReadOnlySpan<byte> cannot be made nullable.
}
```
Suggestion does this with all `ref struct` types.

**Expected Behavior**:
The analyzer should be content with ref structs using a ternary.

You were very quick to fix the last little bug, thanks for your hard work on this tool!

**Comment by JosefPihrt** [comment]
> thanks for your hard work on this tool!

You are welcome!
