### ISSUE TITLE
What does FadeOut sufix mean in rule name?

### ISSUE THREAD

**Issue by xperiandri** [JosefPihrt/Roslynator#107]

**Comment by JosefPihrt** [comment]
Analyzers with suffix 'FadeOut' provide visual indication which syntax will be removed when a code fix is applied. If that visual indication is not desired, fade-out analyzer can be disabled and related analyzer (and a code fix) will still work.

Example:
Analyzer InlineLocalVariable (RCS1124) has fade-out analyzer RCS1124FadeOut.

RCS1124FadeOut enabled:
![fadeout](https://user-images.githubusercontent.com/11931318/28032941-9626eb34-65ac-11e7-900c-21f5555ebcce.png)

RCS1124FadeOut disabled:
![nofadeout](https://user-images.githubusercontent.com/11931318/28032954-a2631634-65ac-11e7-9372-0b53606f6729.png)
