### ISSUE TITLE
Error in command "roslynator fix"

### ISSUE THREAD

**Issue by salvatorenapolitano** [JosefPihrt/Roslynator#1074]
**Product and Version Used**: 
"roslynator.dotnet.cli": 
      "version": "0.5.0",

**Steps to Reproduce**:
roslynator fix

**Actual Behavior**:
```csharp
```
Fix 1 RCS0054 'Fix formatting of a call chain.'
One or more errors occurred. ('end' must not be less than 'start' (Parameter 'end'))
  Inner exception: 'end' must not be less than 'start' (Parameter 'end')

**Expected Behavior**:
```csharp
```

**Comment by JosefPihrt** [comment]
Thanks for the report.

Can you provide code sample to reproduce the bug?
