### ISSUE TITLE
Restore the underlining in the solution explorer

### ISSUE THREAD

**Issue by RichardMoran** [JosefPihrt/Roslynator#108]
I have been using this extension with VS2015 happily for a few weeks now, but the underlining feature in the solution explorer seems to have been removed. I find this incredibly useful and would like to see it put back or at least made optional.

**Comment by JosefPihrt** [comment]
Could you specify more precisely what do you mean by "underlining feature"?

**Comment by RichardMoran** [comment]
I used to get green and blue wavy underlining on files, folders and projects in the solution explorer in VS2015. If I hovered over a file that had the underlining, it would show me the improvements suggested by Roslynator. This seems to have disappeared since the latest update to the Roslynator extension. I have lost both the underlining and the hover information.

**Comment by RichardMoran** [comment]
Closing this as I've discovered this is actually an issue with Power Productivity Tools, not Roslynator. Sorry!
