### ISSUE TITLE
Bump version of Microsoft.CodeAnalysis dependency to 4.5.0

### ISSUE THREAD

**Issue by jamesHargreaves12** [JosefPihrt/Roslynator#1087]
The current version is 4.0.1 which means that there is no support for some of the more recent language features like  ListPatternSyntax (added in v4.3).

**Comment by JosefPihrt** [comment]
There are some problems with tests after update to 4.5.0 (hundreds of tests failing) so I'll make update to 4.4.0 which should be sufficient to be able to support new language features.
