### ISSUE TITLE
Suggestion: Refactoring - Combine Fluent Method Calls

### ISSUE THREAD

**Issue by wekempf** [JosefPihrt/Roslynator#109]
For example:

```csharp
stringBuilder.Append("Hello ");
stringBuilder.AppendLine(name);
```

Could be:

```csharp
stringBuilder.Append("Hello ")
    .AppendLine(name);
```

Code is cleaner and easier to understand when you don't have repeating lines starting with the same identifier. This is the same rationale for VB's with and C#'s initializer blocks.

The existing refactoring that optimizes StringBuilder calls should use the fluent approach as well.

**Comment by IanKemp** [comment]
@wekempf I think your 2nd example is missing a dot? :) I do like the suggestion though, +1.

**Comment by wekempf** [comment]
Why, yes it is. Strange... I'm sure I included it. I'll edit just so things are clear.

**Comment by JosefPihrt** [comment]
Thanks to 359502e4d105c027503d25cbcebb6420925dd57d the analyzer OptimizeStringBuilderAppendCall now uses fluent approach (method chaining).

**Comment by wekempf** [comment]
Great that that was changed. I assume because this is still open that you intend to add this as an analyzer/refactoring?

**Comment by JosefPihrt** [comment]
I would say yes as this seems like a good idea.

@wekempf What do you mean by "This is the same rationale for VB's with and C#'s initializer blocks"? I did not understand that.

**Comment by wekempf** [comment]
VBs "with" blocks look like this.

```vb
Dim aBook As New Book
With aBook
   .Name = "VB.Net Programming"
   .Author = "Zara Ali"
   .Subject = "Information Technology"
End With
```

Meanwhile, C#  has initializer blocks.

```csharp
var book = new Book {
   Name = "VB.NET Programming",
   Author = "Zara Ali",
   Subject = "Information Technology"
};
```
The rationale for both being in the language is to remove the redundancy of specifying the variable name repeatedly, making the code shorter and easier to understand. The same rationale exists for using fluent syntax.

**Comment by JosefPihrt** [comment]
Got it. Thanks for explanation.

**Comment by wekempf** [comment]
I've been looking at the implementation here. I'm not sure this implementation cuts it. You've got a switch statement that's inspecting method names that seem to be specific to StringBuilder. Method chaining should work more broadly than that. Haven't looked closely, but maybe you ensure this works for StringBuilder only, but that wasn't my intent when I asked for this.

Trying to give a good description here of how it should work makes me realize this is a pretty non-trivial thing to implement, though I think it can still be done. Might be that we can only support some limited scenarios at first, but it could be expanded on in later releases.

Start with the simple case. If two statements both are method calls using the same variable and the first returns the same type as that variable, chain them.

```csharp
Foo foo = GetFoo();
foo.DoSomething(); // returns Foo
foo.DoSomethingElse(); // aslo returns Foo
```

Should result in:

```csharp
Foo foo = GetFoo();
foo.DoSomething().DoSomethingElse();
```

If an assignment statement is followed by a method call (chain) that results in the same type as the variable assigned to you can chain those statements. So the last bit of code winds up in.

```csharp
Foo foo = GetFoo().DoSomething().DoSomethingElse();
```

There's other scenarios where chaining could be done as well (for instance, in fluent APIs it's not uncommon for the return types to be different in the middle of a call chain, for instance LINQ is intended to be fluent but some calls result in a different type, for instance OrderBy returns an IOrderedEnumerable instead of the IEnumerable<T> you called it from), but this is a good starting point.

Note that using this algorithm to chain may result in a change in behavior, so I see this as a refactoring and not as an analyzer. I don't think you can safely say that chaining should be done.

**Comment by JosefPihrt** [comment]
This is initial version of the analyzer. It probably will support more cases in future versions.

I'm interested in your note that this fix may result in a change in behavior. Could you be more specific?

**Comment by wekempf** [comment]
Just because an API returns the same type does not mean it returns the same instance, so changing from individual calls to a call chain isn't necessarily equivalent.

**Comment by JosefPihrt** [comment]
Could you give a code sample?

**Comment by wekempf** [comment]
```csharp
var clone = foo.Clone();
foo.SetBar(10);
```
This is obviously a contrived bit of code, but it should also be obvious that we can't chain these two and get equivalent results.

```csharp
var clone = foo.Clone().SetBar(10);
```
The original code intended to ```SetBar``` on the original instance, but because we chained we're doing it on the cloned instance instead. You can't generically know that any given API was intended to be used with "fluent chaining", so calling it out as a problem with an analyzer isn't a good idea. Making it easier to refactor code like this, however, *is* a good idea.

**Comment by JosefPihrt** [comment]
I understand that methods in your code sample cannot be chained. But I wouldn't say that it proves that **UseMethodChaining** feature cannot be implemented as an analyzer.

**Comment by wekempf** [comment]
The only way you can use it as an analyzer is to hard code it for specific APIs, which is very limited.

**Comment by JosefPihrt** [comment]
What is this assertion based on?

**Comment by wekempf** [comment]
Exactly what I just showed you. There is no way to tell if multiple calls can be chained without changing the behavior of the original code. Without being able to tell that, any analyzer is likely to report false positives.
