### ISSUE TITLE
Does it work with `C# Dev Kit`?

### ISSUE THREAD

**Issue by mystiquewolf** [JosefPihrt/Roslynator#1100]
[C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit&ssr=false#overview)
[Blog Article](https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/)

Apparently it replaces OmniSharp.

**Comment by JosefPihrt** [comment]
Bug tracked here: https://github.com/dotnet/roslyn/issues/68588

**Comment by JosefPihrt** [comment]
@mystiquewolf I just updated C# Dev Kit to latest version and it seems that it's fixed now.
