### ISSUE TITLE
SRCS119 Optimize StringBuilder.Append

### ISSUE THREAD

**Issue by mare25** [JosefPihrt/Roslynator#113]
SRCS1197 Optimize StringBuilder.Append generates sometimes wrong code. Try following example.

`public void CreateTable()
        {
            string tblName = "test";
            var sql = new StringBuilder();
            sql.Append("IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = '" + tblName + "')")
                .Append(" CREATE TABLE " + tblName + " (id uniqueidentifier)");
        }`

**Comment by JosefPihrt** [comment]
Thanks for the report @mare25 !

**Comment by mare25** [comment]
Roslynator supports me in my daily work. I like Roslynator! Thank you for your great tool! @JosefPihrt
