### ISSUE TITLE
RCS1102 Suggests Making a Sealed Partial Class Static

### ISSUE THREAD

**Issue by yannduran** [JosefPihrt/Roslynator#115]
If I have this **generated** class:

```
internal sealed partial class SealedPartialClass
{
    public const int PackageToolbar = 0xA001;
}
```
And I need to **add** a value to it:

```
internal sealed partial class SealedPartialClass
{
    public const int PackageMenu = 0xA002;
}
```

The RCS1102 analyser suggests making the class **static**. The fixer then changes both partial class declarations to from ```sealed``` to ```static```.

When the generated file gets regenerated, it gets changed back to ```sealed```, VS now generates an error:

> 'a class cannot be both ```sealed``` **and** ```static```.

**Comment by JosefPihrt** [comment]
Thanks for the report @yannduran !
