### ISSUE TITLE
Suggestion: Make SymbolRenamer and other internal APIs publicly accessible

### ISSUE THREAD

**Issue by naturecodevoid** [JosefPihrt/Roslynator#1156]
Hi, I'd like to be able to use Roslynator's SymbolRenamer class without a hacky solution like going through the CLI.

I'm sure there are a lot of other internal APIs that would be beneficial to API users.

Do you think this would be possible?

**Comment by JosefPihrt** [comment]
Hi,

I think it's good idea to make SymbolRenamer public. Please see the PR for the details.

Regarding the other API: currently there is no template for it but it's necessary to create an issue for each logical group of API and to describe the API in a way similar what is [here](https://github.com/JosefPihrt/Roslynator/pull/1161#issue-1852993052).

**Comment by naturecodevoid** [comment]
Thank you so much! Sorry I didn't get around to the unit tests.
