### ISSUE TITLE
partial keyword usage and WPF

### ISSUE THREAD

**Issue by bdovaz** [JosefPihrt/Roslynator#1174]
In WPF a control can be composed of an xaml file and an xaml.cs file.

In this case it has to have the keyword partial because the xaml file is compiled to code.

But roslynator doesn't seem to take this into account and tries to remove the keyword partial from classes that inherit from UserControl.

**Comment by JosefPihrt** [comment]
If that class always derives from UserControl then it should be possible to tweak analyzer to not report a diagnostic. Could you please post full name of the UserControl class?

**Comment by bdovaz** [comment]
Do you mean this?

https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.usercontrol?view=windowsdesktop-7.0

**Comment by JosefPihrt** [comment]
👍

**Comment by bdovaz** [comment]
> 👍

So it has a solution? Is there something missing? Can something be configured?

**Comment by JosefPihrt** [comment]
Are we talking about RCS1043, right?

It's necessary to check if the class symbol is derived from UserControl and to add some test.

https://github.com/JosefPihrt/Roslynator/blob/afe47e020e60983741f70206146b3155b79ecdd3/src/Analyzers/CSharp/Analysis/RemovePartialModifierFromTypeWithSinglePartAnalyzer.cs#L52

**Comment by bdovaz** [comment]
@JosefPihrt Do you change it? Or do I create a PR?

Thank you!

**Comment by JosefPihrt** [comment]
It would be great if you submit a PR.
