### ISSUE TITLE
Request: Analyzer + code fix to invert negation of if...else block

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#122]
```csharp
bool someValue = true;

if (!someValue)
    SomeValueFalse();
else
    SomeValueTrue();
```

can be rewritten as:

```csharp
bool someValue = true;

if (someValue)
    SomeValueTrue();
else
    SomeValueFalse();
```

The benefit is that the often-easy-to-overlook negation operator `!` is removed. (Sometimes I wish C# had adopted Pascal's `not` as its negation operator, because that was almost impossible to miss.)

**Comment by JosefPihrt** [comment]
I am not sure if this is a good idea for a general rule.

There is already the refactoring [SwapStatementsInIfElse](https://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/SwapStatementsInIfElse.md) which provides required functionality.
