### ISSUE TITLE
Missing format string params for FadeOut descriptions

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#124]
When the `DiagnosticDescriptor.MessageFormat` contains format item(s), multiple FadeOut warnings does not provide an item to replace into the warning string.

So for e.g. `a = a + 1` the description for RCS1089 is "Use {0} operator instead of assignment".
I didn't do an exhaustive search, but for at least RCS1002 it was also the case.

**Comment by JosefPihrt** [comment]
Does it matter when fade-out diagnostics are hidden?

**Comment by jnyrup** [comment]
No, the description had "{0}" in it both when hidden and hovering over the node, and when the diagnostics was set a warning and looking in the error list.

**Comment by JosefPihrt** [comment]
Oh, I see it now.
