### ISSUE TITLE
RCS1202 triggers on assignments

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#129]
```csharp
(variable as T).Property = value;
```
triggers RCS1202 and suggests
```csharp
(variable as T)?.Property = value;
```
which is invalid.

As the syntax error decribes: "Th left-hand side of an assignment must be a variable, property or indexer".

**Comment by JosefPihrt** [comment]
Diagnostic is correct because there is a risk of NullReferenceException, but the code fix is unapplicable in this case.
