### ISSUE TITLE
Offer string operations (interpolation, formatting, SB) when the caret is on a +

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#130]
Imagine this code:

    string var = "test";
    string s = "s" + var;

If the entire '"s" + var' is selected and the quick actions invoked, they correctly offer interpolation, StringBuilder, etc. The same should happen if the caret is just within the expression, for example, before or after the '+' sign. Right now no actions are offered.
Refactoring Essentials and/or C# Essentials do it so you could see their code for reference should you need to.

**Comment by JosefPihrt** [comment]
That sounds reasonable.

I know of two refactorings where it could be applied:
* JoinStringExpressions
* UseStringBuilderInsteadOfConcatenation
