### ISSUE TITLE
Analyzer for terminating empty types with a semicolon instead of { } [C# 12]

### ISSUE THREAD

**Issue by glen-84** [JosefPihrt/Roslynator#1316]
With C# 12, you can terminate empty types with a semicolon:

Before:

```cs
public interface IApplicationAssemblyMarker { }
```

After:

```cs
public interface IApplicationAssemblyMarker;
```

This is applicable to classes, records, and structs as well.

It looks a lot neater IMO.

**Comment by josefpihrt** [comment]
Good idea!
