### ISSUE TITLE
Suggest replacing a lambda with a method group

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#134]
Refactoring Essentials suggests converting the following code:

    list.Where(element => FullfillsCondition(element));

to:

    list.Where(FullfillsCondition);

when the caret is placed somewhere within the lambda, for example before, within or after =>. It also works when the caret is on the name of the method.

**Comment by ddobrev** [comment]
@JosefPihrt thank you very much for implementing my suggestions so quickly. Could you please share when I am going to enjoy them i.e. when do you plan a new release for?

**Comment by JosefPihrt** [comment]
@ddobrev It's been released!

**Comment by ddobrev** [comment]
@JosefPihrt thank you but you have only released it for VS 2017, see the version at the bottom right at https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017 and https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator .

**Comment by JosefPihrt** [comment]
I've just released version for VS2015.
