### ISSUE TITLE
.net core not available?

### ISSUE THREAD

**Issue by JCKodel** [JosefPihrt/Roslynator#139]
There are no code analysis menus anywhare on a .net core project:

![image](https://user-images.githubusercontent.com/379339/29232387-c33f2068-7ec1-11e7-888d-d9e5ec5ac6df.png)

Tried to create a ruleset for my project:
```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Streamline" ToolsVersion="15.0">
  <Rules AnalyzerId="Roslynator.CSharp.Analyzers" RuleNamespace="Roslynator.CSharp.Analyzers">
    <Rule Id="RCS1049" Action="None" />
  </Rules>
</RuleSet>
```

But the warning is still being displayed =\

![image](https://user-images.githubusercontent.com/379339/29232421-ea083a72-7ec1-11e7-8464-be4dc2f43568.png)

I don't want to ignore locally (because # are ugly =P) and I don't want to ignore on a Supression File because I would have to ignore every single instance.

Is there some way to configure Roslynator globally? (note: there are no RCS1049 in Roslynator options, as there are only code fixes (RCF) and refactorings (RR) available in Options)

Would be great if Code Analysers existed in Options (so we could have a default setting for every project, as we do for ReSharper).

**Comment by JosefPihrt** [comment]
I am confident that it is possible to specify ruleset for .net core project. Please see https://www.linkedin.com/pulse/supporting-roslyn-analyzers-visual-studio-2017-net-core-jake-brandt.

**Comment by JCKodel** [comment]
No change whatsoever, I'm afraid =\
While Visual Studio don't support it, nor we have those analysers in options, I guess my only option is ReSharper =\

**Comment by JosefPihrt** [comment]
Did you add CodeAnalysisRuleset element to your csproj? Can you show how your csproj file looks like?

**Comment by JCKodel** [comment]
My streamline.ruleset is a copy of another project (.net full, this time). There it was configurated using the VS UI.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <CodeAnalysisRuleSet>Streamline.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CavemanTools" Version="4.9.0" />
    <PackageReference Include="linq2db.Core" Version="1.8.3" />
    <PackageReference Include="linq2db.SqlServer" Version="1.8.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Database\SqlServer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SqlServer.generated.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Database\SqlServer.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SqlServer.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
```

**Comment by JosefPihrt** [comment]
Could you specify full path to your ruleset file and try again?

**Comment by JosefPihrt** [comment]
@JCKodel any progress?
