### ISSUE TITLE
Promote or introduce field

### ISSUE THREAD

**Issue by glmnet** [JosefPihrt/Roslynator#141]
I see there is the refactoring to promote a local to parameter, but no way to create a field on the current class?
I am missing this one very much.

**Comment by JosefPihrt** [comment]
I understand that you are requesting refactoring "Promote local to field",

Could you please provide some code sample where this would be useful?

**Comment by glmnet** [comment]
On Resharper you have: over any expression Introuce variable (which will do var) or Introduce field, which will popup the Introduce field allowing options like initialize in current member, field (inline), constructor, etc.
Also this option is not available on the light bulb over a local variable, but you can do Ctrl R, F over the local and the same popup will come up and replace this local with a field.

The objective is to store the local in a object field to later use it in another method.

May be the refactor should be "Introduce field for ..." right over some expression

Where this is useful, it depends, as everything it my be arguable if it a good practice or not to have it, but I am used to use it 

![image](https://user-images.githubusercontent.com/96162/29320405-75b1afac-81ad-11e7-935d-a651a28fa2cb.png)

**Comment by glmnet** [comment]
Yes!, and sorry for not being very explicit

**Comment by JosefPihrt** [comment]
Ok
