### ISSUE TITLE
Help Viewer

### ISSUE THREAD

**Issue by fdncred** [JosefPihrt/Roslynator#142]
I am using VS2017 with the Help Viewer installed locally.  Whenever I click on a link in the error list, such as RCS1102, it launches the help viewer and says, "No results were found.".  How do I make this follow the link to the web instead of trying to look locally?

Thanks,
Darren

**Comment by JosefPihrt** [comment]
This issue has to be handled by Microsoft so I created the issue in roslyn repo.

https://github.com/dotnet/roslyn/issues/23602
