### ISSUE TITLE
How to Invoke/Use?

### ISSUE THREAD

**Issue by blaster151** [JosefPihrt/Roslynator#143]
I've installed Roslynator for Visual Studio 2017, but I cannot find or figure out where to see or invoke its functionality anywhere in the application . . . :(

**Comment by JosefPihrt** [comment]
Did you install Visual Studio 15.3 meanwhile? I experienced that extension stop working after install 15.3 update. After reinstallation everything works fine.

Could you reinstall extension?

**Comment by JosefPihrt** [comment]
@blaster151 any progress?

**Comment by Ansssss** [comment]
I just installed Roslynator 2017 (1.4.55) and Roslynator Refactorings 2017 (1.4.55). I'm running Visual Studio Enterprise 2017 Version 15.1. I too do not see any new refactoring options....are they supposed to appear in the regular refactoring menu one can get to via the Ctrl+. menu?

**Comment by Ansssss** [comment]
And yes, I tried uninstalling and reinstalling, no effect. I can see no evidence of Roslynator in the Visual Studio window.

**Comment by blaster151** [comment]
Thanks for the response, @JosefPihrt . . . I had a fairly clean install of VS2017, but when I checked its About box, it shows me that it's only version 15.2.  You've mentioned 15.3, so I'm checking for updates (looks like there is one available) and will try uninstalling and reinstalling.  Thank you.  Can you help me know where to look for Roslynator after reinstalling - what the expected "entry point" should be?

**Comment by blaster151** [comment]
@Ansssss - 15.3 should be the latest; there was no "Check for Updates" in the Help menu but when I went into Tools | Extensions and Updates, I found an available Update for VS itself.  (I'm on Enterprise 15.2 also.)

**Comment by Ansssss** [comment]
@blaster151 - I'm not interested in installing the 15.3 update to Visual Studio at the moment due to an unrelated bug it has related to App Domains for tests. In any case, JosefPihrt was not indicating that 15.3 was needed, rather he was suggesting that an update of Visual Studio to 15.3 may have caused the Roslynator extension to fail. It turns out that is not the case for either of us (you're at 15.2, I'm at 15.1).

**Comment by JosefPihrt** [comment]
Do not install both Roslynator and Roslynator Refactorings as the latter is a subset of the former.

Update 15.3 is not required for running Roslynator.

There is no window "Roslynator" or main menu item. Roslynator features are accessible through Ctrl+. menu or through Error List. Diagnostics code starts with "RCS".

Could you check that your extension is not disabled?

**Comment by Ansssss** [comment]
I didn't change anything (other than restarting Visual Studio a few more times), but now the Roslynator refactor options are showing up in the Refactoring menu, and I do also see "RCS" messages in the Error List.

**Comment by JosefPihrt** [comment]
@Ansssss I'm glad that it's working!

**Comment by JosefPihrt** [comment]
@blaster151 any progress?
