### ISSUE TITLE
Suggest removing redundant else

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#145]
In cases such as:

    if (condition)
    {
        return;
    }
    else
    {}

the else is not needed so Roslynator should suggest removing it. Refactoring Essentials has this.

**Comment by JosefPihrt** [comment]
That analyzer already exists, but it is disabled by default (RemoveEmptyElseClause RCS1040).

**Comment by ddobrev** [comment]
@JosefPihrt I understand, thank you for the quick reply. I have read your documentation about analysers and I understand you want to use the built-in mechanism but do you think there might be a simpler way so that we don't have to drag along a custom set of rules?

**Comment by JosefPihrt** [comment]
I would be useful to enable/disable analyzers globally.

But you have to understand that entire proces of loading and executing analyzers is handled by hosting IDE (Visual Studio). I have no control over it I only provide libraries containing analyzers.

So I believe that this issue should be addressed to Microsoft.

**Comment by ddobrev** [comment]
@JosefPihrt I understand, thank you for the explanation.

**Comment by ddobrev** [comment]
@JosefPihrt this feature actually has a much wider scope and is therefore even more useful. It could work not just when a return statement is involved but also with a break or a goto switch case. While I fully understand your explanation, would you let me ask if you have any idea how RefactoringEssentials has it without needing a custom set of rules added to the project?

**Comment by JosefPihrt** [comment]
I am not sure if I'm following you. Are you talking about some feature that Refactoring Essentials has and Roslynator has not?

**Comment by ddobrev** [comment]
@JosefPihrt precisely.

**Comment by JosefPihrt** [comment]
How this feature works in Refactoring Essentials (from user's point of view)?

**Comment by ddobrev** [comment]
When the caret is placed right before, within or right after (), the light bulb suggests to remove it.

**Comment by ddobrev** [comment]
You can try it for yourself.

**Comment by JosefPihrt** [comment]
There is confusion about what is being discussed here.

I thought that you are talking about feature that would enable/disable analyzers globally.

Now I understand that you meant removing redundant else clause. But there are no parentheses in else clause.

**Comment by ddobrev** [comment]
@JosefPihrt it's my mistake, I didn't look at the title and I thought you were asking about the other feature I suggested today.
So - in RE the caret must be placed on the "else" and then the light bulb suggests its removal, along with any {} and indentation it might have.

**Comment by JosefPihrt** [comment]
There are two possible solution to this issue:

* enable analyzer RemoveEmptyElseClause by default.
* add refactoring RemoveEmptyElseClause that will be suggested when caret is on else token.

Which of these two options are you proposing?

**Comment by ddobrev** [comment]
The latter.

**Comment by JosefPihrt** [comment]
What I'm thinking about it maybe it would make more sense to create refactoring RemoveElseClause that would remove entire else clause including content (and nested if statements if any).

**Comment by ddobrev** [comment]
Why would you remove the content? This would change the existing behaviour which is against the definition of refactoring - plus the sheer deletion of important code.

**Comment by JosefPihrt** [comment]
Refactoring can change existing behaviour, analyzer should not.

**Comment by ddobrev** [comment]
Anyway, the point of this entire feature is that just the "else" itself is unnecessary. Compare:

```csharp
if (condition)
{
return;
}
else
{
doSthElse();
}
```
to:
```csharp
if (condition)
{
return;
}
doSthElse();
```

They are equivalent. However, what you're suggesting is for the second piece to be:

```csharp
if (condition)
{
return;
}
```

This is not equivalent and therefore incorrect.

**Comment by JosefPihrt** [comment]
Now I finally understand what you are suggesting.

Allow me to remind you that you could save us a lot of time by providing code sample immediately.

**Comment by ddobrev** [comment]
I guess you were mislead by my example "else" being empty. I'll be sure to provide a more complete sample next time.

**Comment by JosefPihrt** [comment]
#182
