### ISSUE TITLE
RCS1155 for more string comparisons

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#150]
RCS1155 currently recognizes these two cases of unnecessary allocations when comparing strings. 

```csharp
a.ToUpper() == b.ToUpper();
a.ToLower() == b.ToLower();
```

There are more cases, that could benefit from the same analysis to avoid allocations.

```csharp
a.ToUpperInvariant() == b.ToUpperInvariant();
a.ToLowerInvariant() == b.ToLowerInvariant();

a.ToUpper().StartsWith(b.ToUpper());
a.ToLower().StartsWith(b.ToLower());
a.ToUpperInvariant().StartsWith(b.ToUpperInvariant());
a.ToLowerInvariant().StartsWith(b.ToLowerInvariant());

a.ToUpper().EndsWith(b.ToUpper());
a.ToLower().EndsWith(b.ToLower());
a.ToUpperInvariant().EndsWith(b.ToUpperInvariant());
a.ToLowerInvariant().EndsWith(b.ToLowerInvariant());

a.ToUpper().IndexOf(b.ToUpper());
a.ToLower().IndexOf(b.ToLower());
a.ToLowerInvariant().IndexOf(b.ToLowerInvariant());
a.ToUpperInvariant().IndexOf(b.ToUpperInvariant());

a.ToUpper().LastIndexOf(b.ToUpper());
a.ToLower().LastIndexOf(b.ToLower());
a.ToUpperInvariant().LastIndexOf(b.ToUpperInvariant());
a.ToLowerInvariant().LastIndexOf(b.ToLowerInvariant());
```

Unfortunately .NET does not have a built-in overload for `Contains` that takes a `StringComparison`, but
```csharp
a.ToUpper().Contains(b.ToUpper());
a.ToLower().Contains(b.ToLower());
a.ToUpperInvariant().Contains(b.ToUpperInvariant());
a.ToLowerInvariant().Contains(b.ToLowerInvariant());
```

But they can be rewritten to avoid allocations by using `a.IndexOf(b, StringComparison) >= 0`

**Comment by mlsomers** [comment]
These should be warnings, not errors.
It's good to get these as a warnings, we do look at them and fix when applicable.
But as of Visual Studio Version 17.9.4 builds fail for multiple of these scattered through our code base...
That is not convenient when you need to get some more important work done!
