### ISSUE TITLE
Update Nuget vs VSX

### ISSUE THREAD

**Issue by silvioboehme** [JosefPihrt/Roslynator#151]
#72 
Sorry to reopen this one, but 3 month later I have the same effect.
VSX is available for the latest Version, but NuGet is 3 Month old (v 1.4.0).
Is it possible to release the Nuget version also frequently as the VSX version?

Or is there is reason for delaying the NuGet updates?

**Comment by JosefPihrt** [comment]
Hi,

Sorry to keep you waiting.

I will release next nuget in the next couple of days.

**Comment by silvioboehme** [comment]
Hi!

thank you for your great work. We use only StyleCop.Analyzers and Roslynator as a NuGet for a big project.

Why is there such a big delay between the VSR release and the Nuget one.
Do you need some help to test the NuGet Releases?

**Comment by JosefPihrt** [comment]
http://www.nuget.org/packages/Roslynator.Analyzers/1.5.0-rc

**Comment by JosefPihrt** [comment]
@silvioboehme 1.5.0 is out!

http://www.nuget.org/packages/Roslynator.Analyzers/1.5.0
