### ISSUE TITLE
RCS1085 for override properties

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#154]
```
class BaseClass
{
    public virtual bool Succes { get; set; }
}

class Derived : BaseClass
{
    private readonly bool m_Succes;

    public override bool Succes => m_Succes;
}
```

When applying RCS1085 `Success` in `Derived` in invalid.
> CS8080	Auto-implemented properties must override all accessors of the overridden property.

**Comment by jnyrup** [comment]
As always, I really apriciate the work you put into this great extension.

**Comment by JosefPihrt** [comment]
Thanks!
