### ISSUE TITLE
Rename file to match class name

### ISSUE THREAD

**Issue by jrmurdoch** [JosefPihrt/Roslynator#157]
Can you please add a refactor that will rename the file to match the class name?

This would also apply to interfaces, enums etc

I find I commonly change a class name and have to update the file manually.

Thanks,

**Comment by JosefPihrt** [comment]
That refactoring is already built in Visual Studio 15.3

![renamefiletomatchtypename](https://user-images.githubusercontent.com/11931318/30244965-c4e07ef6-95ca-11e7-8dff-700180ca4a3f.png)

**Comment by jrmurdoch** [comment]
I'm using VS 15.3.0 Preview 5.0

![image](https://user-images.githubusercontent.com/8064970/30245257-701b7008-9627-11e7-8939-bac8c72803d4.png)

The file is named Class1.cs

Maybe it missing from the preview build.

**Comment by JosefPihrt** [comment]
I have version 15.3.3

**Comment by thomaslevesque** [comment]
> That refactoring is already built in Visual Studio 15.3

It's not there in 16.x...

**Comment by remcoros** [comment]
@JosefPihrt it's not there in latest VS 16. Was this removed from roslyn?

**Comment by JosefPihrt** [comment]
@remcoros https://github.com/dotnet/roslyn/issues/24560
