### ISSUE TITLE
Feature request for IDE0009

### ISSUE THREAD

**Issue by nvmkpk** [JosefPihrt/Roslynator#158]
Can you implement [this](https://github.com/dotnet/roslyn/issues/21877) in this analyzer?

**Comment by JosefPihrt** [comment]
Could you provide a code sample so we are clear about what is being requested here?

**Comment by nvmkpk** [comment]
Currently I have my IDE settings to require `this.` to access the class members. Suppose I have a property `SomeProperty` defined. If I am refering to the property like `nameof(SomeProperty)`. It currently triggers warning IDE0009. I would like to suppress this warning (and optionally enforce not using `this.` in such cases (only inside `nameof`).

**Comment by JosefPihrt** [comment]
I cannot change behaviour of IDE0009 so I cannot suppress it inside nameof.

**Comment by nvmkpk** [comment]
I can understand you cannot suppress IDE0009 directly. But I think you can override or do something as stated in the link in the request? I do not have an understanding of how the analyzers work but I am assuming something can be done based on the conversation in that link. If nothing can be done then please feel free to close this.

**Comment by JosefPihrt** [comment]
I'm afraid I can't help you in this particular case.
