### ISSUE TITLE
Incorrect suggestion to remove parenthseses from an interpolated string

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#159]
Roslynator suggests to remove the parentheses from:

    $"about {(weeks == 1 ? "a week" : $"{weeks} weeks")} ago"

This results in:

    $"about {weeks == 1 ? "a week" : $"{weeks} weeks"} ago"

which doesn't compile.

**Comment by JosefPihrt** [comment]
This bug was fixed a long time ago in #34.

In which version are you experiencing it?

**Comment by ddobrev** [comment]
@JosefPihrt in the latest one, I'm afraid, 1.4.57.

**Comment by JosefPihrt** [comment]
Are you using Roslynator or Roslynator 2017?

**Comment by ddobrev** [comment]
2017, sorry for not specifying it in advance. I thought it didn't matter.

**Comment by JosefPihrt** [comment]
I have Roslynator 2017 1.4.57 installed. I tried code that you provided and RCS1032 is not reported.
