### ISSUE TITLE
RCS1095 suggests changes that may introduce functional differences

### ISSUE THREAD

**Issue by MHHenriksen** [JosefPihrt/Roslynator#160]
RCS1095 Use C# 6.0 dictionary initializer

There's a very important difference between initializing a Dictionary (and probably other types) with a collection initializer versus with a dictionary initializer: One calls `Add(k,v)` while the other calls `[k]=v`. The first one will throw for duplicate keys while the second one won't. This ought to be documented.

**Comment by JosefPihrt** [comment]
Hi,

Thanks for pointing that out.

I think that the best solution would be to keep the functionality but as a refactoring not an analyzer.

**Comment by MHHenriksen** [comment]
Sounds reasonable :)
