### ISSUE TITLE
Mark unused private methods for removal

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#164]
Refactoring Essentials doesn't have this but ReSharper does. It detects unused private methods and suggests their removal.

**Comment by wmjordan** [comment]
Maybe it is also applicable to mark removal for the `internal` keyword on types as well.

**Comment by JosefPihrt** [comment]
It is practically impossible to find unused internal methods because that would require to loop through each syntax tree in project (assembly).

**Comment by wmjordan** [comment]
Understood. It is hard to remove internal types.
