### ISSUE TITLE
"RCS1163	Unused parameter 'args'." does nothing

### ISSUE THREAD

**Issue by jojorne** [JosefPihrt/Roslynator#167]
Visual Studio 2017
1- Create a C# ConsoleApp
2 - Pass mouse over the parameter "string[] args" of the Main method
3a - Click at the "Quick Actions" icon or its arrow that is near the mouse
Result: Nothing happens.
3b - Use the shortcut for "Quick Actions" (Alt + Enter)
Result: Quick action menu appears.
3c - Click at the "Quick Actions" icon or its arrow that is near the margin
Result: Quick action menu appears.

Question: There is no refactoring to remove unused parameter in Quick Actions?

**Comment by JosefPihrt** [comment]
Hi,

Please use bulit-in "Change signature..." dialog to remove a parameter.

1. Click "Change signature..."
2. Select parameter to remove
3. Click Delete
4. Click Enter

I proposed https://github.com/dotnet/roslyn/issues/19612 which would make removal of a parameter faster.

**Comment by jojorne** [comment]
3a results in nothing where the expected behavior is opening the "Quick Actions" menu, is it a bug in Visual Studio 2017 or in Roslynator?

**Comment by JosefPihrt** [comment]
It seems that 3a will show only code fixes and there is actually no code fix for RCS1163.

Whereas 3b and 3c will show code fixes and refactorings.

"Change signature..." is considered to be a refactoring.

So it is a bug neither in Visual Studio nor in Roslynator.
