### ISSUE TITLE
RCS1132 remove redundant overriding member is not comparing method attributes

### ISSUE THREAD

**Issue by Tasteful** [JosefPihrt/Roslynator#168]
The `RCS1132:Remove redundant overriding member.` is adding messages to the error list if implementation only calling base-method.  

In this example below the implementation method is calling base-method but method is also decorated with attributes that not exists in base-class.

Example
```
public abstract class MyControllerBase 
{
    public virtual IHttpActionResult Delete(Guid systemId)
    {
          return ...;
    }
}

[RoutePrefix(DefaultRoutePrefix + "items")]
public class MyController : MyControllerBase 
{
    [Route("")]
    [HttpDelete]
    public override IHttpActionResult Delete(Guid systemId)
    {
          return base.Delete(systemId);
    }
}
```

**Comment by JosefPihrt** [comment]
This has been fixed with #165 but not released yet.
