### ISSUE TITLE
Request: Analyzer to detect and warn about unnecessary OfType<> invocations

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#172]
Consider the following code:

```csharp
interface IThing
{
    string Foo { get; set; }
}

class Thing : IThing
{
    public string Foo { get; set; }
}

static void Main()
{
    IEnumerable<IThing> things = new[] { new Thing { Foo = "bar" }, new Thing { Foo = "baz" } };
    var filteredThings = things.OfType<IThing>();

    Console,WriteLine(Enumerable.SequenceEqual(things, filteredThings)); // True
}
```

The `OfType<IThing>()` call is obviously unnecessary because it is already operating on a collection that is of type `IThing`, so an analyzer to detect and warn about such cases would be useful.

**Comment by jnyrup** [comment]
This won't work if the sequence contains nulls
```c#
IEnumerable<IThing> things = new IThing[] { null };
var filteredThings = things.OfType<IThing>();

Console.WriteLine(Enumerable.SequenceEqual(things, filteredThings)); // False
```

**Comment by JosefPihrt** [comment]
As @jnyrup pointed out, this proposal is applicable only for cases where `TResult` in `OfType<TResult>(this IEnumerable source)` is either value type of type parameter with `struct` constraint.

**Comment by jnyrup** [comment]
Still if `OfType<IThing>()` was used as a "trick" to filter out `nulls` `Where(e => e != null)` would be more performant.

I tried benchmarked it with an empty interface:

```c#
interface IThing {}
List<IThing>
```

```
   Method |    N |        Mean |      Error |     StdDev | Scaled | ScaledSD |  Gen 0 | Allocated |
--------- |----- |------------:|-----------:|-----------:|-------:|---------:|-------:|----------:|
    Where |   10 |    165.4 ns |   3.317 ns |   3.257 ns |   0.81 |     0.02 | 0.0355 |     112 B |
   OfType |   10 |    205.4 ns |   2.405 ns |   2.132 ns |   1.00 |     0.00 | 0.0432 |     136 B |
    Where |  100 |    845.1 ns |   7.774 ns |   7.272 ns |   0.67 |     0.01 | 0.0353 |     112 B |
   OfType |  100 |  1,253.0 ns |  13.723 ns |  12.836 ns |   1.00 |     0.00 | 0.0420 |     136 B |
    Where | 1000 |  7,838.9 ns | 131.695 ns | 109.971 ns |   0.67 |     0.01 | 0.0305 |     112 B |
   OfType | 1000 | 11,732.7 ns | 168.284 ns | 140.525 ns |   1.00 |     0.00 | 0.0305 |     136 B |
```

`Where(e => e != null)` is both faster and the intent (at least in my opinion) is more clear.
The numbers are almost identical `Where(e => !ReferenceEquals(e, null))` if you to guard against overriden `!=` operator.

So maybe mark `thing.OfType<IThing>()` as suspicious and _suggest_ replacing it with `Where` if you wants to filter out nulls?

**Comment by JosefPihrt** [comment]
@jnyrup Sounds good.

**Comment by LesRamer** [comment]
Another way of 'not null' testing some might appreciate:
```csharp
.Where(e => !(e is null))
```
