### ISSUE TITLE
Request: Codefix to detect, warn about and remove about unnecessary applications of SerializableAttribute

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#176]
All value types in the .NET Framework are implicitly serializable, so there isn't really any good reason to apply the `SerializableAttribute` to them. For example, the following is redundant:

```csharp
[Serializable] // does nothing
public enum MyEnum
{
    ItemOne,
    ItemTwo,
}
```

(Yes, I know this extremely minor and every other bug/feature request is literally more important, but I just want to report it to prevent myself from forgetting about it. :) )

**Comment by JosefPihrt** [comment]
Could you please provide some reference to your statement that "all value types are implicitly serializable".
