### ISSUE TITLE
The extension disables itself all the time

### ISSUE THREAD

**Issue by alexandretperez** [JosefPihrt/Roslynator#18]
I don't know if this problem happen just with me but every time that I open Visual Studio, the extension starts disabled and I need go to Extensions and Updates to re-enable it.

Any clue about this?

**Comment by JosefPihrt** [comment]
Hi, I know of two possible fixes:

* **Clear MEF Component Cache**:
  * Clean folder %localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache.
  * https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd 
* **Delete duplicate extensions**:
  * Folder %localappdata%\Microsoft\VisualStudio\14.0\Extensions should contain only one folder with Roslynator extension.
  * https://github.com/remcoros/DuplicateExtensionFinder

Also please see https://github.com/madskristensen/WebEssentials2013/issues/1959.
