### ISSUE TITLE
Request: returning null from a non-async method that returns Task<T>

### ISSUE THREAD

**Issue by Vivelin** [JosefPihrt/Roslynator#180]
If I have a method that returns **Task\<T>** (or **Task**) but is not marked as `async`, returning `null` is very unlikely to be the intention, as that will only result in a **NullReferenceException** when it is inevitably awaited.

I think it would be nice to see an analyzer for this situation and possibly a code fix that suggests returning `Task.FromResult<T>(null)` instead.

For example, consider:

```c#
public Task<User> GetUserAsync(string emailAddress)
{
    return Context.Users.SingleOrDefaultAsync(x => x.EmailAddress == emailAddress);
}
``` 

There's no reason to add `async`/`await` here (in fact, there's **RCS1174**), but when I want to add a check to make sure empty email addresses are ignored, it's all too easy (_and wrong_) to simply add the following:

```c#
if (string.IsNullOrEmpty(emailAddress)) 
    return null;
```

Unfortunately, there's no warning built into Visual Studio itself, and the resulting **NullReferenceException** is not very helpful either. It'd be great if I could use a code fix to turn it into the following:

```c#
if (string.IsNullOrEmpty(emailAddress)) 
    return Task.FromResult<Person>(null);
```

**Comment by JosefPihrt** [comment]
@Vivelin Sounds good.

**Comment by Vivelin** [comment]
Nice! I'm curious why you chose to use severity Info rather than Warning, though.

**Comment by JosefPihrt** [comment]
Why do you think it should be warning?

**Comment by Vivelin** [comment]
While it's _technically_ valid, I find it hard to imagine a scenario where you want to purposefully return `null` instead of a **Task** that returns `null`, and since `await null` throws a **NullReferenceException**, I think it warrants a warning.

And if you're writing code that interacts with Task objects (rather than simply writing asynchronous code) and are expecting this behavior, you can always suppress it or turn it off.

**Comment by JosefPihrt** [comment]
Ok, let's change it to warning.
