### ISSUE TITLE
Suggest removal of redundant parentheses

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#181]
In this code:

    new MyClass() { MyProperty = 1 }

() is not necessary. Roslynator should therefore suggest removing it.

**Comment by JosefPihrt** [comment]
There is [RCS1067](http://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1067.md).

It depends on user's preference whether to remove parentheses or not so this analyzer is not enabled by default.
