### ISSUE TITLE
Request: Use concatenation instead of string interpolation

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#185]
Refactor from:
````C#
var s = $"{Name} is cool".ToUpper();
````
to:
````C#
var s = (Name + " is cool").ToUpper();
````

**Comment by wmjordan** [comment]
BTW, the concatenation is performing about 5 times faster than `String.Format` (string interpolation).

**Comment by JosefPihrt** [comment]
Do you propose refactoring or analyzer?

**Comment by wmjordan** [comment]
I am currently using the refactor tool of _Roslynator_.
This feature comes from this place:
https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1105.md
And it is implemented.
Would it be possible to refactoring between string interpolations and string concatenations?
So, for performance concern, we prefer string concatenation over string interpolation, and for readability concern and coding experience, we can refactor the string concatenation back to string interpolation and refactor it back afterward.

**Comment by KrisVandermotten** [comment]
Anyone interested in this analyzer and code fix can [install it from the marketplace](https://marketplace.visualstudio.com/items?itemName=vs-publisher-363830.U2UConsultPerformanceCodeAnalyzersforC7).

I also have a [pull request](https://github.com/dotnet/roslyn/pull/22595) to do this optimization directly in the compiler. If and when that is accepted, the analyzer won't be needed anymore.

**Comment by wmjordan** [comment]
Thank you for making this pull request to the compiler!
It benefits so many people!
