### ISSUE TITLE
Suggest adding a using for IDisposable

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#188]
Let's have this code:

    IDisposable disposable = new Disposable();

When the caret is placed on the name of the variable ("disposable"), Roslynator should suggest wrapping it in a using statement taking into account all usages of the variable below.

**Comment by JosefPihrt** [comment]
There is [RR0177](http://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0177.md).

It requires to select statements that should be wrapped.

**Comment by ddobrev** [comment]
@JosefPihrt thank you, what you're saying definitely works. There are two issues I can see, though:

1. It requires, as you warned, to select the entire statement while it could work - and does in Refactoring Essentials - instead of simply placing the caret on the variable which is much easier;

2. It does not always work, for example, take this line from Xamarin.Android:
    var imageView = this.FindViewById<ImageView>(Resource.Id.imageView);

So you can definitely make this even better.
