### ISSUE TITLE
Roslynator suggests removing () from a bitwise &

### ISSUE THREAD

**Issue by ddobrev** [JosefPihrt/Roslynator#189]
Roslynator suggests removing parentheses from:

    if ((Property & Enum.Field) != 0)

which leads to invalid code.

**Comment by JosefPihrt** [comment]
[RR0106](http://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0106.md) is very simple refactoring that removes parentheses without any further checks.

Benefit of this refactoring is that you don't have to move between opening and closing parentheses to remove them.
 
It can lead to invalid code sometimes.
