### ISSUE TITLE
Feature Request: Provide refactoring for #76

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#192]
Is it possible to add  #76 to the refactoring tool as well?

**Comment by JosefPihrt** [comment]
Why?

I has been added as [RCS1181](http://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1181.md).

**Comment by wmjordan** [comment]
'Cause I was not using the analyzer, and I could not find it in the refactor.

**Comment by JosefPihrt** [comment]
Oh, you use Roslynator Refactorings, right?

**Comment by wmjordan** [comment]
Yep. Please :)
