### ISSUE TITLE
RCS1140: doesn't seem to recognize comments for generic exceptions

### ISSUE THREAD

**Issue by sergey-rybalkin** [JosefPihrt/Roslynator#193]
Analyzer RCS1140 in version 1.5.0 seems to report false positives with exceptions of custom generic types. See example below:

        /// <exception cref="Exception{EmptyAssemblyExceptionArgs}">
        /// Indicates that the specified assembly does not contain any command definitions.
        /// </exception>
        public static void Foo()
        {
                throw new Exception<EmptyAssemblyExceptionArgs>(args);
        }

The analyzer still reports that exception thrown is not documented.

**Comment by JosefPihrt** [comment]
https://github.com/dotnet/roslyn/issues/22923
