### ISSUE TITLE
Analyse / Run Code Analysis  does not show any new issue

### ISSUE THREAD

**Issue by BuhTig4ever** [JosefPihrt/Roslynator#198]
I configured Roslynator like suggested and verified that it give me a hint (with question mark) at a place where it was expected. But when running Analyse / Run Code Analysis I get exactly the warnings as with Microsoft recommended rules. What I am doing wrong?

**Comment by JosefPihrt** [comment]
Roslyn code analysis runs in the background as you type. It is not necessary to click "Run Code Analysis".

**Comment by BuhTig4ever** [comment]
Thank you for the fast answer. I am sitting in front of a project with about 50.000 lines C# code and would find such a functionality very useful.

**Comment by JosefPihrt** [comment]
Which product did you install? Roslynator 2017, Roslynator Refactorings 2017 or Roslynator.Analyzers (nuget)?

Do you see any diagnostics in the Error List?

**Comment by BuhTig4ever** [comment]
It was Roslynator 2017

**Comment by JosefPihrt** [comment]
I'm not sure from your answer if you see diagnostics or not.

I closed this issue because I haven't receive answer for two days so I supposed that you solved the problem.

**Comment by BuhTig4ever** [comment]
Sorry, I have only access to this mail account during workdays and living in another time zone.
If I run Analyse / Run Code Analysis / On Solution I usually get a list of warnings / hints. In References / Analyzers / Open Active Rule Set I see also the Roslynator.CSharp.Analyzers. I assumed I will find Warning that start with 'RCS' and did not see any. This was the start point asking me, what I am doing wrong.
I run it now again with all rules enabled for Roslynator and see no warnings starting with 'RCS'. I cannot believe the me and my colleagues write such perfect code :-)

**Comment by BuhTig4ever** [comment]
I think I found it. The expected messages show up with "Build + IntelliSense". Great. 
Thank you
Ferdinand

**Comment by JosefPihrt** [comment]
Great!
