### ISSUE TITLE
RCS1104 has an invalid refactoring

### ISSUE THREAD

**Issue by jnyrup** [JosefPihrt/Roslynator#20]
````
int a = 1;
bool b = a == 1 ? false : true;
````

The suggested refactoring is: `!a == 1`, which of course should either be `!(a==1)` or (for this example) `a != 1`. 
I guess `a != 1` would only be a non-changing refactoring if `!=` is semantically equivalent to `!(==)`. 
In general that should be a valid assumption, but I don't think that is necessarily true for custom types with operator overloads, even though it should.

**Comment by JosefPihrt** [comment]
Thanks for the report @jnyrup !
