### ISSUE TITLE
RCS1146 in multiple conditions

### ISSUE THREAD

**Issue by nvmkpk** [JosefPihrt/Roslynator#203]
When I have a condition like below:
`this.splitView != null && (this.splitView.DisplayMode == SplitViewDisplayMode.Overlay && this.splitView.IsPaneOpen)`

This analyzer should add the '?' to all conditions. It only does it to the first one.
Expected:
`this.splitView?.DisplayMode == SplitViewDisplayMode.Overlay && this.splitView?.IsPaneOpen == true`
Actual:
`this.splitView?.DisplayMode == SplitViewDisplayMode.Overlay && this.splitView.IsPaneOpen`

**Comment by JosefPihrt** [comment]
It is not necessary to add conditional access to second expression because it is evaluated only if `this.splitView` is not null.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-and-operator

**Comment by nvmkpk** [comment]
What if we have `or` rather than `and`?

**Comment by JosefPihrt** [comment]
Then RCS1146 will not be reported.
