### ISSUE TITLE
Proposal: Add to interface in refactorings

### ISSUE THREAD

**Issue by Zyxious** [JosefPihrt/Roslynator#208]
Say that I have a class MyClass that implements IMyInterface.

When creating a new public method in MyClass I would like to add this to IMyInterface.

My proposal is that when the cursor is on the method signature line I would get a suggestion to add the method to one of the interfaces that the class is implementing.

In this case I would get "Add to interface 'IMyInterface'"

**Comment by wmjordan** [comment]
I also love to have this feature.
