### ISSUE TITLE
Update NuGet

### ISSUE THREAD

**Issue by dwenegar** [JosefPihrt/Roslynator#209]
Could you update the NuGet package?
Thanks.

**Comment by JosefPihrt** [comment]
@dwenegar https://www.nuget.org/packages/Roslynator.Analyzers/1.6.0-rc

1.6.0 will follow within 1-2 weeks.

**Comment by JosefPihrt** [comment]
https://www.nuget.org/packages/Roslynator.Analyzers/1.6.0
