### ISSUE TITLE
Analyzer show errors

### ISSUE THREAD

**Issue by GraySerg** [JosefPihrt/Roslynator#21]
Severity:Warning	
Code:AD0001	
Description:Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.IfStatementSyntaxDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	
Project:<Unknown>		
Line:1	
Active

**Comment by JosefPihrt** [comment]
Thanks for the report @GraySerg !
