### ISSUE TITLE
RCS1138 fails to give warning with Attributes

### ISSUE THREAD

**Issue by Debbus72** [JosefPihrt/Roslynator#213]
_RCS1138: Add summary to documentation comment_

Found this problem in our code-base: 

This will trigger a RCS1138:
```
      /// <summary></summary>
      public string Name { get; set; }
```
This will NOT trigger a RCS1138:
```
      /// <summary></summary>
      [Required]
      public int Key { get; set; }
```

**Comment by JosefPihrt** [comment]
Thanks for the report @Debbus72 !
