### ISSUE TITLE
Porposal: inject properties from constructor

### ISSUE THREAD

**Issue by MovGP0** [JosefPihrt/Roslynator#216]
Given I have a class that looks like: 

```csharp
public sealed class MyClass
{
    private ISomeClass SomeClass { get; }

    public MyClass()
    {
    }
}
```
than it should refactor to: 
```csharp
public sealed class MyClass
{
   private ISomeClass SomeClass { get; }

    public MyClass(ISomeClass someClass)
    {
        SomeClass = someClass ?? throw new ArgumentNullException(nameof(someClass))
    }
}
```

**Comment by JosefPihrt** [comment]
There is built-in refactoring for this, but you have to select entire property declaration (line).

![generateconstructor](https://user-images.githubusercontent.com/11931318/33441616-5f41febc-d5f3-11e7-82b5-50b318f2c821.png)
