### ISSUE TITLE
Roslynator has high impact on VS Editor performance in 15.5 Preview

### ISSUE THREAD

**Issue by xperiandri** [JosefPihrt/Roslynator#217]
Experienced in Preview 4 and Preview 5
Editor is very slow on writing code

**Comment by JosefPihrt** [comment]
I've just installed 15.5.0 (not preview) and I'm not experiencing any visible changes in performance.

Could you install 15.5.0 and tell me if the problem persists?

**Comment by xperiandri** [comment]
How could you install 15.5 RTM if it is not released?
15.4.5 is RTM version

**Comment by xperiandri** [comment]
Well maybe it is not an issue of Roslynator in general but it's behavior on solution when project is quite big.

**Comment by JosefPihrt** [comment]
15.5 is out, see https://www.visualstudio.com/cs-cz/news/releasenotes/vs2017-relnotes

![about](https://user-images.githubusercontent.com/11931318/33634207-b1749c8e-da13-11e7-924f-bbf3700d4919.png)
