### ISSUE TITLE
Proposal: Add refactoring MergeIfWithParentIf

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#218]
The first two `if`s could be merged together but `RR0075` wouldn't show up.

````C#
if (a > 0) {
	if (aa.Length < (a << 1)) {
		Array.Resize(ref c, aa.Length << 1);
	}
}
else {
	c = new byte[d << 1];
}
````

**Comment by JosefPihrt** [comment]
This is not how the RR0075 is supposed to work.

RR0075 will refactor
```csharp
if (x)
{
}

if (y)
{
}
```
into
```csharp
if (x || y)
{
}
```

However, it seems that you proposing change from
```csharp
if (x)
{
	if (y)
	{
	}
}
else
{
}
```
to
```csharp
if (x && y)
{
}
else
{
}
```
It could be new refactoring MergeIfStatementWithNestedIfStatement (similar to [RCS1061](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1061.md)).

**Comment by wmjordan** [comment]
Thank you for pointing this out.
Personally I never met with a situation which needed what `RR0075` currently doing, but frequently merging nested `if` statements.
Please bring that refactoring to the refactor component.
