### ISSUE TITLE
Visual Studio 2017 RC support

### ISSUE THREAD

**Issue by ghoeppner** [JosefPihrt/Roslynator#22]
When can we expect Visual Studio 2017 RC support?

**Comment by JosefPihrt** [comment]
Soon.

**Comment by MoamenMohamed** [comment]
any updates?

**Comment by JosefPihrt** [comment]
There you go.

* [Roslynator 2017](http://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017)
* [Roslynator Refactorings 2017](http://marketplace.visualstudio.com/items?itemName=josefpihrt.RoslynatorRefactorings2017)

**Comment by abeperl** [comment]
![image](https://cloud.githubusercontent.com/assets/6117184/21647635/12fcaf4a-d269-11e6-9f12-0088cc699281.png)


1/4/2017 10:29:05 AM - Microsoft VSIX Installer
1/4/2017 10:29:05 AM - -------------------------------------------
1/4/2017 10:29:05 AM - Initializing Install...
1/4/2017 10:29:05 AM - Extension Details...
1/4/2017 10:29:05 AM - 	Identifier         : 9289a8ab-1bb6-496b-9992-9f7ea27f66a8
1/4/2017 10:29:05 AM - 	Name               : Roslynator 2017
1/4/2017 10:29:05 AM - 	Author             : Josef Pihrt
1/4/2017 10:29:05 AM - 	Version            : 1.1.95
1/4/2017 10:29:05 AM - 	Description        : A collection of 110+ analyzers and 160+ refactorings for C#, powered by Roslyn.
1/4/2017 10:29:05 AM - 	Locale             : en-US
1/4/2017 10:29:05 AM - 	MoreInfoURL        : http://github.com/JosefPihrt/Roslynator
1/4/2017 10:29:05 AM - 	InstalledByMSI     : False
1/4/2017 10:29:05 AM - 	SupportedFrameworkVersionRange : [4.5,)
1/4/2017 10:29:05 AM - 
1/4/2017 10:29:05 AM - 	SignatureState     : Unsigned
1/4/2017 10:29:05 AM - 	Supported Products : 
1/4/2017 10:29:05 AM - 		Microsoft.VisualStudio.Community
1/4/2017 10:29:05 AM - 			Version : [15.0,16.0)
1/4/2017 10:29:05 AM - 		Microsoft.VisualStudio.Pro
1/4/2017 10:29:05 AM - 			Version : [15.0,16.0)
1/4/2017 10:29:05 AM - 		Microsoft.VisualStudio.Enterprise
1/4/2017 10:29:05 AM - 			Version : [15.0,16.0)
1/4/2017 10:29:05 AM - 
1/4/2017 10:29:05 AM - 	References         : 
1/4/2017 10:29:05 AM - 		-------------------------------------------------------
1/4/2017 10:29:05 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
1/4/2017 10:29:05 AM - 		Name         : Visual Studio MPF 15.0
1/4/2017 10:29:05 AM - 		Version      : [15.0,16.0)
1/4/2017 10:29:05 AM - 		MoreInfoURL  : 
1/4/2017 10:29:05 AM - 		Nested       : No
1/4/2017 10:29:05 AM - 
1/4/2017 10:29:05 AM - Signature Details...
1/4/2017 10:29:05 AM - 	Extension is not signed.
1/4/2017 10:29:05 AM - 
1/4/2017 10:29:05 AM - Searching for applicable products...
1/4/2017 10:29:10 AM - Found installed product - Microsoft Visual Studio Professional 2015
1/4/2017 10:29:10 AM - Found installed product - Microsoft Visual Studio Community 2015
1/4/2017 10:29:10 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
1/4/2017 10:29:10 AM - Found installed product - Global Location
1/4/2017 10:29:10 AM - Found installed product - ssms
1/4/2017 10:29:10 AM - Found installed product - ssms
1/4/2017 10:29:10 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()


sure have 2017 RC

![image](https://cloud.githubusercontent.com/assets/6117184/21647705/53f5fef2-d269-11e6-91d0-3c76512004b0.png)

**Comment by JosefPihrt** [comment]
Continues in #30 @abeperl.
