### ISSUE TITLE
Cannot apply rules to files under source control

### ISSUE THREAD

**Issue by Giois93** [JosefPihrt/Roslynator#226]
It seems to me applying a rule to all solution files does not work if the solution is under source control (TFS in my case).

I tried to apply different rules to all solution files and VS checked them out for edit but does not edit them at all. If I try a second time (now that files are checked-out) it works fine.

**Comment by JosefPihrt** [comment]
Hi,

Sorry for late answer.

I'm not familiar TFS. Nevertheless, I believe that this issue does not seem to have anything to do with Roslynator. It can be problem in Visual Studio or in TFS.
