### ISSUE TITLE
Add braces to if statement not triggering an error

### ISSUE THREAD

**Issue by sheam** [JosefPihrt/Roslynator#228]
I have add Braces (RCS1001) and Add braches to if-else (RCS(1003) both set to error.

But I don't see any error in the IDE or compiler output. If I check Add Braces (IDE0011) in the MS Code analysis analyzer it does work.

![image](https://user-images.githubusercontent.com/1779211/34012621-2674c60e-e0da-11e7-8e9a-31f25a1b7db9.png)
![image](https://user-images.githubusercontent.com/1779211/34012636-34dcb80a-e0da-11e7-8602-8ea96993fb93.png)

**Comment by JosefPihrt** [comment]
IDE0011 is probably equivalent to [RCS1007](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1007.md) (Avoid embedded statement).

RCS1001 is suggested when embedded statement (or condition) is multi-line.

```csharp
if (x)
    Foo(y, z); // this will not trigger RCS1001

if (x)
    Foo( // this will trigger RCS1001
        y,
        z);
```

I understand that name of RCS1001 can be misleading as there is built-in analyzer with same name and different functionality.

I will think about changing name of this analyzer.
