### ISSUE TITLE
CLR types over Native types in C#

### ISSUE THREAD

**Issue by sheam** [JosefPihrt/Roslynator#229]
Is there a configuration that will show `string myVar = "test";` as an error, and `String myVar = "test";` as correct?

We prefer the CLR types (don't ask why) and previously used resharper to enforce this.

**Comment by JosefPihrt** [comment]
This can be achieved with IDE0014 and IDE0015.

**Comment by sheam** [comment]
Thanks. I was only looking in the Rolsynator analyzer.
