### ISSUE TITLE
Proposal: Initialize field from constructor

### ISSUE THREAD

**Issue by orobert91** [JosefPihrt/Roslynator#230]
It's all in the title. Currently we can generate constructor from fields, but not add field to an existing constructor. This is the refactoring I miss the most from ReSharper.

**Comment by JosefPihrt** [comment]
There is refactoring [Introduce and initialize field](http://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0064.md).

**Comment by orobert91** [comment]
It's not quite the same thing, my request is for an already existing field, have the ability to add it to the constructor. The refactoring above is for fields that do not currently exist.

**Comment by JosefPihrt** [comment]
Please provide a code sample and more detailed description.

Right now I'm not exactly clear about what is being proposed.

Thanks.

**Comment by orobert91** [comment]
Given:

```
public class MyClass
{
        private int _myField1;
        private int _myField2;

        public MyClass(int _myField1) {
                _myField1 = myField1
        }
}
```

When I choose `Initialize field from constructor` on `private int _myField2` using ReSharper, it gets added to the constructor like this:

```
public class MyClass
{
        private int _myField1;
        private int _myField2;

        public MyClass(int myField1, int myField2) {
                _myField1 = myField1;
                _myField2 = myField2;
        }
}
```

We currently can't do this with Roslynator. I think that introducing new fields in a class is a pretty frequent enough use-case to consider adding this feature.

**Comment by JosefPihrt** [comment]
What if there are multiple constructors?

**Comment by orobert91** [comment]
I don't have ReSharper anymore on hand, so I don't know what was the behavior for the specific case, but I believe it asked which constructor. If this is not feasible, then you could just add it to all constructors by default?

**Comment by MarkusAmshove** [comment]
ReSharper adds them to all constructors:

![2017-12-23_19-44-24](https://user-images.githubusercontent.com/2401875/34321903-bdd89520-e819-11e7-8fe5-ddc7c31d041c.gif)

**Comment by orobert91** [comment]
To be consistent with the behavior of others refactoring (ie the 'Encapsulate field' refactoring), you might wanna consider spanning the trigger of this refactoring to the whole statement, not just the field itself.

For exemple:
`private int _myField;`

The refactoring is proposed only when selecting `_myField`. It should be proposed for the whole `private int _myField;` statement as well.

**Comment by JosefPihrt** [comment]
Could you create a new issue? Thanks.

**Comment by orobert91** [comment]
Done. https://github.com/JosefPihrt/Roslynator/issues/258
