### ISSUE TITLE
Refactoring RR0195 appears to do nothing when triggered

### ISSUE THREAD

**Issue by pyrocumulus** [JosefPihrt/Roslynator#231]
Hello Josef,

I was pleasantly surprised when I noticed RR0195 (Extract member to interface) in the recent update for Roslynator. It would be quite beneficial to my professional work. It seems to trigger on the right spots however I cannot make it actually add the member to the interface it detects.

I originally found this problem when the interface is in a separate project (an Public API assembly) inside the same solution. It triggers in the right situation and detects the right interface to add it to, however when I trigger it it does nothing. I tried manually checking out the interface file before triggering to no avail. 
When I tried to do this refactoring on an interface in the same project it also seems to detect correctly but also does nothing. So it's not something with the separate project per se. And I have the same problem in different projects/solutions.

I haven't been able to actually refactor using this refactoring yet. Are more users experiencing this problem?

My version info is:

- Microsoft Visual Studio Professional 2017 
- Version 15.5.2
- VisualStudio.15.Release/15.5.2+27130.2010
- Roslynator 1.6.0

**Comment by JosefPihrt** [comment]
Thanks for the report @pyrocumulus !

In 1.6.0 the refactoring works only when interface declaration is located in the same document as member declaration. I have fix it.

**Comment by JosefPihrt** [comment]
@pyrocumulus 1.6.10 is out.

**Comment by pyrocumulus** [comment]
@JosefPihrt Thanks! I'll try it asap 👍

**Comment by pyrocumulus** [comment]
@JosefPihrt it works brilliantly! Even when the interface is in another project in my solution.
This is a refactoring I will be using a whole lot, thanks!

Happy holidays! 🎄

**Comment by JosefPihrt** [comment]
I'm glad you like it!

Merry Christmas!
