### ISSUE TITLE
Analyzers missing in Roslynator 1.1.6.1

### ISSUE THREAD

**Issue by wilhelmmedetz** [JosefPihrt/Roslynator#24]
After installing Roslynator 1.1.6.1 several analyzers are missing (Visual Studio 2015 Professional)

eg. RCS1100, RCS1101, RCS1102, RCS1103, RCS1104, RCS1105

Uninstalling and reinstalling Roslynator did not help.

**Comment by JosefPihrt** [comment]
I am not sure why this problem occurs.

Please install newest version 1.1.7. It should help.

**Comment by wilhelmmedetz** [comment]
1.1.7 fixed the problem.

Thanks
