### ISSUE TITLE
Roslynator causes crash in VS2015 with expression-bodied member with argument

### ISSUE THREAD

**Issue by JoeBourassa** [JosefPihrt/Roslynator#240]
With Roslynator enabled in VS105, I attempted to open a file with the following line of code:
`private static string GetBuffer(int numberChars) => new string(' ', numberChars);`

VS then crashed.

Either refactoring this line to not use the expression-bodied syntax or disabling Roslynator caused VS to no longer crash.

**Comment by JosefPihrt** [comment]
Thanks for reporting this issue @JoeBourassa !

New version 1.6.12 has been released.
