### ISSUE TITLE
Wrong RCS1213 Message

### ISSUE THREAD

**Issue by kkadir** [JosefPihrt/Roslynator#243]
```csharp
...
...
private Window _parentWindow;
...
...
public Window ParentWindow
{
    get
    {
        return _parentWindow;
     }
     set
     {
        if (Equals(_parentWindow, value))
        {
            return;
        }
        _parentWindow = value;
        ...
    }
}
```

Even if the private field `_parentWindow` is used by its corresponding property, I get an `RCS1213: Remove unused field declaration` message.

**Comment by JosefPihrt** [comment]
Please install latest version 1.6.20 that fixes the issue.

**Comment by kkadir** [comment]
Hello, @JosefPihrt I wasn't aware of the update, thanks for the info and sorry for the inconvenience.

**Comment by JosefPihrt** [comment]
I released new version about the same time as you posted the issue, so it was just coincidence.
