### ISSUE TITLE
RCS1163 unused parameter error...

### ISSUE THREAD

**Issue by usmrtester** [JosefPihrt/Roslynator#244]
.net 4.0, c# 7.2 Roslynator 1.6.10

The following line of code produces RCS1163, Unused parameter (list). I believe this to be an error as 'list' is required for this lambda expression.

`lReasons = lReasons.OrderBy(list => ranDom.Next()).ToList();`

**Comment by JosefPihrt** [comment]
RCS1163 is reported when parameter (or lambda parameter) is not used which is exactly this case.

Common approach to this concrete case would to to suppress this diagnostic \(see [How to Suppress](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1163.md)\).

Also, I'm thinking about possibility that RCS1163 would not be reported if the parameter name is '_' (see #245).
