### ISSUE TITLE
Static class variable false positive for RCS1213

### ISSUE THREAD

**Issue by mikewodarczyk** [JosefPihrt/Roslynator#249]
This may be similar to another bug with false positives with RCS1213, but I didn't see this scenario in the list of issues.     

public static class foo
    {
        private static string _bar;  **// RCS1213 says that _bar is unused when it is used in Bar below.**
        public static string Bar
        {
            get
            {
                if ( _bar == null )
                {
                    _bar = "BAR";
                }
                return _bar;
            }
        }
    }

**Comment by JosefPihrt** [comment]
Please install latest version that contains fix for this issue.
