### ISSUE TITLE
void methods and  "Use expression-bodied member or Expand to expression-bodied member"

### ISSUE THREAD

**Issue by MoamenMohamed** [JosefPihrt/Roslynator#25]
**Environment**

- Visual Studio version: 2015 Enterprise update 3
- Roslynator version: 1.1.7

**Description**
Both refactoring methods doesn't work well with void methods

**1. Use expression-bodied member**

**Steps to recreate**

Write a void method expanded like so:
```
private void AddName(string name)
{ 
        Names.Add(name);
}
```
**Current behavior**

The refactoring option doesn't show.

---
**2. Expand to expression-bodied member**

**Steps to recreate**

Write a void method as expression-bodied like so:
```
private void AddName(string name) => Names.Add(name);
```
**Current behavior**

the refactoring appear but it does it wrongly by adding a return keyword.
```
private void AddName(string name)
{ 
       return Names.Add(name);
}
```

**Comment by JosefPihrt** [comment]
Thanks for the report @MoamenMohamed !
