### ISSUE TITLE
RCS1083: Call 'Enumerable.Any' instead of 'Enumerable.Count' should kick in only if count() is compared with 0

### ISSUE THREAD

**Issue by vijaygill** [JosefPihrt/Roslynator#252]
The warning "RCS1083: Call 'Enumerable.Any' instead of 'Enumerable.Count'" should not be shown in case of things like ".Where(g => g.Count() > 1)" but only when the count is compared with 0.

**Comment by JosefPihrt** [comment]
Could you explain why do you think so?

**Comment by JosefPihrt** [comment]
@BobbyCannon is this some riddle? ;-)

Some explanation and formatting would be nice. Thanks.

**Comment by BobbyCannon** [comment]
Oh sure, sorry about that.

I was trying to say that "g.Count() > 1" is not the same as "g.Any()". This would be the refactoring should not suggest a change.

However you could suggest a change with the following.

- "g.Count() > 0"
- "g.Count() >= 1"

Because both of the above do equal "g.Any()"

**Comment by JosefPihrt** [comment]
Thanks for a clarification.

Analyzer RCS1083 works for all three examples that you presented:

|Before|After|
|---|---|
|`items.Count() > 1`|`items.Skip(1).Any()`|
|`items.Count() > 0`|`items.Any()`|
|`items.Count() >= 1`|`items.Any()`|

**Comment by BobbyCannon** [comment]
Totally, I was just trying to help clarify. Seems like you are on point. Most excellent!

**Comment by vijaygill** [comment]
Hi @BobbyCannon thanks for explaining it. Sorry I could not get near my machine during the weekend and could not see the messages earlier.

My request was about suppressing this warning in scenario where g.Count() > 1 is used, In this case ".Any()" cannot be used.

Thanks
Vijay

**Comment by JosefPihrt** [comment]
@vijaygill Unfortunately, I still don't understand what you are requesting.

Table above shows that `g.Count() > 1` can optimized by using `Any` (in combination with `Skip`).

**Comment by vijaygill** [comment]
Hi @JosefPihrt ,

Sorry I should have mentioned it in my previous post. Your reply to @BobbyCannon is spot-on. This request can be closed / rejected.

Thanks
Vijay

**Comment by JosefPihrt** [comment]
#315
