### ISSUE TITLE
Shortcut mapping to refactoring

### ISSUE THREAD

**Issue by glmnet** [JosefPihrt/Roslynator#254]
Is it possible to map a shortcut to a refactoring?
E.g. In resharper you can call a refactoring by a shortcut, e.g. Ctrl R, V will call introduce variable (Introduce local in Roslynator)
Is there anyway to do similar?

**Comment by JosefPihrt** [comment]
It would be great to invoke refactoring with a shortcut.

I'm not aware that there a API from Microsoft to do it. I encourage you to ask them.
