### ISSUE TITLE
Refactor request: Remove unnecessary modifiers

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#260]
Given the following C# code:
````C#
internal class A {
    private int i;
}
````
Is it possible to provide a refactor to remove unnecessary modifiers so the code will look like this after refactoring?
````C#
class A {
    int i;
}
````

**Comment by JosefPihrt** [comment]
You are asking for the opposite of [RCS1018](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1018.md), right?

**Comment by wmjordan** [comment]
Yep. Quite exactly.
Please provide a code fix for the refactor component.
