### ISSUE TITLE
Additional rules for RCS1047(remove suffix 'Async' from non-async method name) especially in UWP

### ISSUE THREAD

**Issue by lzl1918** [JosefPihrt/Roslynator#261]
In my case, methods with return type `IAsyncAction` cause the hint RCS1047 to be shown.

The following 4 return types can be added to the rule:
`IAsyncAction`
`IAsyncOperation<TResult>`
`IAsyncActionWithProgress<TProgress>`
`IAsyncOperationWithProgress<TResult, TProgress>`

**Comment by JosefPihrt** [comment]
fixed with 2add015c32c53c076d461a4e814113d0e1c7e894
