### ISSUE TITLE
Refactor Request: Split if conditions

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#263]
Given code:
````C#
if (a && b) {
}
````
After splitting the conditions, it becomes:
```C#
if (a) {
   if (b) {
   }
}
````

**Comment by JosefPihrt** [comment]
Select `b` and choose "Extract condition to nested if".

http://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0043.md

**Comment by wmjordan** [comment]
Got it.
It was what I need.
Previously I thought that I could place the caret on the `&&` and get a refactor option.
