### ISSUE TITLE
Request: "replace interpolation with string.Format" inverse of RR0145

### ISSUE THREAD

**Issue by LesRamer** [JosefPihrt/Roslynator#265]
I strongly prefer string interpolation to ```string.Format``` calls so I use RR0145 a lot in the legacy code that I maintain. But I've encountered a need to go the other direction (that is, to do the inverse of what RR0145 does.)

The driving factor for me is legacy logging code that we are shifting from a "flat" interpolated string to structured logging with "named-holes."

### Example Code:
```csharp
// from this....
logger.LogInformation($"Customer {customer.Name}, Address {customer.Address}");

// to this...
logger.LogInformation(string.Format("Customer {0}, Address {1}", customer.Name, customer.Address));

// So that I can drop the string.Format, add names for the format parameters {0} & {1} to wind up with structured logging, "named-holes"
logger.LogInformation("Customer {Name}, Address {Address}", customer.Name, customer.Address);
```

**Comment by wekempf** [comment]
Why not go straight to this?

```csharp
logger.LogInformation("Customer {Name}, Address {Address}", customer.Name, customer.Address);
```

Use the final property (or method) name for the hole and move the expressions to parameters? Going back to string.Format would be useful for some as well, but including structured logging template support makes sense to me.

**Comment by LesRamer** [comment]
Structured logging, as pervasive as it is still renders that a bit of a niche -- I would totally *love it* tho.  I'm staring at thousands of these, so the time savings for me would be significant.

Being able to go from interpolated string to string.Format makes a round-tripping possible: string.Format -> Interpolated string -> string.Format. More abstractly and ideally, (when possible) each refactoring should have a sibling inverse-refactoring that compliments by going the other direction.

**Comment by wekempf** [comment]
With ASP.NET core and Microsoft.Extensions.Logging I'm not sure I'd call it niche. At least, not in that world (in .NET framework code it's maybe still niche), which is probably pretty important to this project.
