### ISSUE TITLE
Bug: UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer throws NullReferenceException (again)

### ISSUE THREAD

**Issue by teoPL** [JosefPihrt/Roslynator#267]
Problem #190 reappeared

Possible cause: [link](https://github.com/JosefPihrt/Roslynator/commit/2318d974918f6a142b7fcb68d446c320fadd78af?diff=unified#diff-824c316ebebb3a3ed4b4a4675d866b46L40)

**Comment by JosefPihrt** [comment]
Could you provide code that causes the exception? Thanks.
