### ISSUE TITLE
Call ConfigureAwait is not working

### ISSUE THREAD

**Issue by nowol** [JosefPihrt/Roslynator#27]
Hello,

I was trying your code analyzer (latest version on Nuget) and I think I found a small issue:  I tested a small async method with its `ConfigureAwait` method missing and I did not get the expected diagnostic (RCS1090).

My small method:
```
        public async Task BlehAsync()
        {
            await Task.Delay(23);
        }
```

I was expecting the analyzer to propose adding `.ConfigureAwait(false)` to the code since it is missing.  I know the analyzers are active because they found an issue in my code.

Let me know if you need more information.

**Comment by JosefPihrt** [comment]
Hi, I've checked this piece of code using newest version of Roslynator (Visual Studio extension) and it's working. So this bug had been fixed but new version of nuget package hasn't been released yet.
