### ISSUE TITLE
Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

### ISSUE THREAD

**Issue by siewers** [JosefPihrt/Roslynator#271]
I don't know what causes this, as there is nothing else than this in the output window:

`1>CSC : warning AD0001: Analyzer 'Roslynator.CSharp.DiagnosticAnalyzers.UseMethodGroupInsteadOfAnonymousFunctionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
`

I saw that a couple of other bugs in the same analyzer was already fixed, but this error occurs in version 1.7.0 but not in 1.7.0-rc.

Is there a way to get more details about the exception?

**Comment by JosefPihrt** [comment]
duplicate of #267

**Comment by siewers** [comment]
But that issue was closed. Where is this issue fixed? Is it released yet?

**Comment by JosefPihrt** [comment]
The fix has not been released yet.
