### ISSUE TITLE
Convert inline comment to XML doc comment

### ISSUE THREAD

**Issue by franklin-ross** [JosefPihrt/Roslynator#272]
Similar to #76 but for the case of a plain old comment trailing a member.

Before:
`public bool GetThing => thing; // Gets the thing`

After:
```
/// <summary>
/// Gets the thing
/// </summary>
public bool GetThing => thing;
```

Occasionally I come across a file where somebody has done this and it just makes me cry. Being able to quickly fix it to at least get those comments into intellisense would be super valuable.

**Comment by wmjordan** [comment]
I met with such kind of code before.
I just gave up converting them to XML doc.

**Comment by franklin-ross** [comment]
@wmjordan, well yeah, me too. That's why I think this would be a valuable fix :-D

**Comment by franklin-ross** [comment]
I don't know how many times I've hit that "Close and comment" button without thinking.

**Comment by JosefPihrt** [comment]
Seems like a good idea.
