### ISSUE TITLE
Question: Uncomment codefix behaviour

### ISSUE THREAD

**Issue by teoPL** [JosefPihrt/Roslynator#277]
Trying to uncomment `Block1` also uncomment `Block2`, it is intended?

```
namespace test
{
    class TestClass
    {
        void Method()
        {
            // Block1 - 1
            // Block1 - 2
            // Block1 - 3

            // Block2 - 1
        }
    }
}
```

**Comment by JosefPihrt** [comment]
I would say yes.

It could stop on first empty line but I then it would not be possible to uncomment larger commented block that usually contain empty line.

**Comment by teoPL** [comment]
It would be pretty handy but i understand the pros and cons. 

I wanted to be sure it was intedend. Thanks.
