### ISSUE TITLE
RCS1214 on multiple strings

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#279]
Hello Josef
Could you explain the rational behind the RCS1214 warning on such interpolated strings:
`$"{e.Exception.Message}{Environment.NewLine}{e.Exception.StackTrace}"`
Why replace it with
`e.Exception.Message + Environment.NewLine + e.Exception.StackTrace`
?

If I'm correct, interpolated strings use string.Format behind the scenes.
I would expect this is more efficient that concatenating through operator+ as it can directly allocate the final string length and no intermediate string objects

**Comment by JosefPihrt** [comment]
There are two approaches: readability and performance.

### Readability
If you only want to concatenate several strings it is better (more readable) to use `String.Concat`. In other words: using string interpolation only to concatenate strings is bad practice.

### Performance
I fould [this benchmark](https://koukia.ca/string-interpolation-vs-string-format-string-concat-and-string-builder-performance-benchmarks-c1dad38032a) which shows that `String.Concat` is ~3 times faster than string interpolation.

I you look at the source code for [string.Concat](http://source.dot.net/#System.Private.CoreLib/src/System/String.Manipulation.cs,17e1cc2f91f20974
) you will see that it is very simple and final length is calculated. It includes allocation of a new string.

`String.Format` ends up with [StringBuilder.AppendFormatHelper](http://source.dot.net/#System.Private.CoreLib/shared/System/Text/StringBuilder.cs,2c3b4c2e7c43f5a4) which is much more complicated. It may or may not include allocation of a `StringBuilder`. It also may include allocation of underlying array if the strings are long.

**Comment by wiz0u** [comment]
Thanks for your answer.
However I'm pretty sure the C# compiler will be more clever in the future and generate string.Concat calls in case of simple interpolated strings like this, or even on multiple '+' operations on strings.

In fact, it seems to be already underway: https://github.com/dotnet/roslyn/pull/22595

So I stand by my idea that we shouldn't lower the readability of code by discouraging the use of interpolated string simply composed of multiple strings.

If you disagree, another solution could be to split RCS1214 in 2 messages:
- Keep RCS1214 for interpolated strings containing only one string
- Add a RCSxxxx for interpolated strings containing several strings (I would personally disable this one)

**Comment by JosefPihrt** [comment]
I insist that string concatenation should not be disguised as string interpolation.

But truth is that it could be a matter of personal preference so your proposal to split the analyzer into two ones seems to be reasonable.
* **RCS1214** - UnnecessaryStringInterpolation (Severity: Info).
  ```
  $"{x}"
  ```
* **RCS1217** - ReplaceStringInterpolationWithConcatenation (Severity: Hidden).
  ```
  $"{x}{y}"
  ```

**Comment by wiz0u** [comment]
Thanks :)
