### ISSUE TITLE
[Question] - Visual Studio for Mac support

### ISSUE THREAD

**Issue by jzeferino** [JosefPihrt/Roslynator#283]
Any plans to support this analysers in VS for Mac?

**Comment by jzeferino** [comment]
@matthewrdev can you clear this up a bit?

**Comment by matthewrdev** [comment]
Yep, VS Mac supports Rosyn Refactorings.

**Comment by JosefPihrt** [comment]
Could you describe or provide some link how to make 3rd party analyzers working in VS for Mac?

**Comment by jzeferino** [comment]
@JosefPihrt take a look at https://github.com/dotnet/roslyn-analyzers/issues/1453 and the source code.

@matthewrdev any helpful link ou source that you can share?

**Comment by JosefPihrt** [comment]
There is nuget package [Roslynator.Analyzers](https://www.nuget.org/packages/Roslynator.Analyzers/).

Will that do?

**Comment by matthewrdev** [comment]
To my knowledge and experience, the analysers in the NuGet package should just load when it's included in a project.

**Comment by jzeferino** [comment]
I added Roslyn-analyzers as my project dependency and it seems to not work.

**Comment by JosefPihrt** [comment]
If roslyn-analyzers are not working please file an issue in their repo.

They are discussing in the issue that is referenced above that version 2.6.0-beta1 will not work on mac but version 2.3.0-beta1 works.

Did not try to install Roslynatorl.Analyzers?

**Comment by jzeferino** [comment]
I've already installed Roslynator Analyzers in VS for Mac and it didn't work.

**Comment by matthewrdev** [comment]
@jzeferino In the case that the analyser nuget isn't loading, that's probalby a VS Mac nuget. You should reach out to the VS Mac product team.

**Comment by jzeferino** [comment]
@JosefPihrt close this if you want.

**Comment by JosefPihrt** [comment]
@jzeferino Did you succeed to load roslyn analyzers in VS for Mac?

**Comment by chucker** [comment]
FWIW, I succeeded to install `Roslynator.Analyzers` via NuGet, and after a moment, my test project yielded:

>Warning RCS1102: Make class static.

Note that VSMac does not support VSIX (due to its MonoDevelop heritage, it expects [`mpack`](https://www.monodevelop.com/developers/articles/creating-a-simple-add-in/) instead). So for now, only the NuGet variant will work.

**Comment by bchavez** [comment]
For those coming from Google, you can get analyzers to work in Visual Studio for Mac 2017 by adding the following to your `.csproj`:

```xml
<ItemGroup>
  <Analyzer Include="/Users/ACCOUNT/.nuget/packages/analyzer.nuget.package/0.0.0/analyzers/dotnet/cs/Some.Analyzer.dll" />
</ItemGroup>
```
* Where `/Users/ACCOUNT` is replaced with your local Mac account name.
* Where `analyzer.nuget.package` is your NuGet analyzer.
* Where `0.0.0` is your NuGet analyzer package version.
* Where `Some.Analyzer.dll` is the analyzer DLL you're interested in running.

Restart Visual Studio for Mac and it should work. This is what worked for me.

Tested in VS for Mac 2017 / v7.8 (build 1624).
