### ISSUE TITLE
RCS1186 & constant pattern: shouldn't the Regex be declared as static ?

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#288]
Currently the fix generates a `private readonly Regex`
Wouldn't it be better to make it a` private static readonly Regex` ?
At least if the pattern is a constant string.

By the way, you don't seem to check much about the pattern expression:
If it references a local variable or a non-static member, the refactoring generates a non-working Regex initializer.
It is probably safer to restrict RCS1186 to occurrences using a constant string pattern.

**Comment by JosefPihrt** [comment]
Fixed with ed8198d6f362643f1b7c32d6da2dad60357c06ac
