### ISSUE TITLE
RCS1103  C# Consider replacing if statement with assignment. Goes wrong

### ISSUE THREAD

**Issue by mkany** [JosefPihrt/Roslynator#29]
RCS1103 markes this code. 

if (Regex.IsMatch(dir.FullPath, @"\\[0-9]{2}_"))
                        {
                            if (!dir.FullPath.Contains(@"\00_wwle") &&
                                !dir.FullPath.Contains(@"\02_sb") &&
                                !dir.FullPath.Contains(@"\02_lb") &&
                                !dir.FullPath.Contains(@"\05_ab")
                                )
                            {
                                result = false;
                            }
                            else
                            {
                                result = true;
                            }
                        }
                        else
                        {
                            result = true;
                        }

after code changed, code looks like this.

if (Regex.IsMatch(dir.FullPath, @"\\[0-9]{2}_"))
                        {
                            result = !!dir.FullPath.Contains(@"\00_wwle") &&
                                !dir.FullPath.Contains(@"\02_sb") &&
                                !dir.FullPath.Contains(@"\02_lb") &&
                                !dir.FullPath.Contains(@"\05_ab");
                        }
                        else
                        {
                            result = true;
                        }

but the code must be like this.

if (Regex.IsMatch(dir.FullPath, @"\\[0-9]{2}_"))
                        {
                            result = !(!dir.FullPath.Contains(@"\00_wwle") &&
                                !dir.FullPath.Contains(@"\02_sb") &&
                                !dir.FullPath.Contains(@"\02_lb") &&
                                !dir.FullPath.Contains(@"\05_ab"));
                        }
                        else
                        {
                            result = true;
                        }

**Comment by JosefPihrt** [comment]
Thanks for the report @mkany !
