### ISSUE TITLE
RCS1169: missing space after readonly

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#293]
RCS1169 refactoring of
`private static int Test = 3;`
becomes
`private static readonlyint Test = 3;`

It happens 60% of the time, with various types, modifiers... can't point out what makes it insert space correctly or not.

**Comment by JosefPihrt** [comment]
Please try to provide a code sample that will reproduce the bug, otherwise it is hard to fix it.

**Comment by wiz0u** [comment]
this one does `private static int test = 3;`

(tested under VS2015)

**Comment by JosefPihrt** [comment]
I'm unable to reproduce it in VS2017.

But I tried to improve the code fix, we'll see in the next release if it works :)
