### ISSUE TITLE
Suggestion: Create constructor with call to base class constructor

### ISSUE THREAD

**Issue by Zyxious** [JosefPihrt/Roslynator#294]
I work with nopCommerce and sometimes I need to override a method or two on the original factories/services to get custom behavior.

The way I do this is by inheriting a class and replace the default implementation of a method with my own and then injecting my implementation of the class with higher priority.

When inheriting a class without a parameterless constructor I also need to call a base class constructor otherwise I get a CS7036 error.

I would like Roslynator to give me a suggestion to automatically create such constructor.

For example I get the error on ProductModelFactory when I write like this:

    public class ProductModelFactory : Nop.Web.Factories.ProductModelFactory
    {
    }

I purpose that, if I place the cursor on the class name I would like to get a suggestion like "Create constructor with call to base class constructor"

The resulting code should look like this:

    public class ProductModelFactory : Nop.Web.Factories.ProductModelFactory
    {
        public ProductModelFactory(ISpecificationAttributeService specificationAttributeService,
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            IProductService productService,
            IVendorService vendorService,
            IProductTemplateService productTemplateService,
            IProductAttributeService productAttributeService,
            IWorkContext workContext,
            IStoreContext storeContext,
            ITaxService taxService,
            ICurrencyService currencyService,
            IPictureService pictureService,
            ILocalizationService localizationService,
            IMeasureService measureService,
            IPriceCalculationService priceCalculationService,
            IPriceFormatter priceFormatter,
            IWebHelper webHelper,
            IDateTimeHelper dateTimeHelper,
            IProductTagService productTagService,
            IAclService aclService,
            IStoreMappingService storeMappingService,
            IPermissionService permissionService,
            IDownloadService downloadService,
            IProductAttributeParser productAttributeParser,
            IDateRangeService dateRangeService,
            MediaSettings mediaSettings,
            CatalogSettings catalogSettings,
            VendorSettings vendorSettings,
            CustomerSettings customerSettings,
            CaptchaSettings captchaSettings,
            OrderSettings orderSettings,
            SeoSettings seoSettings,
            IStaticCacheManager cacheManager) : base(specificationAttributeService, categoryService, manufacturerService, productService, vendorService, productTemplateService, productAttributeService, workContext, storeContext, taxService, currencyService, pictureService, localizationService, measureService, priceCalculationService, priceFormatter, webHelper, dateTimeHelper, productTagService, aclService, storeMappingService, permissionService, downloadService, productAttributeParser, dateRangeService, mediaSettings, catalogSettings, vendorSettings, customerSettings, captchaSettings, orderSettings, seoSettings, cacheManager)
        {

        }
    }

PS. The example is taken from nopCommerce 4.0

**Comment by JosefPihrt** [comment]
This refactoring already exists:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0054.md.

A list of refactorings can be searched here: http://pihrt.net/Roslynator/Refactorings?Query=constructor

**Comment by Zyxious** [comment]
Oh, sorry my bad.
