### ISSUE TITLE
Edit rulesets

### ISSUE THREAD

**Issue by Thorocaine** [JosefPihrt/Roslynator#295]
Hi

I am trying to edit the default RCS ruleset, according to the [instructions ](https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md).

When I open the current ruleset I do not see any Roslynator rules in the list.
I tried adding a ruleset, but I don't see the ruleset in the available sets to add.

Is there a way I can add the RCS rules, and edit them to what I want active in my projects?

**Comment by JosefPihrt** [comment]
Hi,

I would like to help you but I'm confused by your post.

What do you mean by "default RCS ruleset" and "current ruleset" and how do they look like?

Is your ruleset correctly referenced in your csproj file?

Do you use old csproj or a new version (.NET Core)?

It seems that you are trying to add rules to ruleset file manually which is neither necessary nor recommended. I always use [ruleset editor](https://github.com/JosefPihrt/Roslynator/raw/master/images/RuleSetEditor.png) to change rules.

**Comment by Thorocaine** [comment]
Hi
I am using the rule set editor.
I don't see any of the RSC rules in the editor (what I am asking, is how do
I get them there).

I have Roslynator installed, and it is giving me squiggles and light bulbs,
but I want to change the severity of some of the RSC rules.

I don't see any of the RSC rules in the rule editor, so I cannot change
them to ERROR or NONE.

I have tried old and new styles of csproj files.

**Comment by JosefPihrt** [comment]
What is the exact name of the extension that you have installed?

I'm asking because you could have "Roslynator Refactorings" which does not contain any analyzers.

**Comment by Thorocaine** [comment]
Roslynator 2017

**Comment by JosefPihrt** [comment]
This is very unusual and maybe this is the issue that is not related to Roslynator but to Visual Studio itself.

Do you have any other analyzer extensions installed and do you see them in the ruleset editor?

For example, could you install this  [extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-363830.U2UConsultPerformanceCodeAnalyzersforC7) and check if you will see it in the list.

**Comment by JosefPihrt** [comment]
@Thorocaine any update?

**Comment by Thorocaine** [comment]
Hi
I tried installing U2U now, created a project, checked the analyzers.
U2U was there. I don't know what has changed, but Roslynator is there as
well.

Thank you
