### ISSUE TITLE
Question: Is "Merge if with parent if" RR0196 supposed to preserve behavior

### ISSUE THREAD

**Issue by LesRamer** [JosefPihrt/Roslynator#300]
The [Merge if with parent if : RR0196](https://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0196.md) refactoring has an example code snippet, that I will alter here to frame my question:
## Before (RR0196)
```csharp
if (x == null) // note that I changed 'x' to 'x == null"
{
    if (y)
    {
    }
}
else
{
    // Also new -- but note it's safe to access x.Name since x cannot possibly be null in this else
    Console.WriteLine(x.Name);
}
```
## After (RR0196)
```csharp
if (x == null && y) // again, note 'x' changed to 'x == null'
{
}
else
{
    // Potentially Unsafe: x could be null -- we will get here when x is null and y is false, resulting in a NullReferenceException
    Console.WriteLine(x.Name);
}
```
I wanted to illustrate how this refactoring isn't necessarily behavior preserving when the parent has an 'else' with code that was null-safe before the refactoring and that potentially throws a NullReferenceException after the refactoring.

So, my question is whether this is by-design since there are other useful tools Roslynator provides that are not necessarily behavior preserving. I had a peer that used Roslynator and expected that all of its refactorings were behavior preserving & therefore safe.  I pointed out that "negating a Boolean expression" is immensely useful yet not behavior preserving.

Of course, there is the situation where no "else" exists on the parent and child conditionals, and in this case RR0196 preserves behavior.

As I see it, this can go one of two ways:
1. Your intent is to be behavior preserving -- in which case, the existence of an else should prevent this refactoring. -OR-
1. Your intent is to provide a useful automated code transformation that isn't necessarily behavior preserving -- in which case, it would be nice to find a way of warning the user of this caveat when there's an "else" and also consider updating the docs for RR0196.

**Comment by wiz0u** [comment]
Good question.
As a user, I have the feeling that most refactorings suggested by Roslynator are behavior-preserving, and consider it safe to apply them without too much second thoughts.
If this one is not behavior-preserving, a warning to the user is indeed welcome.

**Comment by wiz0u** [comment]
(could be just by adding a little asterisk * at the end of the refactoring name in the context menu)

**Comment by wiz0u** [comment]
Actually, looking further into it, RCS* analyzers fixes and CS* code fixes both seem behavior-preserving.
But the RR* refactorings are much less following the idea to be behavior-preserving.

So whatever Josef answers to your question is fine by me.

The only thing that bothers me, is that the context menu preview doesn't name or reference the RRxxxx ID (as is done with RCS and CS), so we don't know that the quick action was suggested by a Roslynator refactoring (and therefore, we can't tell if it is considered behavior-preserving or not)

**Comment by JosefPihrt** [comment]
Are refactorings semantics (behavior) preserving?

Sometimes they are and sometimes they are not. Generally, it is completely wrong idea to consider all refactorings to be semantics preserving. Refactorings can be considered as automated code transformation. Please note that this is not something that is special to Roslynator because built-in refactorings are not necessarily semantics-preserving as well.

Code fixes for CS diagnostics try to fix erroneous code (in most cases) so question if they are semantics preserving is irrelevant.

Code fixes for RCS diagnostics should be semantics-preserving. If they are not it is probably a bug.

RR.... identifier is an internal feature of Roslynator so it cannot be displayed in the quick actions menu.

**Comment by JosefPihrt** [comment]
You categorization is correct.

Truth is that there are built-in refactorings that fall into third category such as "Inline temporary variable".

Following sample is silly but shows that semantics will not be preserved.
```csharp
string s = ""; // Inline temporary variable
s = null;
if (s == null)
{
}
```

```csharp
string s = "";
s = null;
if ("" == null)
{
}
```

It is interesting idea to indicate in UI that semantics will not be preserved. But I think that that would require to introduce a convention that would be followed by other producers of roslyn tools (including Microsoft).

To introduce this convention just for Roslynator refactorings would be confusing for users.
