### ISSUE TITLE
RCS1093 file with no code...

### ISSUE THREAD

**Issue by usmrtester** [JosefPihrt/Roslynator#302]
I believe this to be a bug.  Please see the tool tip.   Project is looking in my profile (temp folder) for this file.

![rcs1093 message](https://user-images.githubusercontent.com/32103332/37164441-e2816952-22bf-11e8-9b6e-c128990a9d94.png)

**Comment by JosefPihrt** [comment]
It seems that this file should be excluded from the analysis since it is a generated file.

If this file is not marked as generated, it should be discussed with those who are responsible for generation of this file.

Could you tell me which type of the project is it?

**Comment by JosefPihrt** [comment]
@usmrtester and could you copy here the content of the file? It may be empty but it may contain some comments. Thanks.
