### ISSUE TITLE
RCS1174 displays 'Remove redundant async/await' for awaitable non-Task classes

### ISSUE THREAD

**Issue by MorleyDev** [JosefPihrt/Roslynator#304]
When using code that implements the GetAwaiter functionality, but is not actually a Task, the "remove redundant await" suggestion still appears. Removing the await and async obviously results in a compilation error, since the object is not actually a Task.

The situation I run into this the most is when combining IObservable with AspNetCore, since this allows you to await an observable like a Task in your controller.

Example:
![image](https://user-images.githubusercontent.com/1002358/37399460-a5f59d96-2779-11e8-9f40-7d615c078d54.png)
![image](https://user-images.githubusercontent.com/1002358/37399477-b050eac0-2779-11e8-9820-5fb69e7c46fc.png)

**Comment by JosefPihrt** [comment]
minimal repro:
```csharp
public class Foo
{
    public static async Task<bool> GetAsync()
    {
        return await Observable.Range(0, 1).Any(_ => false);
    }
}
```
