### ISSUE TITLE
RCS1213: annoying Quick Action menu item placement when renaming

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#305]
After renaming a method (by changing its name in its implementation), I usually type Ctrl-. (Quick Actions and Refactorings) and validate with Enter to apply the renaming throughout my code.

However, with RCS1213 enabled, the first entry in the Quick Actions menu becomes the "Remove method X" from RCS1213 because it detects the method is not used (with the new name).
So a quick validation with Enter triggers the wrong actions.

I'm thinking about 2 different ways to fix this:
* If you can control the placement of the action in the context menu, maybe you could move it further down so the first action remains "Rename X to Y"
* Eventually, there might be a way to let the user choose to keep RCS1213 enabled (for the Error List to display the issue) but disable its associated action in the Quick Actions menu (that feature request might apply to other RCS* too)

**Comment by JosefPihrt** [comment]
When I tried to test this issue "rename" item always showed above "remove" item. I don't know what causes the different ordering on your system.

To your points:
1) Currently it is not supported by Roslyn library to manage order of items in the menu.
2) Currently it is not supported by Roslyn library to disable a code fix for a certain diagnostic (although it could be useful in this case). 

Your options are:
1) Click down arrow before you click enter.
2) Use F2 to rename an identifier.
3) Disable RCS1213.

**Comment by wiz0u** [comment]
Ok.

I'm under VS2015. Renaming through F2 crashes often (https://github.com/dotnet/roslyn/issues/7364)
![image](https://user-images.githubusercontent.com/11647984/37586369-65da5102-2b5c-11e8-8818-81db9de4914e.png)

Hopefully we will migrate to VS2017 soon.

**Comment by JosefPihrt** [comment]
If you are under 2017 my recommendation is to use F2 to rename identifiers.
