### ISSUE TITLE
Cannot disabling RCS1036 Remove redundant empty line

### ISSUE THREAD

**Issue by boodoolak** [JosefPihrt/Roslynator#306]
I disable this refactoring in settings, but it still fires.
And enabled after restart VS.
VS2017 15.6.2

**Comment by JosefPihrt** [comment]
Could you show me where did you disable RCS1036?

RCS1036 is an analyzer which means that it cannot be disabled in settings.

Use have to use ruleset: https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md

**Comment by boodoolak** [comment]
Oh, sorry, I disabled RR0101, but I thought it should turn off empty lines refactoring.
![default](https://user-images.githubusercontent.com/3179176/37426040-6cbead3a-27d6-11e8-9292-af5d56327547.png)
![default](https://user-images.githubusercontent.com/3179176/37426050-75c548a8-27d6-11e8-945b-c6c1e4c302cd.png)
