### ISSUE TITLE
Option 'Prefix field identifier with underscore' not taken into account 

### ISSUE THREAD

**Issue by pierrejleroy** [JosefPihrt/Roslynator#31]
Hello, 

I've got a problem with this option :

On visualstudio startup it's set to 'false'. But when generating a variable, the underscore is there. 
I then need to set the option to true, then back to false to have it correctly taken into account.
This need to be done after each start up (same issue on vs 2015 & vs 2017).

I suppose there is a little issue when loading this option.

Could you have a look ?

Pierre

**Comment by JosefPihrt** [comment]
Which product are you using? Roslynator or Roslynator Refactorings?

**Comment by JosefPihrt** [comment]
Thanks for the report @pierrejleroy !

**Comment by pierrejleroy** [comment]
@JosefPihrt with pleasure. And thank you for your tool. It is really a good one.
