### ISSUE TITLE
Request: Use pattern matching

### ISSUE THREAD

**Issue by JosefPihrt** [JosefPihrt/Roslynator#312]
from:
```csharp
x is T && M((T)x)
```
to:
```csharp
(x is T y) && M(y)
```

from:
```csharp
var x = y as T;
if (x == null)
  return;
```
to:
```csharp
if (!(y is T x))
  return;
```

**Comment by IanKemp** [comment]
Shouldn't your second "to" be `if (!(y is T x))`? Either way, the `x` variable is not needed.

**Comment by JosefPihrt** [comment]
You are right that is should be vice versa, I've fix it.

Variable is needed because it is presumably used in the subsequent statements (in case of successful conversion).

**Comment by IanKemp** [comment]
@JosefPihrt There's another case that is missing IMO:

from

```csharp
if (x is T)
{
    DoSomethingWith((T)x);
}
```

to

```csharp
if (x is T y)
{
    DoSomethingWith(y);
}
```

I would imagine this would fall under RCS1172 - please let me know if I should open a separate feature request for this.
