### ISSUE TITLE
RCS1083 suggests call Enumerable.Any instead of Enumerable.Count even when you are checking for a enumerable with more than 1 item

### ISSUE THREAD

**Issue by kiasyn** [JosefPihrt/Roslynator#315]
Example code:
`bool moreThanOne = set.Count() > 1;`

`set.Count() > 1` is not equivalent to `set.Any()`

**Comment by JosefPihrt** [comment]
But the code fix will replace `set.Count() > 1` with `set.Skip(1).Any()`, which is equivalent.

**Comment by kiasyn** [comment]
@JosefPihrt you are correct, somehow I completely skipped over that!

**Comment by Vivelin** [comment]
I have to disagree. While the result might be identical, it becomes more difficult to understand the intent behind a statement at a glance.

With `Count() > 0`, you want to check if the collection is not empty, so `Any()` makes sense. For any other value however, you wouldn't say “I want to check whether the collection contains any items if I skip the first _n_”. You simply describe it as checking the number of items.

The fact that there are multiple duplicate GitHub issues for this should be evidence enough that this behavior from Roslynator is confusing.

**Comment by JosefPihrt** [comment]
Let's say you are right @Vivelin.

There are two options how this issue could be solved:

* Remove functionality that includes 'Skip' call.
* Move this functionality to a new analyzer.

**Comment by Vivelin** [comment]
Personally, I would simply remove it. However I imagine there are users that are more interested in the performance benefit than in the readability aspect so I think moving that part of the functionality to a separate analyzer would be the best option.

However, while you can individually turn of code fixes and refactorings in Options, there does not seem to be a global way to disable specific analyzers (without suppressing it in the code itself), so I'm not sure that would help much.

**Comment by Vivelin** [comment]
What about an option where you can choose to optimize for readability or optimize for performance?

**Comment by JosefPihrt** [comment]
I move the functionality with "Skip+Any" to a new analyzer that is disabled by default.

**Comment by BenjaminBrienen** [comment]
IMO .skip(n).Any() is perfectly readable.
