### ISSUE TITLE
Request for Analyzer & Code-Fix: eliminate "continue"

### ISSUE THREAD

**Issue by LesRamer** [JosefPihrt/Roslynator#317]
Code that is "continue-happy" can benefit from what I currently do via a multi-step refactoring using Roslynator to eliminate continues. I'm proposing writing an analyzer and automated code-fixe to remove continues in code like the following:
```csharp
foreach(var x in xs)
{
   // ...doesn't really matter whether there is code here before condition
   if (earlyOutConditionExpression)
   {
      continue;
   }
  // code after condition
}
```
When I encounter code like this, I like to do the following 3 steps:

1. Wrap the "code after condition" part in an else block. (In visual-studio, I select the code, hit ctrl-k + s, and type "else" -- this surrounds the selected code in an else-block.)
2. Swap conditional expression (this involves selecting the conditional first)
3. Remove the else-continue block

I'll show what this looks like after each step.
### First, wrap the remainder of the code in an else block:
```csharp
foreach(var x in xs)
{
   // ...doesn't really matter whether there is code here before condition
   if (earlyOutConditionExpression)
   {
      continue;
   }
   else
   {
        // code after condition
   }
}
```
### Second, swap conditional:
```csharp
foreach(var x in xs)
{
   // ...doesn't really matter whether there is code here before condition
   if (!earlyOutConditionExpression)
   {
        // code after condition
   }
   else
   {
      continue;
   }
}
```
### Lastly
Now the only thing in the conditional's else-block is a continue. Since the continue is not really continuing past anything, and the block it's in can be eliminated:
```csharp
foreach(var x in xs)
{
   // ...doesn't really matter whether there is code here before condition
   if (!earlyOutConditionExpression)
   {
        // code after condition
   }
}
```
In every case where I've applied this, the code has become significantly shorter and simpler. Being able to apply this solution-wide would be awesome. I've resisted eliminating continue statements when they are nested there's no clear way to move them to the end.

The loop doesn't have to be a foreach -- it could be any other loop type as well: for, while, do-while.

Many developers see continue-use as a kind of gray-area -- so continue-use not universally frowned upon. Nonetheless, a detection and code-fix for this would be really useful. The code where I encounter this continue-use pattern is often in large sprawling methods, so it isn't necessarily obvious to a casual code-reading that the continue can be eliminated. I've used this pattern of steps to remove multiple continues from the same loop (one at a time of course) -- when this has happened, code that was previously too hard to reason about became clear.
# BONUS: Use LINQ-Where on foreach with conditional
When there is no code before the conditional and the conditional is the only thing in a foreach loop, I'll often move the condition into a LINQ-Where turning my refactoring of the previous example into something like this:
```csharp
foreach(var x in xs.Where(x => !earlyOutCondition))
{
    // code after condition
}
```

**Comment by LesRamer** [comment]
I should add in the case of multiple continues in the same loop, I almost always eliminate the continues working from the bottom of the loop up. When working them in the opposite direction, I believe the end result was the same (or at least similar) code but I had more intermediate nesting to contend with. Perhaps writing an analyzer and fixer for this wouldn't suffer from the same issues that I do when doing this manually.

(BTW, I have a couple other ways I've used Roslynator to refine code. Do you appreciate suggestions using "issues" like this or is there a better forum for suggestions?)

**Comment by LesRamer** [comment]
The "BONUS" from my original came about from encountering code like:
```csharp
foreach(var foo in bars)
{
    if (!IsFooBar(foo))
    {
        continue;
    }

    // something meaningful
}
```
Eliminating the continue turns this into (note the negation of condition):
```csharp
foreach(var foo in bars)
{
    if (IsFooBar(foo))
    {
        // something meaningful
    }
}
```
When the entire body of the foreach loop is wrapped in the condition, we can move the condition into the foreach...Where and eliminate the code-block:

```csharp
foreach(var foo in bars.Where(foo => IsFooBar(foo)))
{
    // something meaningful
}
```
To me this is a win.

**Comment by wekempf** [comment]
@IanKemp Note that in Les's larger example (full disclosure, Les and I are colleagues, working in the same legacy code base) the amount of indentation in the code didn't change at all. There were 3 levels of indentation in the original code, and 3 levels in the final result. We've applied Les's pattern numerous times and I can't recall a single time in which the result had more nesting. I get you're concern because in the trivial cases, yes, this would add a level of indentation, but in practice, where you'd want to apply this, I've never observed it to be the case. Far more importantly, this pattern often reduces conditional expressions and therefore improves code comprehension significantly. Far more than an additional indentation level would harm it. Continue and break are sugared forms of goto, and I'm sure you've read the famous blog post on that. :)

All that said, there is a time and place for continue/break where it *does* make the code easier to understand. So, I'm not sure this one should be an analyzer that produces diagnostics. I would *love* to have it as a refactoring option, however.

**Comment by LesRamer** [comment]
@JosefPihrt 
> "I would prefer to move your second suggestion "Replace if with Where" to a new issue"

I don't mind if you want to do that. After all, you own this repo. :)
