### ISSUE TITLE
Assign Field From Constructor

### ISSUE THREAD

**Issue by ardalis** [JosefPihrt/Roslynator#32]
There's a refactoring to go from a constructor parameter to a private readonly field, but not to go in the other direction.

Example:
```
        private readonly IHelloService _helloService;
```

doing ctrl+. on _helloService should prompt to populate from constructor:

```
        public HomeController(IHelloService helloService)
        {
            _helloService = helloService;
        }
```

**Comment by JosefPihrt** [comment]
There is built-in refactoring for this, but you have to select entire declaration (line). Then you should see "Generate constructor 'HomeController(IHelloService)'" in context menu.

I created similar refactoring, but it is disabled by default since there is built-in refactoring.

**Comment by ardalis** [comment]
Ah, thanks. I see it now when I select the whole line. Not as discoverable as clicking on the field name, but at least it's there. Cheers.

**Comment by MovGP0** [comment]
This issue is actually not solved. When I have something like: 
```csharp
    public sealed class MyClass
    {
        private IDependency1 Dependency1 { get; }
        private IDependency2 Dependency2 { get; }

        public MyClass(IDependency1 dependency1)
        {
            Dependency1 = dependency1;
        }
    }
```
And I select the line with `Dependency2` and select this refactoring option, it generates: 
```csharp
    public sealed class MyClass
    {
        private IDependency1 Dependency1 { get; }
        private IDependency2 Dependency2 { get; }

        public MyClass(IDependency1 dependency1)
        {
            Dependency1 = dependency1;
        }

        public MyClass(IDependency2 dependency2 )
        {
            Dependency2 = dependency2 ;
        }
    }
```
But what I need is: 
```csharp
    public sealed class MyClass
    {
        private IDependency1 Dependency1 { get; }
        private IDependency2 Dependency2 { get; }

        public MyClass(IDependency1 dependency1, IDependency2 dependency2)
        {
            Dependency1 = dependency1;
            Dependency2 = dependency2;
        }
    }
```

**Comment by JosefPihrt** [comment]
@MovGP0 There is built-in refactoring that fits your needs:

![addparameterstoconstructor](https://user-images.githubusercontent.com/11931318/37217277-07f49a38-23b5-11e8-8d92-e8390e478346.png)

You have to select both property declarations.

**Comment by MovGP0** [comment]
@JosefPihrt thank you for the tipp :-) 

But I think it's still not the point: It should work by 
- setting the cursor to a single one of the properties, rather than multiple properties, and 
- without the need to select the whole line.

**Comment by JosefPihrt** [comment]
@MovGP0 it works for a field declaration:

```csharp
public sealed class MyClass
{
    private IDependency1 _dependency1;
    private IDependency2 _dependency2; // Initialize field from constructor

    public MyClass(IDependency1 dependency1)
    {
        _dependency1 = dependency1;
    }
}
```
If you want to enable it for a property declaration, please file a new issue, thanks.
