### ISSUE TITLE
RCS1163 And Interface Implementations

### ISSUE THREAD

**Issue by wekempf** [JosefPihrt/Roslynator#321]
This may apply to virtual overrides as well, I don't know, I haven't checked. It also may be something others won't agree with, because this diagnostic *may* help them to redesign interfaces/virtual methods. That said, I think for the most part this diagnostic is mostly an annoyance in this case. Most of the time there's a reason why an interface will have certain parameters, and an equally valid reason why some implementations won't use those parameters. I'd suggest you not issue this diagnostic for overrides or interface implementations at all, or maybe at least split this into two diagnostics to allow the end user to choose to turn them off in these scenarios.

**Comment by JosefPihrt** [comment]
Unused parameter is NOT reported for virtual/override members as well as for members that explicitly implements interface member.

**Comment by wekempf** [comment]
Hmmm... trying that example I get the same results (no diagnostic). I've got another case where I do get a diagnostic, however. Not sure why, and I can't share the code, so if I can't find a simple reproduction I guess you can consider this closed. :(
