### ISSUE TITLE
RCS1213 and DebuggerDisplayAttribute

### ISSUE THREAD

**Issue by wekempf** [JosefPihrt/Roslynator#322]
This one may be hard to deal with, but it's one that's pretty prevalent in my own code so I thought I'd bring it up at least for discussion. We like to use DebuggerDisplayAttribute liberally on our types, and we generally follow [JaredPar's "best practices"](https://blogs.msdn.microsoft.com/jaredpar/2011/03/18/debuggerdisplay-attribute-best-practices/) advice when doing so. From an example on that blog post:

```csharp
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class Student {
    public string FirstName { get; set; }
    public string LastName { get; set; }
    private string DebuggerDisplay {
        get { return string.Format("Student: {0} {1}", FirstName, LastName); }
    }
}
```
Unfortunately, Roslynator doesn't understand the DebuggerDisplayAttribute interaction going on here and flags the DebuggerDisplay property with RCS1213. I'm sure there's other common reflection based use cases like this, but most there's probably nothing you can do about them. In this case, you could interpret the DebuggerDisplayAttribute declaration, though parsing that might be something you consider too complicated just to satisfy one stranger's request here. I get that. But, one less thing I have to suppress when using Roslynator is a big win for me. :)

BTW, I hope the issues we've raised don't discourage you. This is by far the best of the analyzers we've used, and your efforts here are appreciated. If I had any spare time I'd help contribute here in more meaningful ways than just providing bug reports and suggestions.

**Comment by JosefPihrt** [comment]
This seems to be a good idea and it's probably doable.

I'm glad that you like Roslynator and any future bug reports and suggestions are welcome.
