### ISSUE TITLE
Refactor request: Remove "else" (and braces) after if (x) { return; }

### ISSUE THREAD

**Issue by tamlin-mike** [JosefPihrt/Roslynator#324]
```
if (x) { /* smth */ return; }
else { /* blah */ }
```
It would be nice to have a refactoring to remove the (redundant and pointless) `else` keyword, together with its potential braces, if the last statement in the previous branch is a request to leave scope.

While `return` is most obvious, I can also imagine `throw`, `break`, `continue`, and even `goto` (though that could require some hairy code-flow analysis to ensure semantics, why I wouldn't waste time on it).

**Comment by JosefPihrt** [comment]
Done in #182.

See [RCS1211](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1211.md).

This diagnostic is enabled by default but it is hidden which means that you will not see it in Error List but it will show up in the context menu if you place cursor in else keyword and click Ctrl+. (or Alt+Enter).

**Comment by tamlin-mike** [comment]
Oh, it's an _analysis_ thing. Never used those. I have only used the direct refactorings by context menu (RR* I presume), where it's missing.

Since this refactoring is present, though not accessible the way I tried to access it, any chance of exposing this functionality the way I expected it to be available?

**Comment by JosefPihrt** [comment]
So you are extension "Roslynator Refactorings", right?

**Comment by JosefPihrt** [comment]
If you use "Roslynator Refactorings" then you can use refactoring "Extract from containing else clause"

![removeelseandbraces](https://user-images.githubusercontent.com/11931318/38579629-20eb2f7e-3cf7-11e8-9568-ba1ecf517dce.png)

This refactoring simply removes else and braces and does not analyze if the parent if statement contains jump statement as a last statement.
