### ISSUE TITLE
Add DebuggerDisplay attribute

### ISSUE THREAD

**Issue by JosefPihrt** [JosefPihrt/Roslynator#326]

**Comment by LesRamer** [comment]
I follow Jared Parsons' advice in the following link: https://blogs.msdn.microsoft.com/jaredpar/2011/03/18/debuggerdisplay-attribute-best-practices/

The code excerpt from his blog detailing best-practice:
```csharp
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class Student {
    public string FirstName { get; set; }
    public string LastName { get; set; }
    private string DebuggerDisplay {
        get { return string.Format("Student: {0} {1}", FirstName, LastName); }
    }
}
```
Of course in c#6 (well after his post), the private property could be done with an expression-bodied-member; which is how I ordinarily write it.
```csharp
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class Student {
    public string FirstName { get; set; }
    public string LastName { get; set; }
    private string DebuggerDisplay  => string.Format("Student: {0} {1}", FirstName, LastName);
    }
}
```

**Comment by wmjordan** [comment]
Correspondingly, how about having an "Override ToString" as well?

**Comment by JosefPihrt** [comment]
@LesRamer I use this pattern. In fact, I've just added a new refactoring that will generate 'DebuggerDisplay' property for you (2224b31f90d0c6f767ea6131c16ba55d8cab7dc1).
