### ISSUE TITLE
Not all analyzers are added to ruleset file

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#328]
Environment: Windows 10 1709 build 16299.309 x64, Visual Studio 2017 15.6.6, Roslynator 1.8.0 via Nuget

I want to use the Roslynator rules in my project, so I've followed your [super duper handy guide to create a ruleset](https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md). However, when I view my project's rules in Visual Studio, I see this:

![image](https://user-images.githubusercontent.com/1726434/38616626-fedce6d6-3d94-11e8-8baf-db772c11b55b.png)

As you can see, various analyzers are missing and thus cannot be configured; to allow modification of the missing ones in VS, I have to manually edit the generated .ruleset file and insert said absent analyzers. That's not a major thing, but it feels unnecessary.

Is this intentional?

**Comment by JosefPihrt** [comment]
What type of project is it?

Can you confirm that you see only analyzers that are present in ruleset file that this behavior is same for other set of analyzers?

**Comment by IanKemp** [comment]
I'm a dummy.

For some reason the "Show rules that are not enabled" button was not toggled on, so of course I wasn't seeing the disabled rules.

You can close this one as PEBKAC.
