### ISSUE TITLE
Please add a Use Initializer refactoring

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#33]
Refactor from:
````C#
var instance = new Instance();
instance.Name = "a";
instance.Value = "b";
instance.Date = DateTime.Now;
````
To:
````C#
var instance = new Instance {
    Name = "a",
    Value = "b",
    Date = DateTime.Now
};
````

**Comment by JosefPihrt** [comment]
That kind of refactoring already exists, but you have to select the lines you want to refactor.

http://github.com/JosefPihrt/Roslynator/blob/master/source/Refactorings/Refactorings.md#collapse-to-initalizer

**Comment by wmjordan** [comment]
Oh, understood.
Thanks!
