### ISSUE TITLE
Refactor request: Swap binary operands

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#333]
Sometimes we will realize that swapping the sequence of binary boolean operations could gain small performance margin.
````C#
if (dictionary.ContainsKey(a) && command == 1) {
}
````
Since the dictionary lookup can take much more time than the latter constant comparison operation, it is reasonable to swap the operands around the `&&` operator.
````C#
// after refactoring
if (command == 1 && dictionary.ContainsKey(a)) {
}
````

**Comment by JosefPihrt** [comment]
https://github.com/JosefPihrt/Roslynator/blob/master/docs/refactorings/RR0159.md

You have to select the binary expression.

**Comment by wmjordan** [comment]
Oh, I see.
I thought that I could place the caret onto `&&` and it could trigger the refactoring.
