### ISSUE TITLE
RCS1077: Simplify LINQ method chain - Any

### ISSUE THREAD

**Issue by spuljko** [JosefPihrt/Roslynator#335]
RCS1077: Simplify LINQ method chain is not applicable in case
`bool x = items.Where(f => string.IsNullOrEmpty(f)).Count() > 1;`
 Suggestion is:
`bool x = items.Where(f => string.IsNullOrEmpty(f)).Any(); `
Valid case is:
`bool x = items.Where(f => string.IsNullOrEmpty(f)).Count() > 0;`

**Comment by JosefPihrt** [comment]
The suggestion for [RCS1077](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1077.md) is not:
`bool x = items.Where(f => string.IsNullOrEmpty(f)).Any();`
but:
`bool x = items.Count(f => string.IsNullOrEmpty(f)) > 1;`
which is valid.

You are probably referring to [RCS1083](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1083.md) where the suggestion would be:
`bool x = items.Where(f => string.IsNullOrEmpty(f)).Skip(1).Any();`
which is also valid.

But I have received complaints that this fix is confusing so I moved Skip+Any functionality to a new analyzer RCS1219 which is disabled by default (see #315).
