### ISSUE TITLE
Extra whitespace after join interpolation

### ISSUE THREAD

**Issue by LesRamer** [JosefPihrt/Roslynator#336]
This is more of an annoyance than it is a bug; the refactored code still works, it's just not formatted the way I expect.

Occasionally when joining concatenated strings whose expressions span lines (and are indented), the interpolated string will contain extra spaces after the opening curly.

For example, the end result is something like: 
```csharp
$"My {        foo} is bar."
      ^^^^^^^^ The above spaces are what I'm seeing after Roslynator replaces the string.
```
I haven't formulated the exact cause -- whether it's going to interpolated strings from string.Format that spans lines or whether it's going to interpolated strings from several string concatenations (i.e., via +) that span lines.

**Comment by JosefPihrt** [comment]
I have coincidentally fix this in 0dfa45e8e3df31a0e5e116c13eb2d69bd6eec6a2 and it has been released in 1.8.1
