### ISSUE TITLE
RCS1206 should better handle the null case

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#339]
Consider:

```csharp
class Program
{
    static void Main(string[] args)
    {
        Foo y = null;

        // original
        var x = (y == null ? null : y.Bar);
        // after RCS1206; incomplete
        var x = (y?.Bar ?? null);
        // after RCS1206 + RCS1143, or IDE0031
        var x = (y?.Bar);
    }
}

public class Foo
{
    public int? Bar;
}
```

As can be seen, invoking RCS1206 results in a simplified expression, but one that can be further simplified, and indeed RCS1143 then triggers to suggest that optimisation. It would be ideal if RCS1206 could perform both fixes in a single pass.

The Microsoft-provided fix IDE0031 from `Microsoft.CodeAnalysis.CSharp.Features` for .NET Framework (there doesn't seem to be a corresponding one for .NET Core) does do this "full fix", so maybe have look at their implementation: http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.Features/UseNullPropagation/AbstractUseNullPropagationCodeFixProvider.cs

**Comment by JosefPihrt** [comment]
I'm not able to reproduce this bug with the latest version. Which version and product are you using?

**Comment by JosefPihrt** [comment]
I'm able to reproduce it now.
