### ISSUE TITLE
Wrong suggestion for RCS1032

### ISSUE THREAD

**Issue by nvmkpk** [JosefPihrt/Roslynator#34]
This should not be suggested in following case:
$"UAC is {(UacHelper.IsUacEnabled ? "" : "not ")s}enabled"

Applying the suggestion leads to an error because we are using ':' in the string interpolation and compiler treats it as separator for format specifier. We need the parenthesis in this case.

**Comment by JosefPihrt** [comment]
Thanks for the report @nvmkpk !
