### ISSUE TITLE
RCS1032 with object initializer and variable declaration

### ISSUE THREAD

**Issue by MSeifert04** [JosefPihrt/Roslynator#346]
I noticed that "remove redundant parenthesis" highlights code like this:

```
        string a, b;
        var x = new List<string>
        {
            (a = "abc"),
            (b = "def")
        };
```

However these parenthesis are not redundant and the "code fix" will produce invalid and semantically different code:

```
        string a, b;
        var x = new List<string>
        {
            a = "abc",
            b = "def"
        };
```

**Comment by JosefPihrt** [comment]
Thanks for the report @MSeifert04 !

**Comment by MSeifert04** [comment]
Thank you for the very fast fix. :+1:
