### ISSUE TITLE
RCS1163 triggered for unused parameter in lambda

### ISSUE THREAD

**Issue by silvioboehme** [JosefPihrt/Roslynator#349]
Hi!

1163 (unused parameter) is triggered, if i provide a lambda an don't use the parameter.

RuleFor(o => o.IdentityId, f => Guid.NewGuid().ToString());

1163 for parameter f (basically right), but there is no solution for this hint.
Maybe you can prevent a hint/warning in this case.

Thank you for your great work.
Silvio

**Comment by JosefPihrt** [comment]
Hi,

Recommended approach in this case is to rename unused parameter to "_". Then it will not be reported.

Please see the documentation:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1163.md

**Comment by silvioboehme** [comment]
Thank you. I have seen this before, but never recognized this as a common way.

You can close this issue. Thanks
