### ISSUE TITLE
Refactor Request: Inline and remove local

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#353]
Given the following code, `l` is used for only once, it is possible to remove it.
````C#
var l = DateTime.Now - new DateTime(2018, 1, 1);
Console.WriteLine(l);
````
After refactoring:
````C#
Console.WriteLine(DateTime.Now - new DateTime(2018, 1, 1));
````

**Comment by JosefPihrt** [comment]
There already is built-in refactoring "Inline temporary variable".

**Comment by wmjordan** [comment]
Oops, I did not expected that VS had built it in. I found it now. Sorry for this issue.
