### ISSUE TITLE
Line break missing when simplifying nested using statement

### ISSUE THREAD

**Issue by MitchellEnsink** [JosefPihrt/Roslynator#354]
Given the following code:

    using(var foo = new object()) {
        using(var bar = new object()) {
        }
    }

When using the fix for `RCS1005: Simplify nested using statement`, the result I would expect differs from the actual change being made.

Expected result:

    using(var foo = new object())
    using(var bar = new object()) {
    }

Actual result:

    using(var foo = new object()) using(var bar = new object()) {
    }

Having both using statements on the same line harms the readability and forces the programmer to fix it manually, which defeats the point of automating the fix.

I would like to see the fix inserting the line break automatically in order to solve this issue.

(Note that this issue only occurs when the opening brace of the outer `using` statement is on the same line as the statement itself.)

**Comment by JosefPihrt** [comment]
Thanks for the report @MitchellEnsink !

**Comment by MitchellEnsink** [comment]
Thanks for fixing it!
