### ISSUE TITLE
Loading settings from disk

### ISSUE THREAD

**Issue by niemyjski** [JosefPihrt/Roslynator#36]
I tried looking through the code to see how settings were loaded but looks like they only come from inside of vs settings...

I'd like to put a json setting in the root of the project / solution or in a .vs folder and have the settings loaded. This means I can share them with my team and have them applied. Is this possible?

**Comment by JosefPihrt** [comment]
It seems to be doable.

A couple of notes:

* There will be possibility to override Visual Studio options with options specified in a file.
* File name will be **roslynator.config**.
* File will be located in solution directory.

A file will have following structure:

```xml
<?xml version="1.0" encoding="utf-8"?>
<roslynator>
  <settings>
    <general>
      <prefixFieldIdentifierWithUnderscore isEnabled="true" />
    </general>
    <refactorings>
      <refactoring id="RR0001" isEnabled="false" />
    </refactorings>
  </settings>
</roslynator>
```

Refactorings ids with be specified [here](http://github.com/JosefPihrt/Roslynator/tree/master/source/Refactorings/README.md).

**Comment by niemyjski** [comment]
We'll please note that VS2017 is going off of .editorconfig for most formatting so maybe we could imitate that :).

**Comment by NickCraver** [comment]
+1 for a solution `.json`, this would be ideal for me too. I want this especially since suppression doesn't yet support namespaces ([dotnet/roslyn/#486](https://github.com/dotnet/roslyn/issues/486)).

**Comment by JosefPihrt** [comment]
@NickCraver The configuration file would be applicable only to refactorings, not analyzers.

**Comment by jbcutting** [comment]
@JosefPihrt Out of curiosity, why would the config file only be applicable to refactorings? I recently found Roslynator and hugely prefer it over ReSharper. However, I'd like to be able to turn specific analyzers (and refactorings) on or off for the whole team.

**Comment by lancelarsen** [comment]
So when do we expect this global config file?

That or when applying the suppression in File... is there a wildcard format for the Target? ie. whole project ignore.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1169:Mark field as read-only.", Justification = "<Pending>", Scope = "member", Target = "~F:SecondAct.Controllers.BackgroundController._backgroundTypeRepository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1169:Mark field as read-only.", Justification = "<Pending>", Scope = "member", Target = "~F:SecondAct.Controllers.BackgroundController._characterRepository")]

**Comment by JosefPihrt** [comment]
@lancelarsen proposed config file would not (and cannot) be applicable to analyzers (RCS....).

I recommend to use **rule set** to suppress certain analyzer in entire project (see [How to Customize Analyzers](https://github.com/JosefPihrt/Roslynator/edit/master/docs/HowToCustomizeAnalyzers.md)).

**Comment by lancelarsen** [comment]
Would love that -- really dig your extension...  keep up the great work!

**Comment by JosefPihrt** [comment]
[How to Configure Refactorings](http://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureRefactorings.md)
