### ISSUE TITLE
ignore naming violation for native methods

### ISSUE THREAD

**Issue by HassanHashemi** [JosefPihrt/Roslynator#364]
it seems that ignoring "name violation" for native methods might be a good idea.
since names are coming from an entirely different language and naming convention.

take `libuv` methods for example:
![image](https://user-images.githubusercontent.com/6805984/40276441-5491cdfa-5c1f-11e8-8894-503672b876c9.png)

**Comment by JosefPihrt** [comment]
"Name violations" are not provided by Roslynator. I suggest you to file this issue in roslyn repo:
https://github.com/dotnet/roslyn/issues
