### ISSUE TITLE
RCS1183 should remove trailing comma

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#368]
var o = new Class
		{
			Field1 = true,
			Field2 = false,
		};
When RCS1183 is applied we get:

		var o = new Class { Field1 = true, Field2 = false, };

I think that last (optional) comma should be removed.

When writing multiple-lines initializer, some users leave a comma on the last field initializer so that additional fields lines can be added without the need to add a comma to the previous field initializer (and the line considered as modified by source control)

However if the user specifically intend to convert them to a single line initializer through RCS1183, it makes no sense to keep that final comma. It's not pretty and it doesn't serve its initial purpose of avoiding unnecessary source control modifications.

**Comment by IanKemp** [comment]
I feel like this should be another analyzer + code fix, not a modification to the current behaviour of RCS1183.

**Comment by wiz0u** [comment]
So, in order to not alter the current behaviour of RCS1183 **code fix**, you decide to alter the behaviour of RCS1035 **detection**?

I can see reasons why some people might have enabled RCS1035 to have it report tailing comma on multiple-lines initializer so they can remove the comma (cosmetic choice).
So altering its behaviour is not a good option in my opinion (unless you split it in 2 analyzers for single & multiple-lines)

But I can't see reasons why people would want to keep the trailing comma after applying RCS1183 code fix. @IanKemp Could you give argument why RCS1183 should not remove the trailing comma when applying the code fix?
Note also if one is really willing to keep a trailing comma on a single-line initializer, it can always add it back after applying the RCS1183 code fix (just like I remove it currently because RCS1183 doesn't do it for me.. I just feel the majority of people would want that comma automatically removed)

**Comment by JosefPihrt** [comment]
Regardless of whether the modification of RCS1035 is going to be implemented, I think that we can remove trailing comma in code fix for RCS1183.

@wiz0u:
By the way, RCS1183 is applicable for initializers with a single expressions and your code contains initializer with two expressions.

**Comment by wiz0u** [comment]
> RCS1183 is applicable for initializers with a single expressions 
Right, that must be an oversight while transcribing what I observed in my code, to generic code for the purpose of explaining the issue.
