### ISSUE TITLE
Issue configuring ruleset

### ISSUE THREAD

**Issue by eduherminio** [JosefPihrt/Roslynator#382]
Following `HowToConfigureAnalyzers.md`, I'm not being able to configure the ruleset using Visual Studio 2017 (last version, v15.7):
- No `Open active ruleset` option is shown in Analyzers.

**Comment by JosefPihrt** [comment]
You are probably using new csproj format (.NET Core  app or .NET Standard library).

In that case, you have to manually edit csproj file and add following PropertyGroup (or add element to existing PropertyGroup):

```xml
<PropertyGroup>
	...
  <CodeAnalysisRuleSet>relative_or_absolute_path_to_ruleset_file</CodeAnalysisRuleSet>
	...
</PropertyGroup>
```

To be able to edit ruleset you have to open that file in Visual Studio. Recommended pattern is to add folder "Solution Items" to your solution and add ruleset file to that folder (Add > Existing Item).

I will update documentation accordingly.

**Comment by JosefPihrt** [comment]
db124047e7441f739d117f446357ab0c5630723f

**Comment by JosefPihrt** [comment]
Does it help, @eduherminio ?

**Comment by eduherminio** [comment]
Sorry, I didn't have the chance to test it.
Before starting using Roslynator I was already working with an autogenerated ruleset.
How could I get default Roslynator's default one, to customize and add it to my project so that active rules are overwritten?

**Comment by JosefPihrt** [comment]
Please follow updated step-by-step tutorial:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md#new-csproj-format-net-core-net-standard
