### ISSUE TITLE
Request: Refactoring to use null-coalescing operator instead of ternary expression

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#383]
```csharp
Color? color = null;
int? colorArgb = color.HasValue ? (int?)color.Value.ToArgb() : null;
```

Can be written as:

```csharp
Color? color = null;
int? colorArgb = color?.ToArgb();
```

Might be similar/related to #378, I seem to be coming across quite a few scenarios where code referencing nullable structs' `HasValue`/`Value` properties can be greatly simplified.

**Comment by JosefPihrt** [comment]
Probably could be done as an extension of [RCS1206](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1206.md)
