### ISSUE TITLE
Error on Package Load

### ISSUE THREAD

**Issue by MikVar** [JosefPihrt/Roslynator#389]
Hi Josef,
Thanks for all your efforts on this awesome tool.  
I recently started getting errors in VS2017 on project load.  Had to disable Roslynator :( 
Here's the exceptions from the ActivityLog.xml:
 
 <entry>
    <record>2560</record>
    <time>2018/06/19 19:12:48.691</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VSPackage]Source: &apos;mscorlib&apos; Description: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)&#x000D;&#x000A;   at Roslynator.VisualStudio.AbstractPackage.&lt;InitializeAsync&gt;d__9.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()</description>
    <guid>{7AD86013-9E55-4BBE-98CC-DE72FADAB1E6}</guid>
    <hr>8000ffff - E_UNEXPECTED</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>2562</record>
    <time>2018/06/19 19:12:49.883</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VSPackage]Source: &apos;&apos; Description: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))&#x000D;&#x000A;System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr, Int32[] expectedHRFailure)&#x000D;&#x000A;   at Roslynator.VisualStudio.AbstractPackage.&lt;InitializeAsync&gt;d__9.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__78.MoveNext()</description>
    <guid>{F8A97C1B-B204-42B9-A881-816D250F2074}</guid>
    <hr>8000ffff - E_UNEXPECTED</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by JosefPihrt** [comment]
Hi,

Please try following steps:

* Uninstall Roslynator
* Delete content of the folder "%LOCALAPPDATA%\Microsoft\VisualStudio\15.0_xxxxxxxx\ComponentModelCache"
* Install Roslynator

**Comment by MikVar** [comment]
Performing these steps did not fix the issue.  However issuing the devenv /clearcache command after these steps did solve the problem.  I thought the clearcache command accomplishes the same thing as deleting the contents of the ComponentModelCache, but perhaps it does more. 

 

Thanks for your help.

**Comment by JosefPihrt** [comment]
:thumbsup:
