### ISSUE TITLE
RCS1143 - Shouldn't gray the second part of a coalesce, suggesting it's useless

### ISSUE THREAD

**Issue by Thieum** [JosefPihrt/Roslynator#39]
Using VS2015 Enterprise Update 3 / Roslynator 1.2.12 / .Net 4.6.2

![rcs1143-2](https://cloud.githubusercontent.com/assets/944894/22809849/01fb2206-ef03-11e6-82ae-c4b23230fc27.png)

RCS1143 when active seems to consider the second part of a coalesce expression as useless, graying it out in the UI (the warning doesn't pop in the IntelliSense list though).

It shouldn't use the graying effect, that is used for element that can be deleted or replaced safely, when that is not the case.

It would be nice if we could disable this refactoring too.

![rcs1143-options](https://cloud.githubusercontent.com/assets/944894/22810356/3743b736-ef06-11e6-9f1e-7dd9e88d3d2c.png)

**Comment by JosefPihrt** [comment]
Thanks for the report @Thieum .

**Comment by Thieum** [comment]
@JosefPihrt You're welcome, thanks a lot for the awesome tool and support =)
