### ISSUE TITLE
RCS1210 not found

### ISSUE THREAD

**Issue by aserdobintsev** [JosefPihrt/Roslynator#399]
RCS1210 is found only after RCS1016 was fixed, even if RCS1016 was turned off.
Is it correct behaviour or a bug?

**Null task not found**
<img width="256" alt="nulltasknotfound" src="https://user-images.githubusercontent.com/5861270/42211750-ba8193cc-7ecd-11e8-9420-350e5f2fd0bc.png">
**Null task found**
<img width="348" alt="nulltaskfound" src="https://user-images.githubusercontent.com/5861270/42211751-baad6aa6-7ecd-11e8-8ffe-291102c9dee2.png">
**Ruleset**
<img width="809" alt="ruleset" src="https://user-images.githubusercontent.com/5861270/42211976-45df2e20-7ece-11e8-8d24-562043b0239c.png">

P.S. If I click the right button of the mous  on the 'null' keyword, then refactoring suggestion appears.
<img width="710" alt="refactoringsuggestion" src="https://user-images.githubusercontent.com/5861270/42212365-537cc816-7ecf-11e8-936e-983e54907c75.png">
Environment: Visual Studio Enterprise 2017 15.7.4, Roslynator 2017 1.9.0 extension, Roslynator Refactorings 2017 1.9.0 extension.

**Comment by JosefPihrt** [comment]
This has nothing to do with RCS1016. It is just a bug in RCS1210.

**Comment by aserdobintsev** [comment]
Thanks for your quick response and for your work 💪!

**Comment by JosefPihrt** [comment]
You are welcome!
