### ISSUE TITLE
RCS1018 - Provide the ability to disable it in the options

### ISSUE THREAD

**Issue by Thieum** [JosefPihrt/Roslynator#40]
Using VS2015 Enterprise Update 3 / Roslynator 1.2.12 / .Net 4.6.2

Provide the ability to disable RCS1018 - Add default access modifier in the options.

![rcs1018](https://cloud.githubusercontent.com/assets/944894/22810414/9acfb6f6-ef06-11e6-9c8b-912188bcdaa8.png)

**Comment by JosefPihrt** [comment]
* Please distinguish between analyzer and refactoring. If it has a code like "RCS...." then it is analyzer.

* See [How to Customize Analyzers](http://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToCustomizeAnalyzers.md).

* Visual Studio options page works only for refactorings.

**Comment by Thieum** [comment]
@JosefPihrt Ah makes sense! Maybe it could help if you could add a column with the associated code in the options, as some of the refactoring share a name with analyzers.

**Comment by JosefPihrt** [comment]
Could you be more concrete about this proposal. I'm not clear about how it should look like and what is the purpose of it. Thanks.

**Comment by Thieum** [comment]
@JosefPihrt I thought refactorings already had IDs, but it seems only a proposal defined in #36 .
if #36 goes ahead, I was thinking about something like this, which would self document that refactorings are a different thing than analyzer, even if they share a name:

![refactorings](https://cloud.githubusercontent.com/assets/944894/23516254/b524e4e2-ff3a-11e6-81e1-cea6412ea34a.png)

**Comment by JosefPihrt** [comment]
@Thieum new options page with 'Id' column has been implemented [here](http://github.com/josefpihrt/roslynator/commit/734297a17d3a0f2d0b80ac7f0660e1253fd68e07) and [here](http://github.com/josefpihrt/roslynator/commit/167350f8f9227d84e6fc8ff1219a33cb02a2b72c).

So I think I can close this now.

**Comment by kieronlanning** [comment]
Perhaps I'm missing it, but where can I disable RCS1018 @JosefPihrt?

The list only has RR* refactorings in it.

**Comment by JosefPihrt** [comment]
@kieronlanning please see [How to Configure Analyzers](http://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md).

**Comment by kieronlanning** [comment]
Thanks @JosefPihrt, I saw that after posting it. I've set it up in our 72 project solution. But we'll need to remember to add that to new each project. Is there a simpler way?

**Comment by JosefPihrt** [comment]
Only "simpler" way I know about is to create a script that will edit csproj files.
