### ISSUE TITLE
Suggestion RCS1073: Use Alternate Example

### ISSUE THREAD

**Issue by slatejn** [JosefPihrt/Roslynator#405]
The second example shows a null return which is generally not the best idea as it requires extra handling. Examples in a tool that enforces best practices shouldn't demonstrate a potentially problem creating example (missing a null check against the return value).
Suggest an alternate test example that more clearly illustrates the requirement and still returns the (bool) evaluation of an if statement:
## Code with Diagnostic
```c#
int x = 1;
if (x.Length > 0) // RCS1073
{
    return true;
}
else
{
    return false;
}
```
## Code with Fix
```c#
int x = 1;
var evalCondition = (x.Length > 0);
return evalCondition;
```

**Comment by JosefPihrt** [comment]
Hi,

Could you explain what do you mean by "second example". Second example of what?

**Comment by JosefPihrt** [comment]
This:
```csharp
if (x != null)
{
    return x;
}
else
{
    return null;
}
```
can be replaced with this:
```csharp
return x;
```
What is wrong with this example?


I'm afraid I'm missing your point.

**Comment by slatejn** [comment]
There is nothing wrong with it.  To be clear, this is a suggestion not a problem. ;)

I agree that A can be replaced with B.  My issue is that  A seems like an edge case of the things people who are going to get this message will encounter. While there are valid cases to return a null, generally speaking, it isn't a good idea when there are other options because failing to check for a null is probably the most common logical error made by programmers (that need the examples). 
reasons:
Not only should the first half be re-written to not return a null when possible, but the replacement makes it harder to see and anticipate the null in the first place.

**Comment by Debbus72** [comment]
@slatejn For the whole 'return null should be avoided' statement, I would suggest that you look at the new C# 8.0 Nullable Reference Types ( [blog](https://blogs.msdn.microsoft.com/dotnet/2017/11/15/nullable-reference-types-in-csharp/) and [magazine](https://msdn.microsoft.com/en-us/magazine/mt829270.aspx) articles ). 

There may be room for additional analyzers regarding the new Nullable Reference types feature, but please let RCS1073 stay as-is.

**Comment by JosefPihrt** [comment]
I agree with @Debbus72 that RCS1073 should be kept as is.
