### ISSUE TITLE
[BUG] Settings page can't load when no solution is load

### ISSUE THREAD

**Issue by TobiasSekan** [JosefPihrt/Roslynator#406]
Problem
-------------------------------------------------------
The settings page of Roslynator crash or can't load

Steps to reproduce
-------------------------------------------------------
1. Start Visual Studio 2017 15.8 Preview 3
2. Don't load/open a solution, folder or file (no auto open)
3. Open Setting 
4. Go to Roslynator settings

Version
-------------------------------------------------------
Microsoft Visual Studio Professional 2017 Preview
Version 15.8.0 Preview 3.0
VisualStudio.15.Preview/15.8.0-pre.3.0+27825.0

**Comment by JosefPihrt** [comment]
This bug occurs only before first solution is loaded (not when no solution is loaded).

Workaround: do not open Roslynator options before first solution is loaded.
