### ISSUE TITLE
[Request] Add code fix for "use compound assignment" (RCS1058)

### ISSUE THREAD

**Issue by TobiasSekan** [JosefPihrt/Roslynator#410]
Currently, Roslynator has no code fix for

**RCS1058** - Use compound assigment
and
**RCS1058FadeOut** - Use compound assigment

It would be nice when Roslynator have this code fix in the next version :+1:

**Comment by JosefPihrt** [comment]
First of all, only purpose of ...FadeOut analyzers is to color tokens as "faded" which usually means that they are redundant and can be removed.

Secondly, I can see a code fix for RCS1058 in latest version of Roslynator 2017. Could you specify which version are you using?

**Comment by TobiasSekan** [comment]
Oh dammed :-D it was my fault, i have only activate the **FadeOut** rule and i haven't notice that it was set to **hidden**

**Comment by TobiasSekan** [comment]
Hm , I can see now a bulb but there is no code fix, I have activate all re-factorings and all code-fixes in the options. I use Roslynator version 1.9.1

**Comment by JosefPihrt** [comment]
Could you please provide a code sample that causes this behavior?

**Comment by TobiasSekan** [comment]
```
uint test = 1;
test = test * 50;
```

![2018-07-13 14_12_14-webvis - microsoft visual studio preview](https://user-images.githubusercontent.com/17874713/42691061-e4295c10-86a6-11e8-8faf-f6d10ba127c2.png)

![2018-07-13 14_14_40-webvis - microsoft visual studio preview](https://user-images.githubusercontent.com/17874713/42691152-245353f4-86a7-11e8-8ab3-d5682836559e.png)

**Comment by JosefPihrt** [comment]
@TobiasSekan Did you try to create a new solution and test this issue as I advise you.
