### ISSUE TITLE
Problems setting up for .NET Core

### ISSUE THREAD

**Issue by starquake** [JosefPihrt/Roslynator#412]
Thanks for the great Code Analyzer! But I'm having some issues on getting it to work on build.

I found a DefaultRuleSet.ruleset but I'm not entirely sure how to use it. 

Can I reference this file or do I need to copy paste this? It also has no names for the rules there so it doesn't show up in Visual Studio.

I also couldn't find any documentation that refers to this file. If you could help me setting up I'll make sure you get a pull request with some documentation for .NET Core.

**Comment by JosefPihrt** [comment]
Please follow these steps:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md#new-csproj-format-net-core-net-standard

to set up ruleset for .NET Core.

**Comment by starquake** [comment]
Yeah I saw that document but if you follow those steps you will end up with an empty set of rules. So if I understand correctly step 4 would be to add every single rule with an Id and an Action.

That's quite a lot of work. Is there some default set of rules? Could I use the DefaultRuleSet for that or do you have a better option?

Also if there are new rules introduced, do I have to add those manually to the ruleset too?

**Comment by starquake** [comment]
Yep I'm using Visual Studio 2017. Can you give me a hint where I could find that UI editor? The menu options you shown in your doc do not show up. I can create a global.ruleset but it does not show the rules of Roslynator. I can click Analyze -> Configure Code Analysis -> For Solution. But that shows a screen with the text: "There are currently no analyzable projects loaded."

**Comment by starquake** [comment]
BTW. What I want is to make sure the code gets checked on build. VS also has similar issues that might be related but that's not what I'm trying to fix right now.

**Comment by JosefPihrt** [comment]
> I can click Analyze -> Configure Code Analysis -> For Solution

Problem is that you are using the part of the documentation that is applicable only for old csproj format (.NET Framework).

This will never work. You have to follow the tutorial that is applicable for new csproj format (.NET Core)
https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md#new-csproj-format-net-core-net-standard

#### 1) Install VS extension "Roslynator 2017"

#### 2) Create new solution with a new project "Console App .NET Core"

#### 3) Add New Rule Set File to Your Solution

* Go to Solution Explorer - Solution - Context Menu - Add - New Item - Code Analysis Rule Set

#### 4) Attach Rule Set to Project(s)

* Open csproj file in text editor or go to Solution Explorer - Project - Context Menu - Edit ProjectName.csproj
* Add following `PropertyGroup` (or add element to the existing `PropertyGroup`):

```xml
<PropertyGroup>
  <CodeAnalysisRuleSet>relative_or_absolute_path_to_ruleset_file</CodeAnalysisRuleSet>
</PropertyGroup>
```

#### 5) Open ruleset by double-clicking on it.

**Comment by starquake** [comment]
> Problem is that you are using the part of the documentation that is applicable only for old csproj format (.NET Framework).

I did use the correct guide (see [comment](https://github.com/JosefPihrt/Roslynator/issues/412#issuecomment-405240547)). After trying it on a new project it does seem to work. It however does not work on my existing project. 

So that's the point where everything seems to fall apart. I'll see if I can find differences between a new project and and my existing one.

**Comment by starquake** [comment]
As soon as I add the Microsoft.EntityFrameworkCore nuget package the Code Analysis breaks down. 
So it looks like it has nothing to do with your software. I will close this and start looking in a different direction.
Thanks for your help!

**Comment by starquake** [comment]
Just wanted to add, it's even worse.
- Create a new project
- Add global ruleset like in your howto
- Everything works fine
- Close VS and reopen VS with solution
- Only 2 rulesets show up and the rest is gone...

**Comment by pawelklimczyk** [comment]
I;m currently expiring identical problem. 

dotnet core 2 projects (dll and web) and a global ruleset file added via context menu. Only 2 rulesets visible 
![image](https://user-images.githubusercontent.com/1084668/56914043-648a8280-6ab3-11e9-86a5-43d2c974a028.png)
