### ISSUE TITLE
RCS1146 refactoring suggestion results in broken code

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#42]
Given the following code, where `Data` is a class type with an `IDictionary<>` named `Dictionary` defined on it:

```
return data != null && data.Dictionary.TryGetValue(value, out result) ? result as T : null;
```

Roslynator 1.2.13 in VS 2017 RC flags this as RCS1146 and applies the following refactoring:

```
data?.Dictionary.TryGetValue(value, out result == true ? result as T : null
```

But this causes a syntax error due to the missing right parenthesis after `out result`, the correct code is:

```
data?.Dictionary.TryGetValue(value, out result) == true ? result as T : null
```

**Comment by JosefPihrt** [comment]
Thanks for the report @IanKemp !
