### ISSUE TITLE
RCS1202 Inconsistency

### ISSUE THREAD

**Issue by mdelbrocco** [JosefPihrt/Roslynator#423]
I noticed a bit of inconsistency that you may want to look into regarding [RC1202](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1202.md).

The example shows it working for FirstOrDefault() - suggesting the Elvis operator after the method call to avoid a potential nullref. I noticed that in my code, I have an instance of SingleOrDefault() that SHOULD be getting this suggestion (as the signature is the same as FirstOrDefault()), but I'm not getting anything. I *have* verified that Roslynator gives me the suggestion when I change my SingleOrDefault() call to FirstOrDefault().

Not a showstopper by any means, but figured I'd point it out in case it's helpful.

Thanks,
-Matt

**Comment by JosefPihrt** [comment]
Since SingleOrDefault will throw if there is not a single element in a sequence it has no meaning to add conditional access (aka elvis operator). In other words, InvalidOperationException will be thrown sooner than NullReferenceException.

**Comment by mdelbrocco** [comment]
"SingleOrDefault will throw if there is not a single element in a sequence"
This isn't entirely true. If the list is empty, `null` will be returned. In this scenario, a null reference exception may occur.

Also FWIW, in my case, I was using SingleOrDefault with the lambda parameter.

**Comment by JosefPihrt** [comment]
You are right. I'm going to fix it.
