### ISSUE TITLE
Disable by default RCS1174: Remove redundant async/await

### ISSUE THREAD

**Issue by mvelosop** [JosefPihrt/Roslynator#429]
Hi Josef,

Thanks for a great tool!

Today I found that [RCS1174](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1174.md) is enabled by default and, according to a [recommendation from a blog post from Stephen Cleary](http://blog.stephencleary.com/2016/12/eliding-async-await.html), which was [confirmed by the .NET team regarding a PR in eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/pull/568#issuecomment-383117319), that should not be the default option.

I'm pretty clear I can disable it (which already did) but being it enabled by default can unknowingly lead to difficult to track problems for people following this guidance. As a matter of fact, based on authoritative recommendations, I think the guidance should be quite the opposite, i.e. warn when returning a Task.

Thanks again.

**Comment by JosefPihrt** [comment]
Hi Miguel,

First of all, thanks for your donation I appreciate it.

Your concern with "Remove redundant async/await" seems to be reasonable.

Disable RCS1174 by default would be one of possible solutions.

I'm also thinking about introduce new refactoring with the same functionality as RCS1174 (in addition to disabling it).

By the way, I have recently introduced a new [analyzer](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1229.md) that enforces using async/await.

**Comment by mvelosop** [comment]
Hi @Josef,

Thanks for your reply and considering this issue!

This has been a hot topic in more than one discussion, mostly justified by efficiency and I have to acknowledge that I did that kind of "pre-optimization" at some point!

Anyway, thanks for this tool, it's really helpful and hope it gets to mean a helpful income for you.

Cheers.
