### ISSUE TITLE
RCS1146 Codefix Inconsistency

### ISSUE THREAD

**Issue by nnpcYvIVl** [JosefPihrt/Roslynator#432]
RCS1146 currently applies the following fix.

### Code with Diagnostic

```csharp
if (s != null && s.StartsWith("a")) // RCS1146
{
}
```

### Code with Fix

```csharp
if (s?.StartsWith("a") == true)
{
}
```

The original statement doesn't use ```== true``` so shouldn't the fixed code follow the original pattern?

### Code with Proposed Fix

```csharp
if (s?.StartsWith("a"))
{
}
```

**Comment by JosefPihrt** [comment]
Your fix contains error (CS0266). Why to suggest to user a fix with broken code?
