### ISSUE TITLE
RCS1163 triggered on not existing/temp file

### ISSUE THREAD

**Issue by JAD-SVK** [JosefPihrt/Roslynator#436]
Today I got to see the following message from Roslynator on my C# project:

|Severity|Code|Description|Project|File|Line|Suppression State|
|---|---|---|---|---|---|---|
|Message|RCS1093|Remove file with no code.|*project name*|`C:\Users\`*`user_name`*`\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cs`|1|Active|

Additional info: 

* there is no `*.cs` file in the `C:\Users\`*`user_name`*`\AppData\Local\Temp\` directory,
* message still displayed after restart of VS and removing all files from temp folder,
* this message was not displayed two-three days ago,
* the files without code only standard files: `Properties\AssemblyInfo.cs` and `Properties\Resources.resx`

OS: Windows 7 x64 Professional,
VS: Visual Studio 2017 Community,
Project: .NET Framework 4.0, Console application

**Comment by JosefPihrt** [comment]
@JAD-SVK Can I ask you what exactly is meant by this:

> * the files without code only standard files: `Properties\AssemblyInfo.cs` and `Properties\Resources.resx`
