### ISSUE TITLE
RCS1046: do not base it on async keyword, but on Task return type

### ISSUE THREAD

**Issue by antoinebj** [JosefPihrt/Roslynator#437]
Hi,

Although it can be a subject of debate as it can be considered as some sort of Hungarian notation, our team decided to use the 'Async' suffix for asynchronous method names to comply with the [official Microsoft guideline for TAP](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap) and for better readability in code reviews.

Rule RCS1046 could be helpful to us. Unfortunately it is basing its decision on the presence or absence of the `async` keyword, which does not quite make sense. This [SO answer](https://stackoverflow.com/a/37466440) and the whole discussion in general gives a bit of insight, and it is interesting to note that Microsoft has since changed their guideline to not mention the presence of the `async` keyword anymore for the subject of adding the suffix to the name.

Anyway, for our purpose, I have found that with very few exceptions all methods returning a `Task` type are eligible for the 'Async' suffix, regardless of their use of the `async` keyword (sometimes they simply forward the call).
As for `async void` methods, as is argued in the SO discussion that I linked above, these should in theory never be public and as such shouldn't need to publicize their asynchronous nature. But I'll add that even if they were public, since the async work that they do cannot be awaited, it is probably work that the caller should not have to care about, and therefore the caller does not need to know that there is anything asynchronous going on. Besides, it would create confusion in code reviews, methods that end with Async are usually expected to either be awaited or have their returned task used in some way.

So my suggestion would be to label this a bug and change the implementation of this rule to only verify whether the return type is `Task`/`Task<>` or not.

If you agree with that suggestion, even though I'm not familiar with the code base, it seems easy enough to understand for me to attempt a pull request.

**Comment by Vivelin** [comment]
Something to keep in mind: **Task** isn't the only type that can be awaited. **ValueTask** is a relatively new example where this rule would need to apply as well, and UWP has **IAsyncAction**. Neither of these inherit from **Task**.

Except for `async void`, I believe the only requirement is that it requires a **GetAwaiter** method, which in turn does not need to return any specific type as long as it implements certain members. However, it can be an extension method as well (as is the case with **IAsyncAction**).
