### ISSUE TITLE
RCS1155 reported when comparing partial strings using contains.

### ISSUE THREAD

**Issue by keenam** [JosefPihrt/Roslynator#441]
I have a code that lowers the string and checks to see if the string contains the text.  That line gets reported by RSC1155.

e.g.
``` cs
if (text.ToLower().Contains("kee")) // RCS1155 is reported here.
{
}
```

**Comment by LesRamer** [comment]
Roslynator has an autofix that replaces the Contains check with IndexOf. 
So your example will get an autofix like the following:

```csharp
if (text.IndexOf("kee", StringComparer.OrdinalIgnoreCase) >= 0)
{
}
```

**Comment by keenam** [comment]
Sorry, I thought it would autofix with `string.Equals` as stated on the [site](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1155.md).  I have tested autofix. It does as @LesRamer mentioned.
Thanks!

**Comment by JosefPihrt** [comment]
RCS11555 applies to many kinds of string operators/methods such as `==`, `!=`, `Equals`, `StartsWith`, `EndsWith`, `IndexOf`, `LastIndexOf` and `Contains`.

The site contains only one example where `==` is replaced with `Equals`.

Contains cannot be replaced with `Equals` but it can be replaced with `IndexOf`.

**Comment by nvmkpk** [comment]
@JosefPihrt why does it replace `Contains` with `IndexOf` while `Contains` does have an overload that takes `StringComparison` argument?

**Comment by JosefPihrt** [comment]
@nvmkpk ae6200d14bef1c0eb905b94bcbb54ee0e67ceb83
