### ISSUE TITLE
Suggestion: Add ability to disable rules without requiring a ruleset

### ISSUE THREAD

**Issue by udlose** [JosefPihrt/Roslynator#451]
I have recently installed Roslynator and (unsurprisingly) see a lot of noise with the inherited codebase. This codebase does not have a ruleset in the  repository and i'm the only one wib Roslynator installed.  The only way I can find on disabling some of these rules is thru a ruleset. This is not practical in my case since I'm the only one with it installed. Plus, I have to add it to my .gitignore so the ruleset isn't accidentally checked in.

ReSharper has the ability to configure warnings, errors, etc. thru the settings for the extension in VisualStudio. It would be so much more helpful if I could do this.

**Comment by udlose** [comment]
1. I'm the only developer on the team with the extension installed. 

2. I shouldn't have to add code to suppress a warning that only 1 Dev on the team sees because of an extension they have installed. And it is certainly not reasonable to have all the devs install this (though IMO they should).

3. I shouldn't have to add a ruleset just to suppress a warning that only 1 Dev sees. My TL wouldn't allow it anyways.

4. I shouldn't have to add a nuget to 27 projects just to suppress warnings that only affect 1 Dev. TL wouldn't want that either.

5. There is no reason it shouldn't work just like Resharper. You can control inspections and their severity locally to a machine.

**Comment by jhinder** [comment]
As you're drawing comparisons to Resharper: their users certainly don't have problems with adding Resharper attributes to everything (and the corresponding `JetBrains.Annotations` package -- yes, it's a development dependency, but so is Roslynator, and you only need to add that once per solution), adding `// ReSharper disable` comments here and there, and adding Resharper-specific files to the project (`.dotSettings`). If all that is fine, I don't get why adding a ruleset file is not okay.

**Comment by starquake** [comment]
I have to agree on @udlose here. Try contributing to a repository on github and commit a change to .gitignore or try adding pragma's to disable Roslynator stuff. Big chance they won't allow it.

We can already set settings for Code Fixes and Refactorings. Sounds naturally to me add the settings for the rules there:
![image](https://user-images.githubusercontent.com/1044544/47853823-47b11300-dde0-11e8-8dfb-ab1afb3b4b68.png)

**Comment by udlose** [comment]
@jhinder
It is unreasonable to assume that all Resharper users use their product in the same way. I've consulted for many companies, large and small. Each use the product in a way that suits them. Some teams are fine with putting Resharper pragma's everywhere (which makes the code look like crap IMO). Some teams don't use it in that way and use a shared Resharper file across the team. Some teams do neither of the above and leave it to each developer to use their own extensions and make changes based on what each feels is in the benefit of the codebase. 

When you develop a tool for someone to use, you have to think of how they will use it instead of writing it in a way that forces them to do X, Y, and Z to "kinda make it work" for them.  Otherwise, people just won't use it. I think this is a great tool and was very excited when I found it. But if I'm not able to use any tool in a way that is useful and productive to me, I won't use it at all.

**Comment by JosefPihrt** [comment]
I have a fix for this in #461
