### ISSUE TITLE
RCS1120 incorrectly triggers for a nullable struct

### ISSUE THREAD

**Issue by NickCraver** [JosefPihrt/Roslynator#454]
Came across an issue with RCS1120 when dealing with nullable structs. Here's a simplified example case:
```c#
var value = new DateTime?();
if (value is DateTime?)
{
    var asNullableDate = (DateTime?)value;
}
```
RCS1120 suggests the refactoring to:
```c#
var value = new DateTime?();
if (value is DateTime? dateTime)
{
    var asNullableDate = (DateTime?)dateTime;
}
```

...but since `DateTime?` is a struct, that's not valid C#.

**Comment by JosefPihrt** [comment]
This has been fix in 9109d9828381b3cf7fb5f45a7d53af226891a87c. Please install latest version.

**Comment by JosefPihrt** [comment]
I've just realized that only package Roslynator.Analyzers had been released since the fix was applied. If you use VS extension you have to wait till next release.

**Comment by NickCraver** [comment]
Gotcha - I was about to say I'm on 2.0.0 :) Thanks for fixing already!
