### ISSUE TITLE
Roslynator.CodeFixes nuget package does not add code fixes

### ISSUE THREAD

**Issue by InvalidCast44** [JosefPihrt/Roslynator#456]
hi!

i though by adding Roslynator.CodeFixes package to a project, i would have access to code fixes in it (all "RR" code fixes)

![image](https://user-images.githubusercontent.com/28800506/48048658-80643a00-e19c-11e8-9eb5-f15304a8a162.png)

for example, on this picture you can see i can't use RR0062 (inline method)

does my first assumption was wrong?

**Comment by JosefPihrt** [comment]
Package Roslynator.CodeFixes contains code fixes for CS diagnostics (compiler diagnostics).

If you want to use refactoring "Inline method" (and other refactorings) you have to install one of the VS extension:
https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017
https://marketplace.visualstudio.com/items?itemName=josefpihrt.RoslynatorRefactorings2017
