### ISSUE TITLE
Feature Request: use "is null" instead of "== null" and vice versa

### ISSUE THREAD

**Issue by TobiasSekan** [JosefPihrt/Roslynator#458]
Hello,

It would be nice when rosylnator have code analysis and refactoring for
`is null` and `== null`

```csharp
// before refactoring
if(parameter == null)
{
    parameter = newValue;
}

// after refactoring
if(parameter is null)
{
    parameter = newValue;
}

// and vice versa
```

* Visual Studio 2017 - 15.9.0 - Preview 5.0
* Roslynator 2017 - 2.0.0

**Comment by JosefPihrt** [comment]
Are you proposing [analyzer or refactoring](https://github.com/JosefPihrt/Roslynator/blob/master/docs/AnalyzersVsRefactorings.md)?

**Comment by TobiasSekan** [comment]
The first -> Analyzer (+ Code Fix)

Analyzer rules:
1. use always `== null` instead of `is null`
2. use always `is null` instead of `== null`
