### ISSUE TITLE
Suggestion: Recognize "default(T)" is alias for "new T()"

### ISSUE THREAD

**Issue by tamlin-mike** [JosefPihrt/Roslynator#462]
Code of the form
```
var t = default(T);
t.f1 = xxx;
```
is not recognized for "Object initialization can be simplified".

Obvious workaround is to manually change `default(T)` to `new T()`, but it would be nice if the refactoring recognized `default(T)` as presented.

**Comment by JosefPihrt** [comment]
"Object initialization can be simplified" is built-in analyzer provided by Microsoft. I would suggest to file this issue to https://github.com/dotnet/roslyn/issues
