### ISSUE TITLE
Rule document explanation

### ISSUE THREAD

**Issue by cviktor** [JosefPihrt/Roslynator#463]
Hi,

I think it would be helpful to document what the different fileds in the table of a rule description means. (The table at the top of these documents: https://github.com/JosefPihrt/Roslynator/blob/master/src/Analyzers/README.md)

I think it is a not very straightforward what the following items mean:

- Enabled by Default
- Supports Fade-Out
- Supports Fade-Out Analyzer

For example what happens when the Enabled by default has a value `-` but the default severity is Info, or what the Fade-Out and the Fade-Out analyzer means. (I did not found anything about the fade-out analyzer at all)

Thanks,
Viktor

**Comment by cviktor** [comment]
It sounds good if you think there is no added value in the fields.

What about the fade-out functionality? I found some explanation in the #107 If it works like that, then I think the table should look like this:

Property | Value
-- | --
Id | RCS1001
Category | Style
Severity | None\|Hidden\|Info\|Warning\|Error
Supports Fade-Out | -\|✓

And we should create a docs explaning how to configure it.

**Comment by JosefPihrt** [comment]
"Supports Fade-Out" is now obsolete because I recently made so called "fade-out" analyzers "not configurable" which means that they are not configurable by the user (see 52675bf9f86c344a1b9cf9e85407b79943e7fa87).

**Comment by JosefPihrt** [comment]
Yes,

"not enabled by default" is equal to "None" severity.

**Comment by cviktor** [comment]
Then your proposal seems fine. What should be the next step? Do you want to update the existing docs, or just slowly when you need to modify one for some other reason?

**Comment by JosefPihrt** [comment]
I'm going to update them all.

**Comment by cviktor** [comment]
Ok, thanks for your answer I think it will be more clear now.

You can close this issue if you want, or leave it here to track the work.

**Comment by JosefPihrt** [comment]
Thanks for the suggestion!
