### ISSUE TITLE
feature request : Inline parameter name hints

### ISSUE THREAD

**Issue by iAmBipinPaul** [JosefPihrt/Roslynator#464]
something like this 

![xmldoc-on-hover](https://user-images.githubusercontent.com/9201481/49098936-37ce0700-f298-11e8-838e-fff0150f8001.png)

**Comment by JosefPihrt** [comment]
Hi,

I'm sorry, I don't understand your request. Could you provide a code sample (one before the change and one after)?

**Comment by iAmBipinPaul** [comment]
Hi , This feature was already present in the ***jetbrains webstorm*** , they recently introduced this in ***ReSharper***.

Here is the related blog.
https://blog.jetbrains.com/dotnet/2018/11/27/inline-parameter-name-hints-c-vb-net-resharper-rider/

before 
`var people = peopleService.Find("Maarten", null, false);`

after 

![inline-parameter-hints-null-boolean](https://user-images.githubusercontent.com/9201481/49101571-a0b87d80-f29e-11e8-98a4-d47778a2fb9b.png)

**Comment by JosefPihrt** [comment]
If I understand it correctly, you don't want to actually have parameter name in the source code you just want to see parameter name in the IDE.

But is there any reason not to have parameter name to the source code? Then the source code will be readable for everyone, not only for those who read it through IDE.

There are refactorings that add/remove parameter name:
http://pihrt.net/Roslynator/Refactorings?Query=parameter+name

**Comment by iAmBipinPaul** [comment]
Wow , That's alray there(source code) 🆒 
Having that in source  looks much better but It will be awesome  to have hotkey for that, so that we can toggle that apply (add/Remove) for a method and also option to  apply (add/remove ) that in file /project and solution level.
