### ISSUE TITLE
RCS1004 should not be suggested if block contains comments after statement

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#467]
I think it should not be suggested to remove the braces from code like the following
```
		if (condition)
		{
			computeSomething();
			//commentedStuff();
		}
		else
			doSomethingElse();
```

Apparently, if there is comments above the statement, RCS1004 already disables itself. But not when there is comments below.

**Comment by JosefPihrt** [comment]
fixed with 334c1645b15ab4f9281afe122bcdd7295d1440ac
