### ISSUE TITLE
RCS1146 (Use conditional access) is truncating bool property names

### ISSUE THREAD

**Issue by NickCraver** [JosefPihrt/Roslynator#47]
Best explained in a picture:

<img width="803" alt="screen shot 2017-02-18 at 10 58 11" src="https://cloud.githubusercontent.com/assets/454813/23094582/c2ab2934-f5c9-11e6-8d94-6f2f6ca615a0.png">

This only happens if there's trailing boolean logic afterwards. Here's a minimal repro:
```c#
public class A
{
    public bool Prop { get; }
    public static GetProp(A obj)
    {
        if (obj != null && obj.Prop && true)
        {
            Console.WriteLine("Hey!");
        }
    }
}
```
Currently, RCS1146 refactors this to:
```c#
        if (obj?.Pro == true && true)
        {
            Console.WriteLine("Hey!");
        }
```
Relevant code link: [UseConditionalAccessRefactoring.cs#L139](https://github.com/JosefPihrt/Roslynator/blob/master/source/Analyzers/Refactorings/UseConditionalAccessRefactoring.cs#L139)

**Comment by JosefPihrt** [comment]
This has been fixed in #42.
