### ISSUE TITLE
RCS1040 should not be suggested if 'else' block is followed by another (upper) 'else' block

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#475]
Empty else clause should not be suggested for removal if it is immediately followed by another else clause, as this would change the meaning of that code construction.

```
	if (x)
		if (y) doSomething(); else { }
	else
		doSomethingElse();
```

**Comment by wiz0u** [comment]
unless the following else clause is outside brackets like this:
```
	if (x)
	{
		if (y) doSomething(); else { }
	}
	else
		doSomethingElse();
```
Then it is safe for removal

**Comment by JosefPihrt** [comment]
Good catch!
