### ISSUE TITLE
RCS1065 Documentation/Codefix Inconsistency

### ISSUE THREAD

**Issue by nnpcYvIVl** [JosefPihrt/Roslynator#484]
According to the documentation at https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1065.md a while loop should be replaced with a do while loop.

```
Code with Diagnostic

while (true) // RCS1065
{
}

Code with Fix

do
{
}
while (true);
```

When I run the codefix it generates a for loop instead of a do while loop:

```chsarp
for (; ; )
{
}
```

Is the documentation incorrect?

**Comment by JosefPihrt** [comment]
Documentation is wrong.
