### ISSUE TITLE
Roslynator.CommandLine properties parameter

### ISSUE THREAD

**Issue by nnpcYvIVl** [JosefPihrt/Roslynator#489]
Roslynator.exe help analyze shows the following parameter ```-p <NAME=VALUE>, --properties=<NAME=VALUE>    Defines one or more MSBuild properties.```

When I use ```--properties=Configuration=Release``` on the command line I get the following error
```
ERROR(S):
A required value not bound to option name is missing.
```

Is my syntax wrong?

**Comment by JosefPihrt** [comment]
Proper syntax is:
```
--properties Configuration=Release CodeAnalysisRuleset=my.ruleset
```

This line:
```
-p <NAME=VALUE>, --properties=<NAME=VALUE> Defines one or more MSBuild properties.
```

is generated by third party library that is responsible for parsing command-line parameters. I don't know why there is an equal sign.

Working scripts can be found here: https://github.com/JosefPihrt/Roslynator/tree/master/tools.
Namely the ones that are prefixed with underscore.

**Comment by nnpcYvIVl** [comment]
@JosefPihrt I get the same error with ```--properties Configuration=Release```

**Comment by nnpcYvIVl** [comment]
@JosefPihrt Thanks, I figured it out.

This fails:
```Roslynator.exe analyze --ignore-compiler-diagnostics --use-roslynator-analyzers --ignore-analyzer-references --properties Configuration=Release "C:\Workspace\Solution.sln"```

This works:
```Roslynator.exe analyze --ignore-compiler-diagnostics --use-roslynator-analyzers --ignore-analyzer-references "C:\Workspace\Solution.sln" --properties Configuration=Release```

**Comment by JosefPihrt** [comment]
It seems that the parsing library I mentioned before does not allow solution/project path to be at last position.
