### ISSUE TITLE
UnusedMemberWalker is rooting Roslyn compilations

### ISSUE THREAD

**Issue by sharwell** [JosefPihrt/Roslynator#492]
The following thread-static field is keeping Roslyn compilations alive in memory, leading to severe performance degradation when used inside Visual Studio. In [this feedback report](https://developercommunity.visualstudio.com/content/problem/427776/freeze-and-lag-while-editing-c.html), 65 instances of `UnusedMemberWalker` in this cache rooted 48 `CSharpCompilation` instances through the `SyntaxTreeSemanticModel`.

https://github.com/JosefPihrt/Roslynator/blob/b2c2493c880ccd06215a11fa7b42b64a1fea0470/src/Analyzers/CSharp/Analysis/UnusedMember/UnusedMemberWalkerCache.cs#L12-L13

**Comment by JosefPihrt** [comment]
Thanks for the report @sharwell !
