### ISSUE TITLE
Why is RCS1083 deprecated?

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#510]
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1083.md

What is its replacement?

**Comment by JosefPihrt** [comment]
This analyzer was incorporated into https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1077.md

**Comment by JosefPihrt** [comment]
b83946468c1899c14a025158853eb430df963a41
