### ISSUE TITLE
Roslynator 2017 not working alongside Resharper

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [JosefPihrt/Roslynator#511]
Thanks for the Visual Studio extension. 
I am using this extension alongside ReSharper.

The extension is showing messages and warnings. 
When I click on any message or warning it's taking me to that line but then there is no quick action on the left side of the IDE.

![image](https://user-images.githubusercontent.com/10863510/53797330-fa92a880-3f5b-11e9-80a6-0a44595fd3e6.png)

When I disable the ReSharper and follows the same steps, It does show the Quick Actions.

![image](https://user-images.githubusercontent.com/10863510/53797337-ff575c80-3f5b-11e9-9e21-6cd11f5935b3.png)

![image](https://user-images.githubusercontent.com/10863510/53797388-17c77700-3f5c-11e9-9cb6-e995735e51be.png)

**Info**

Visual Studio - 15.9.7
Resharper Ultimate - 2018.3.4
Roslynator 2017 - 2.0.2

Is there any way, I can get you more information, if there are exceptions when the Roslynator 2017 extension loads?

**Comment by lukasf** [comment]
Roslynator has been built to allow you to finally uninstall the ultra-slow Resharper bloat! ;)

**Comment by JosefPihrt** [comment]
Hi,

I don't have Resharper so I cannot test it.

But my understanding is that you don't see lightbulb icon when Resharper is enabled but you see quick actions when you use hotkey ctrl+. (or alt+enter)? If I'm right then it seems that Resharper is using bar on the left side to display its own icons.

Bottom line is that this behavior is probably caused by Resharper, not Roslynator.

**Comment by sawankumarbundelkhandi** [comment]
@JosefPihrt, I don't see Roslynator quick actions even using hotkey ctrl+. (or alt+enter) when ReSharper is enabled.
This issue might be happening because of some component cache. I will try to reinstall VS, Resharper, and roslynator. 
Never mind, I am closing this ticket for now.

**Comment by lukasf** [comment]
You might want to check out this Resharper setting:

![resharper](https://user-images.githubusercontent.com/2306201/53950272-16b55780-40cc-11e9-8ba1-79de51657155.png)

**Comment by sawankumarbundelkhandi** [comment]
The fix is to enable this setting in reshaper.

![resharper_settings](https://user-images.githubusercontent.com/10863510/59039633-d021f580-8892-11e9-85f4-7093dc3c78f3.jpg)
