### ISSUE TITLE
Suggestion: Add parameter to interface, remove parameter from interface

### ISSUE THREAD

**Issue by lukasf** [JosefPihrt/Roslynator#512]
Great work is being done here!

This is one of the refactorings I still miss from Resharper: 

My class implements an interface `IMyInterface `with method `void Test()`. During implementation, I find I need a parameter, so I change the implementation method to `void Test(bool myParam)`. Now I would like to get a QuickFix: "_Add parameter 'myParam' to 'IMyInterface.Test()'_". Similarly, if I later find out that I do not need that parameter anymore and remove it, I would like to see a QuickFix "_Remove parameter 'myParam' from interface 'IMyInterface.Test()'_".

So what Roslynator would need to do is check
- Is there an interface method with the same name that is currently not implemented
  - Would the interface be implemented if the last method parameter is added to interface
    - Show "Add parameter" quick fix
  - Would the interface be implemented if the last parameter from interface is removed
    - Show "Remove parameter" quick fix

Optionally, this could even support adding or removing multiple parameters in one go. But much more important is the simple case of just adding or removing one parameter. That would be awesome.

**Comment by JosefPihrt** [comment]
@lukasf Could you provide a link to Resharper docs where this feature is described?

**Comment by lukasf** [comment]
@JosefPihrt Here you can see the documentation from ReSharper:

https://www.jetbrains.com/help/resharper/Refactorings__Inplace_Refactorings.html#change_signature

Check the second example in the Change Signature area. ReSharper also detects other signature changes such as remove parameter, reorder parameter, change parameter type. I think add and remove are the most important scenarios, that is why I recommended them here.
