### ISSUE TITLE
InvalidCastException in error list

### ISSUE THREAD

**Issue by lukasf** [JosefPihrt/Roslynator#513]
I get an InvalidCastException in the errors list:

> Warning	AD0001	Analyzer 'Roslynator.CSharp.Analysis.SingleLineDocumentationCommentTriviaAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.XmlEmptyElementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.XmlElementSyntax'.'.	Philips.PmsGxr.DynamicViewer		1	Active

Running on VS2019 RC1. I cannot say which element this comes from. It might be something like `<summary />`, but I am just guessing here, since I do not get a file or line number.

**Comment by JosefPihrt** [comment]
A duplicate of #487

**Comment by JosefPihrt** [comment]
Related to RCS1228
