### ISSUE TITLE
Global suppressions not working

### ISSUE THREAD

**Issue by lukasf** [JosefPihrt/Roslynator#514]
I have disabled RCS1138 and RCS1168 in the Roslynator settings. But still my error window is flooded with RCS1138 and RCS1168.

Our company uses Resharper, so I cannot add Roslynator comments to our files and I have to use global suppressions instead.

I am testing this on VS2019 RC1.

**Comment by JosefPihrt** [comment]
The option has limited functionality which means that it will not delete existing diagnostics from the Error List, but it will stop reporting new ones.

It is meant to be used as a "last resort" option when you cannot use ruleset file.

**Comment by lukasf** [comment]
If I close VS and open it again with the same solution, full solution analysis starts again and shows all the errors again once analysis is completed. So to me it looks like the errors are added again, although disabled. 

Or is there some caching going on? It does not seem so, since errors only show up once complete analysis is done.

**Comment by JosefPihrt** [comment]
Problem is that "global suppressions" feature does not work (and won't work) with "full solution analysis" option enabled.

"Full solution analysis" runs on its own process (ServiceHub.RoslynCodeAnalysisService32.exe). It is not possible to pass Visual Studio options to this process.

It can only add warning to option page, something like: "Global suppressions does not work with full solution analysis enabled".

**Comment by lukasf** [comment]
Is it not possible to load the options from a config file or Windows Registry or something like that?
