### ISSUE TITLE
RCS1080: Don't recommend using Count() instead of Any() 

### ISSUE THREAD

**Issue by HeinzKessler** [JosefPihrt/Roslynator#523]
Using Count() to find if a collection contains > 0 elements is generally considered bad style.
The reason is, that counting all elements in a collection is much more expensive that just testing if there is at least one element, like Any() does.

If an equivalent alternative is needed, then the replacement could be

`_collection_.FirstOrDefault() != null`

Maybe this RCS could stay the same for arrays (array.Length), since this is not as expensive as Count() with a collection.

**Comment by JosefPihrt** [comment]
RCS1080 should replace `Any()` with `Count` or `Length` property. Replacing `Any()` with `Count()` would not make sense. Could you provide a code sample to clarify your post?

`_collection_.FirstOrDefault() != null` will be replaced with `_collection_.Any()` by RCS1077.

**Comment by HeinzKessler** [comment]
I must apologize.
I didn’t recognize, that RCS1080 only recommends `Count` and `Length` (e.g. for `List<>`’s), but not `Count()` (=LinQ), therefore there is no performance penalty.
Therefore I close the issue.

**Comment by JustDre** [comment]
Any() expresses intent much better than Count != 0, IMO.  Its performance is highly dependent on the compiler optimization that recognizes whether the IEnumerable has a Count or Length property and inlines the call to Any(), effectively replacing it with the exact same code as this recommendation.  Would the RCS take this into consideration?

**Comment by JosefPihrt** [comment]
I thought about it and it makes sense to disable RCS1080 by default.

Performance gain is negligible and it is more readable to use `Any()`.
