### ISSUE TITLE
Null check for catch clause

### ISSUE THREAD

**Issue by Danghor** [JosefPihrt/Roslynator#527]
In the `RemoveOriginalExceptionFromThrowStatementAnalyzer`, there is a null check for the catch clause. I am currently struggeling with covering this line with a unit test. How could the catch block ever be `null`? Even if it is empty, it would not be `null` then.

https://github.com/JosefPihrt/Roslynator/blob/fecd10812f7c48869d6720a031e40d08cb9d374d/src/Analyzers/CSharp/Analysis/RemoveOriginalExceptionFromThrowStatementAnalyzer.cs#L31-L40

**Comment by JosefPihrt** [comment]
I suppose it can be null in case of invalid code.

```csharp
try
{
    Foo();
}
catch
```

**Comment by JosefPihrt** [comment]
Update: it seems that it actually cannot be null:
https://github.com/dotnet/roslyn/blob/e633085334b714ca051bfdf27922f4be4f61b1ee/src/Compilers/CSharp/Portable/Generated/Syntax.xml.Main.Generated.cs#L8436
