### ISSUE TITLE
Question: apply refactorings on entire solution

### ISSUE THREAD

**Issue by juavol** [JosefPihrt/Roslynator#528]
I understand the distinction between a refactoring (which can be selectively applied) and analyzers producing code fixes (which can be applied in batches in VS or via command line).

I would like to cleanup a legacy solution by applying a number of refactorings, such as converting from getXXX()/setXXX() methods to properties, converting to auto-properties, etc.

These are currently refactorings (both in Roslynator as well as lightbulbs in VS2017 itself), but not code-fixes, so I would need to apply these one by one (for 300+ cases, ...)

Is there a way to do this automatically? Can I configure or create an analyzer rule which would create a corresponding code fix?

**Comment by JosefPihrt** [comment]
It's not possible now but it may be in the future, see https://github.com/dotnet/roslyn/issues/32461
