### ISSUE TITLE
RCS1093 Bad behavior on non-empty #if <def> files

### ISSUE THREAD

**Issue by NickCraver** [JosefPihrt/Roslynator#53]
I'm not sure what to suggest here, just providing that the suggestion is odd. Analyzer in play:
> RCS1093: Remove file with no code.

But when compiling projects where the whole file is `#if` conditioned, this is an invalid suggestion *overall*. Example:

```c#
#if NET46
namespace MyTests
{
    public class Test { }
}
#endif
```
...when the project targets both `netstandard1.5` and `net46`. Screenshot of my example case:
<img width="1046" alt="screen shot 2017-02-26 at 10 07 15" src="https://cloud.githubusercontent.com/assets/454813/23340878/e6773a86-fc0b-11e6-9de7-d45651e0f307.png">

So while in the context of *that particular framework compilation* there isn't any used code, there is code in the *file* (where the suggestion points). Is it possible to change this check for actual empty files, or is there no knowledge of that available?

**Comment by NickCraver** [comment]
Thanks!

**Comment by JosefPihrt** [comment]
My pleasure!
