### ISSUE TITLE
RCS1046 should not be raised for overridden methods

### ISSUE THREAD

**Issue by daveaglick** [JosefPihrt/Roslynator#539]
**Product and Version Used**: Roslynator.Analyzers 2.0.0

**Steps to Reproduce**: Override a base method that does not end in "Async", that returns `Task`, and use the `async` keyword.

**Actual Behavior**: RCS1046 is raised due to the overridden method being `async` but not having the "Async" suffix.

**Expected Behavior**: I'd suggest overriden methods be excluded from RCS1046 since the implementation has no control over the method name. If the code is under your control, you'll still get the RCS1046 error in the base definition. If not, there's no way to correct the error unless you supress it.

**Comment by daveaglick** [comment]
Wow, that was fast! Thanks!

**Comment by JosefPihrt** [comment]
You're welcome!
