### ISSUE TITLE
Keeps disabling itself

### ISSUE THREAD

**Issue by kentcb** [JosefPihrt/Roslynator#54]
No matter how many times I re-enable the addon, it just keeps disabling itself. This is in VS2015.

Any thoughts on how to identify the cause of this?

**Comment by JosefPihrt** [comment]
Please see #18

**Comment by kentcb** [comment]
Hmm, I had quite a few dupes! Now wondering whether this is "normal" for VS to keep dupes around...

Will try running without dupes today and see how it goes.

**Comment by kentcb** [comment]
Well, I've been running a whole day now without it disabling itself, so seems the duplicate addons were root cause.

Still interested in whether this is a VS problem or a Roslynator one, but will close this for now.
