### ISSUE TITLE
RCS1181 (Replace comment with documentation comment) gives false positive

### ISSUE THREAD

**Issue by salixzs** [JosefPihrt/Roslynator#541]
**Product and Version Used**: 
VS 2019, Roslynator.Analyzers 2.1.0-rc
.Net Core 3.0 preview 4, enforced C#8.0

**Steps to Reproduce**:
Make RCS1181 action "Error" in ruleset for solution/project.
Have `*.cs` file with documentation comments,
Build.

**Actual Behavior**:
`Error RCS1181 Replace comment with documentation comment` is added to error list.
![image](https://user-images.githubusercontent.com/3694770/56691799-79e56280-66e9-11e9-8dd7-9f0e830f5c50.png)

**Expected Behavior**:
Documentation comments are recognized and no error created.

**Comment by JosefPihrt** [comment]
I was not able to reproduce this bug from your screenshot. Could you please provide a code sample?

**Comment by salixzs** [comment]
[GitHub1181.zip](https://github.com/JosefPihrt/Roslynator/files/3118251/GitHub1181.zip)

Here is solution which I am getting this behavior.
Note, I am using Visual Studio 16.1.0 Preview 2 (VS 2019 Preview, latest) to develop/open this and compiling against .Net Core 3.0 Preview 4

**Comment by JosefPihrt** [comment]
I'm able to reproduce this bug. The reason is described [here](https://github.com/dotnet/roslyn/issues/10003).
