### ISSUE TITLE
Globally suppress an analyser isn't working

### ISSUE THREAD

**Issue by richardcox13** [JosefPihrt/Roslynator#549]
**Product and Version Used**: Roslynator 2019 (2.1.0, preview)

**Steps to Reproduce**: Include an expression using `await`. And in the global suppression file (included as a link into the project so it can be share through the solution):
```csharp
[assembly: SuppressMessage("Design", "RCS1090:Call 'ConfigureAwait(false)'.", Justification = "This does not do what you think it does, throwing it everywhere is not the solution")]
```
(I want this to be global, so not setting scope and target properties.)

This is a netcoreapp2.2 class library for xUnit.

**Actual Behavior**: I get the message to use `ConfigureAwait(false)`

**Expected Behavior**: RSC1090 is not shown.

**Comment by richardcox13** [comment]
PS. I really like Roslyator for refactoring: they are really useful.

The analysers rather conflict with my own opinionated approach...

**Comment by th0mk** [comment]
I don't think the issue is with `SuppressMessageAttribute`, but rather that RSC1090 isn't shown in the global suppression file. How would I go about globally suppressing this message?

**Comment by JosefPihrt** [comment]
In VS2017 you can globally suppress any analyzer in Tools > Options > Roslynator > Global Suppressions.

In VS2019 you can globally disable any analyzer by using ruleset file at `%LOCALAPPDATA%\JosefPihrt\Roslynator\VisualStudio\2019\roslynator.ruleset`. For example if you would like to disable RCS1090 your ruleset would look like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="roslynator.ruleset" ToolsVersion="16.0">
  <Rules AnalyzerId="Roslynator.CSharp.Analyzers" RuleNamespace="Roslynator.CSharp.Analyzers">
    <Rule Id="RCS1090" Action="None" />
  </Rules>
</RuleSet>
```

**Comment by th0mk** [comment]
My bad- the ruleset file opens in Visual Studio with just a list of analyzers, and it doesn't include the ones from Roslynator. When I edit the file itself it works fine. Thanks for helping out.

**Comment by gnzgo** [comment]
If I understand this correctly, you deprecated the global suppressions from a convenient menu in the VS options with checkboxes and a search functionality, to replace it with manually editing an XML file to type in a properly formatted entry for the specific suppression you wish to include, **and then** you must restart Visual Studio?

That's...well, it's not very convenient, I gotta say.

**Comment by JosefPihrt** [comment]
There is no need to edit ruleset manually. Visual Studio has built-in support for editing ruleset (including search functionality). You only have to add ruleset file to a solution and open it.
