### ISSUE TITLE
RCS1163: Suggests unused parameter for extension method `this` members

### ISSUE THREAD

**Issue by NickCraver** [JosefPihrt/Roslynator#55]
Here's an example:
```c#
public static IHtmlString InitClientTimings(this WebPageBase page) =>
    MiniProfiler.Current == null ? null : new HtmlString(ClientTimingHelper.InitScript);
```
While `page` isn't used in the method, it's not a thing to "fix" - can we please exclude `this` parameters from the 1163 analyzer?

**Comment by JosefPihrt** [comment]
Could you give me a code sample how this method is used? I've never come across an extension method that does not use its 'this' parameter.

**Comment by NickCraver** [comment]
@JosefPihrt yep, it's used in MVC views - so the extension point is for attachment, not use - e.g. `@this.InitClientTimings()` in a razor view.

**Comment by JosefPihrt** [comment]
I propose following solution to this issue:

* **this** parameter will be excluded from RCS1163.
* A new analyzer **UnusedThisParameter** will be introduced. This analyzer will report only unused **this** parameters.

Then you can disable latter analyzer (see [How to Customize Analyzers](http://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToCustomizeAnalyzers.md)).

**Comment by NickCraver** [comment]
+1 - that sounds like a good solution
