### ISSUE TITLE
Feature request: Analyzer and fix for List<T>.Select().ToList()

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#559]
I often, sadly, see the following construct in the codebase I maintain daily:

```csharp
List<AClass> foo = ...

// snip many lines of code...

return foo.Select(a => new AnotherClass(a)).ToList();
```

which can be rewritten as:

```csharp
return foo.ConvertAll(a => new AnotherClass(a));
```

thus saving a method call.

It would be useful to have this optimisation as a codefix.

**Comment by lechu445** [comment]
it can also be applied to arrays to use `Array.ConvertAll(array, a => new AnotherClass(a))`
