### ISSUE TITLE
Read-Only (RCS1169) false request to add

### ISSUE THREAD

**Issue by QuickC** [JosefPihrt/Roslynator#56]
The attached file suggests to have _workerTask  marked Read-Only. This causes and error it I let the read-only be added.  

-Kyle

`using System.Threading.Tasks;

namespace MachineTools
{
    internal class MachineController
    {
        protected enum machineMode
        {
            RESET = -1,
            STOP = 0,
            STEP = 1,
            START = 10
        }

        // constructor 
        public MachineController() => _workerTask = Task.Run(() => workerTask());

        // methods controlling sequence run
        public void Reset() { _runMode = machineMode.RESET; _runningUpdateMS = _idleUpdateMS; }
        public void Start() { _runMode = machineMode.START; _runningUpdateMS = _startDelayMS; }
        public void Step()  { _runMode = machineMode.STEP; _runningUpdateMS = _idleUpdateMS; }
        public void Stop()  { _runMode = machineMode.STOP; _runningUpdateMS = _idleUpdateMS; }

        // private methods
        protected void workerTask()
        {
            while (_machineRun)
            {
                switch (_runMode)
                {
                    case machineMode.START:
                        _runOperation();
                        break;

                    case machineMode.STEP:
                        _runOperation();
                        _runMode = machineMode.STOP;
                        break;

                    case machineMode.STOP:
                        break;

                    case machineMode.RESET:
                        _runOperation = _startOperation;
                        _runMode = machineMode.STOP;
                        break;
                }

                _workerTask.Wait(_runningUpdateMS);
            }
        }

        // utility method to print status
        protected internal virtual string Print() => "none";

        protected delegate void operationPointer();
        protected operationPointer _runOperation { get; set; }
        protected operationPointer _startOperation { get; set; }

        protected machineMode _runMode { get; set; } = machineMode.STOP;
        protected Task _workerTask;

        protected const bool _OFF = false;
        protected const bool _ON = true;
        protected readonly bool _machineRun = true;

        protected readonly int _idleUpdateMS = 50;
        protected int _runningUpdateMS = 50;
        protected readonly int _startDelayMS = 50;
    }
}`

**Comment by JosefPihrt** [comment]
Where does the error occur? I've tried to mark _workerTask as read-only and I see no error. Does it occur in some derived class?

**Comment by QuickC** [comment]
internal class OddMachine : MachineController
    {
        // constructor
        public OddMachine()
        {
            _startOperation = startOfCycle;
            _runOperation = startOfCycle;

            _offDelayTask = Task.Run(() => offDelayTask());
            _workerTask = Task.Run(() => workerTask());
        }

…

So yes it’s a derived class

Kyle

**Comment by JosefPihrt** [comment]
Thanks for the report @QuickC !
