### ISSUE TITLE
Would it be possible for analyzer to produce a build error on analyzer error

### ISSUE THREAD

**Issue by pgmagid** [JosefPihrt/Roslynator#566]
**Product and Version Used**: 
package id="Roslynator.Analyzers" version="2.0.0" targetFramework="net462" developmentDependency="true" 

**Steps to Reproduce**:
Introduce an error into the code that would cause the Roslynator Analyzer to show in Error in the Errors windows

**Actual Behavior**:
Error in show in the Errors window and in the code file, but a build a of the project completes successfully

**Expected Behavior**:
Error in show in the Errors window and in the code file and a build error is produced so that the build is marked as unsuccessful. This is the same behavior as I would get when using the Microsoft.CodeQuality.Analyzers package.

**Comment by JosefPihrt** [comment]
Hi,

Build output displays Warnings and Errors and build will fail on Error diagnostic and possibly on Warning diagnostic if TreatWarningsAsErrors is set. I tested it and it works in my case.

Could you provide a sample solution that I could use to reproduce the behavior you described?
