### ISSUE TITLE
RCS1190 (join string expression) doesn't correctly escape braces from interpolated strings

### ISSUE THREAD

**Issue by Ghost4Man** [JosefPihrt/Roslynator#567]
**Product and Version Used**: 
Roslynator 2.1.1
Visual Studio Community 2017 (15.9.13)

**Steps to Reproduce**:
Use the _RCS1190 (Join string expressions)_ refactoring on the following code:
```csharp
string str = "{1 + 2} = " + $"{1 + 2}";
```

**Actual Behavior**:
```csharp
string str = $"{1 + 2} = {1 + 2}";
```
The generated code would now output `3 = 3` (incorrectly).

**Expected Behavior**:
```csharp
string str = $"{{1 + 2}} = {1 + 2}";
```
`str` here correctly outputs `{1 + 2} = 3`. 

The braces from normal strings should be escaped when put into interpolated strings.

**Comment by JosefPihrt** [comment]
This bug is actually related to refactoring RR0078 not analyzer RCS1190.
