### ISSUE TITLE
RCS1188 with nullable reference type and bang operator

### ISSUE THREAD

**Issue by bddckr** [JosefPihrt/Roslynator#578]
**Product and Version Used**: `Roslynator.Analyzers`, version `2.1.0`.

**Steps to Reproduce**:
Create a auto-property of a non-nullable reference type and try to initialize the auto-property with `null!` to tell the compiler you'll ensure it's always not-null.

**Actual Behavior**:
```csharp
// RCS1188	Remove redundant auto-property initialization.
// Thus let's disable it until it knows about nullable reference types and `!`.
[System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1188:Remove redundant auto-property initialization.", Justification = "RCS1188 doesn't know about nullable reference types and the bang operator yet.")]
protected string TestProperty { get; private set; } = null!;
```

**Expected Behavior**:
```csharp
// No need to suppress any diagnostic because we don't get RCS1188.
protected string TestProperty { get; private set; } = null!;
```

**Comment by bddckr** [comment]
Thank you!

**Comment by John-Welch** [comment]
I'm seeing this identical issue with  `Roslynator.Analyzers`, version `2.3.0`. Has the fix made it through to that version?

**Comment by JosefPihrt** [comment]
@John-Welch Not yet, because `Roslynator.Analyzers` 2.x references Roslyn 2.x libraries which do not contain new features like "bang" operator (but it is compatible with VS 2017). New version of `Roslynator.Analyzers` that references Roslyn 3.x will be released soon.

**Comment by John-Welch** [comment]
Makes sense. I look forward to upgrading in due course. Thanks!
