### ISSUE TITLE
[Roslynator.Analyzers] Rules higher as RCS1235 are not shown in the project-explorer

### ISSUE THREAD

**Issue by TobiasSekan** [JosefPihrt/Roslynator#583]
**Product and Version Used**: 
Visual Studio Community 2019 Version 16.3.0 Preview 1.0
Roslynator.Analyzers 2.10

**Steps to Reproduce**:
1. Install NuGet package `Roslynator.Analyzers 2.10`
2. Expand the project analyzers in the project explorer
3. Expand `Roslynator.CSharp.Analyzers`
4. Scroll to the end of the expanded `Roslynator.CSharp.Analyzers` rules

**Actual Behavior**:
Rules higher as RCS1235 are not shown in the project-explorer

project explorer
![2019-08-13 07_58_21-DailyKanji](https://user-images.githubusercontent.com/17874713/62918544-36019080-bda0-11e9-9fc6-3bab65ea783b.png)

part of ruleset file
```xml
    <Rule Id="RCS1236" Action="Warning" />    <!-- RCS1236: Use exception filter -->
    <Rule Id="RCS1237" Action="Warning" />    <!-- RCS1237: Use bit shift operator -->
    <Rule Id="RCS1238" Action="Warning" />    <!-- RCS1238: Avoid nested ?: operators -->
    <Rule Id="RCS1239" Action="Warning" />    <!-- RCS1239: Use 'for' statement instead of 'while' statement -->
    <Rule Id="RCS1240" Action="Warning" />    <!-- RCS1240: Operator is unnecessary -->
    <Rule Id="RCS1241" Action="Warning" />    <!-- RCS1241: Implement non-generic counterpart -->
```

**Expected Behavior**:
Show all Roslynator rules in the project-explorer

**Comment by TobiasSekan** [comment]
Rule RCS1137 is not displayed too.

`<Rule Id="RCS1137" Action="Warning" />    <!-- RCS1137: Use bit shift operator -->`

**Comment by JosefPihrt** [comment]
These analyzers are not shown because they are not part of the package. Package Roslynator.Analyzers
is intentionally released at a slower pace which makes it more stable (less bugs).
