### ISSUE TITLE
Duplicate refactorings for RCS1169

### ISSUE THREAD

**Issue by nvmkpk** [JosefPihrt/Roslynator#592]
**Product and Version Used**: 2.1.3

**Steps to Reproduce**:
Just add a static field initialized inline. Screenshot shows it.

**Actual Behavior**:
Two refactoring options (with different text) show up (and VS has its own making it three). As shown in screenshot.

**Expected Behavior**:
Only one refactoring should be shown.

![image](https://user-images.githubusercontent.com/18663052/64190572-b158de00-ce44-11e9-9fb3-c23f388dced8.png)

**Comment by JosefPihrt** [comment]
It seems that that second suggestion comes from nuget package Roslynator.Analyzers that is installed side by side with Roslynator extension for VS. If that is true then my recommendation is to uninstall the package.

**Comment by nvmkpk** [comment]
That was the issue. But I wonder why the text is different between the two.

**Comment by JosefPihrt** [comment]
The text is different because I changed it :)

**Comment by nvmkpk** [comment]
OK. I added the nuget package so that these refactorings go with the repository and not require installing the extension. Other than this, are there any feature differences between the two?

**Comment by JosefPihrt** [comment]
New analyzers are first published as a part of vs extension. After some time the the nuget package is published. As of now, newest analyzers (RCS1236-41) are contained only in vs extension. This is the only difference.
