### ISSUE TITLE
Provide an Extension which contains only the Refactorings

### ISSUE THREAD

**Issue by felixhirt** [JosefPihrt/Roslynator#595]
It would be awesome if you could provide different versions of the Extension again (like in 2015 https://marketplace.visualstudio.com/items?itemName=josefpihrt.RoslynatorRefactorings), where one would only contain the refactorings but not the analyzers

**Comment by JosefPihrt** [comment]
There is no plan to publish an extension without analyzers. But that doesn't mean that you cannot enjoy Roslynator without analyzers. Please see this [post](https://github.com/JosefPihrt/Roslynator/issues/570#issuecomment-510030808) which explains how to disable analyzers (it is very easy).

**Comment by felixhirt** [comment]
That was exactly my scenario (analyzers come in by nuget)! Thanks a lot. Gona close this.
