### ISSUE TITLE
HasFlag code fix changes behavior

### ISSUE THREAD

**Issue by giulianob** [JosefPihrt/Roslynator#607]
**Product and Version Used**: 
2.2.0-rc

**Steps to Reproduce**:
RCS1096 

**Actual Behavior**:
```csharp
if (FenceBitmask.Value.HasFlag(PositionFlags.East | PositionFlags.West))
{
}
```
becomes 
```csharp
if ((FenceBitmask.Value & PositionFlags.East | PositionFlags.West) != 0)
{
}
```
which then it recommends to add parenthesis and becomes
```csharp
if (((FenceBitmask.Value & PositionFlags.East) | PositionFlags.West) != 0)
{
}
```

**Expected Behavior**:
The order of operations is wrong and this breaks the code. The original `HasFlag` should be converted to:
```csharp
if ((FenceBitmask.Value & (PositionFlags.East | PositionFlags.West)) != 0)
{
}
```

**Comment by qbert09** [comment]
HasFlag and the conversion you have are not equivalent.  Expected behavior: 

if ((FenceBitmask.Value & (PositionFlags.East | PositionFlags.West)) == (PositionFlags.East | PositionFlags.West))
{
}

We must also consider that you can have composite flags 

i.e. 
 public enum MyFlags
{
    A = 1,
    B = 2,
    C = 4,
    D = 8,
    DA = D | A
}

Example program that shows they do not work the same:

  public class Program
    {
        [Flags]
        public enum MyFlags
        {
            A = 1,
            B = 2,
            C = 4,
            D = 8
        }
        
        public static void Main(string[] args)
        {
            var x = MyFlags.A | MyFlags.C;
            
            //Your code goes here
            Console.WriteLine(x.HasFlag(MyFlags.A|MyFlags.C));
            Console.WriteLine( (x & (MyFlags.A|MyFlags.C)) != 0);
            Console.WriteLine( (x & (MyFlags.A|MyFlags.C)) == (MyFlags.A|MyFlags.C));
            
            x = MyFlags.A | MyFlags.D;
            
            //Your code goes here
            Console.WriteLine(x.HasFlag(MyFlags.A|MyFlags.C));
            Console.WriteLine( (x & (MyFlags.A|MyFlags.C)) != 0);
            Console.WriteLine( (x & (MyFlags.A|MyFlags.C)) == (MyFlags.A|MyFlags.C));
            
        }
    }
