### ISSUE TITLE
RCS1047 reported for IAsyncEnumerable

### ISSUE THREAD

**Issue by WilStead** [JosefPihrt/Roslynator#613]
**Product and Version Used**: 2.2.0

**Steps to Reproduce**: return an IAsyncEnumerable from a method with "-Async" in the name which is not itself async (e.g. return the result of another method call without awaiting on it).

```csharp
private async IAsyncEnumerable<T> LoadDataAsync() => await FetchAsync(); // no suggestion

public IAsyncEnumerable<T> GetDataAsync() => LoadDataAsync(); // RCS1047
```

**Actual Behavior**: RCS1047 suggestion to remove 'Async' suffix.

**Expected Behavior**: No suggestion.

**Comment by Alxandr** [comment]
Same with valuetask:

```csharp
            public ValueTask DisposeAsync()
                => _inner == null
                ? new ValueTask()
                : _inner.DisposeAsync();
```

**Comment by JosefPihrt** [comment]
@Alxandr `ValueTask` is handled properly:

https://github.com/JosefPihrt/Roslynator/blob/3f48e990cc85dd30a5fa94f7f085fa2668a9a5bb/src/Core/SymbolUtility.cs#L630

**Comment by Alxandr** [comment]
Wonder why I got it reported though?

**Comment by JosefPihrt** [comment]
I use your code sample with latest version. Which version do you use?

**Comment by Alxandr** [comment]
Latest version (as of last week at least). But on a much bigger code base, so it might have been affected by something else. If you can't repro it, it was probably something weird happening.
