### ISSUE TITLE
vscode LocationPaths version number breaks updates

### ISSUE THREAD

**Issue by divinebovine** [JosefPihrt/Roslynator#615]
**Product and Version Used**: 
josefpihrt-vscode.roslynator-2.2.0

When using the vscode plugin, you have to set the LocationPaths in the omnisharp.json file. The location paths include the version of the plugin, e.g. `"%USERPROFILE%/.vscode/extensions/josefpihrt-vscode.roslynator-2.2.0/roslyn/common",`. When the plugin updates the location path is no longer valid, which requires one to manually update their omnisharp.json.

It would be ideal to no have to set this in the omnisharp.json to begin with, but barring that, it would be preferable to not have to edit this file every time the plugin updates.

**Comment by JosefPihrt** [comment]
I understand that necessity to update omnisharp.json after each update of the extension is slightly annoying. I would like to get ride of it as much as you. But I don't know how do it (and if it is even possible.

**Comment by divinebovine** [comment]
Thanks for the reply. I get it and I appreciate what you're doing.

I dug around looking for the source code to the extension and I wasn't able to find it. I was considering poking around and seeing if i could come up with something. Can you point me to the source or is it not open?

**Comment by JosefPihrt** [comment]
https://github.com/JosefPihrt/Roslynator/tree/2019/src/VisualStudioCode/package

**Comment by JosefPihrt** [comment]
fixed with #623
