### ISSUE TITLE
Ability to configure global ruleset for analysers with Visual Studio Code extension

### ISSUE THREAD

**Issue by nizmow** [JosefPihrt/Roslynator#618]
**Product and Version Used**: 

Visual Studio Code 1.40.1
Roslynator extension 2.2.0

**Steps to Reproduce**:

N/A

**Actual Behavior**:
There's no way to configure rules globally. I believe if you're using Visual Studio (full) there's a preferences panel to enable and disable analyser rules. It doesn't seem possible to get this functionality with Visual Studio Code.

**Expected Behavior**:
We can configure analysers globally. :)

**Comment by JosefPihrt** [comment]
Hi,

I'm sorry for late answer.

Good news is that is it possible to configure rules globally with VS Code by using ruleset file at `%LOCALAPPDATA%\JosefPihrt\Roslynator\VisualStudioCode\roslynator.ruleset`.

For example if you would like to disable RCS1090 your ruleset would look like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="roslynator.ruleset" ToolsVersion="16.0">
  <Rules AnalyzerId="Roslynator.CSharp.Analyzers" RuleNamespace="Roslynator.CSharp.Analyzers">
    <Rule Id="RCS1090" Action="None" />
  </Rules>
</RuleSet>
```

**Comment by nizmow** [comment]
Thanks a lot for the response! I was going to offer a PR to update the docs but I see you've done that already. Really appreciated.
