### ISSUE TITLE
RCS1068 can be dangerous with NaN comparisons

### ISSUE THREAD

**Issue by wiz0u** [JosefPihrt/Roslynator#630]
Test expressions like:

    if (!(a >= b))
should not always be simplified into

    if (a < b)

when `a` or `b` can be `double.NaN`
(in which case, top test would be true, bottom test would be false)

I don't know whether the solution is to disable it for `double`/`float` comparisons, but the very minimum is to add a warning to [the documentation]( https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1068.md)

**Comment by wiz0u** [comment]
Looking at the fix, I'm not sure you really solved the issue...
What I meant is that a and/or b can be variables which at run time contains NaN... it is not simply a matter of comparing with the constant double.NaN ...

**Comment by JosefPihrt** [comment]
I think I fix the issue.

If the a/b is float/double type then it must have constant value that is not NaN.

**Comment by wiz0u** [comment]
Yes it's fine, I read too fast
