### ISSUE TITLE
Invalid refactoring suggestion (RCS1049) with nullable bool

### ISSUE THREAD

**Issue by Smoovsky** [JosefPihrt/Roslynator#631]
**Product and Version Used**: 
Roslynator for Visual Studio Code 2.3.0

**Steps to Reproduce**:
Snippet:
```csharp
if (!someCollection?.Any() == true)
....
```

**Actual Behavior**:
Intellisense suggests that it should be(RCS1049):
```csharp
if (someCollection?.Any() == false)
....
```

**Expected Behavior**:
Intellisense should reckon it's correct or change to something like:
```csharp
if (!someCollection?.Any() ?? false) // kinda make sense
....
```

**Comment by JosefPihrt** [comment]
The point of this analyzer is to make syntax more readable.

`if (someCollection?.Any() == false)`
is more readable than
`if (!someCollection?.Any() ?? false)`

So I don't think it's an invalid suggestion.

**Comment by Smoovsky** [comment]
> The point of this analyzer is to make syntax more readable.
> 
> `if (someCollection?.Any() == false)`
> is more readable than
> `if (!someCollection?.Any() ?? false)`
> 
> So I don't think it's an invalid suggestion.

Sry, I was confusing myself
