### ISSUE TITLE
RCS1221 code fix generates errors when applied to a nullable type

### ISSUE THREAD

**Issue by nalka0** [JosefPihrt/Roslynator#635]
**Using Roslynator 2017 (v2.0.0) and Roslyn refactorings 2017 (v1.9.2)**: 

```csharp
object value = 1d;
double? nullableDouble = value as double?;
if (nullableDouble == null)
{
    // do some stuff
}
```

**Actual Behavior**:
```csharp
object value = 1d;
if (!(value is double? nullableDouble)) // CS1003 : Syntax error, ':' expected + CS0103 : The name nulalbleDouble does not exist in the current context
{
    // do some stuff
}
```

**Expected Behavior**:
```csharp
object value = 1d;
if (!(value is double nullableDouble))
{
    // do some stuff
}
```

**Comment by JosefPihrt** [comment]
Fixed in #445.

Please install latest version (2.3.1).

It seems that you are using both Roslynator 2017 and Roslynator Refactorings 2017 at the same time. Because RR2017 is a subset of R2017 you should uninstall RR2017.
