### ISSUE TITLE
RCS1089: `+= 1` is not always equivalent to postfix increment

### ISSUE THREAD

**Issue by jhinder** [JosefPihrt/Roslynator#639]
```csharp
public class C {
    int i;
    
    public int M()
    {
        i += 1; // <-- equivalent to i++
        return i += 1; // <-- equivalent to ++i!
    }
}
```

[Sharplab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRjgOwMYwJYD2mqADgXpjBAsgDQAmIA1AD4ACAzAARsBMXAYS4BvALAAoLlK4UYMgNwTpXJdM4zKXALIAKAJSqpYycul4uTALxcAjPK4B6B1wA8qVFwgBHOHgBuUAA2EJowBDJMTIambADsMhbWdo7Obh7evgHBoeGReACE0QC+EkVAA=)

Whenever the value of the `+=` expression is taken, it's equivalent to a pre-increment, not a post-increment. When applying the code fix RCS1089, this difference can introduce subtle off-by-one bugs.

Version: 2.3.0

**Comment by JosefPihrt** [comment]
It's the same with `yield return`.

[SharpLab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQWoGYEBMcAwnAN5ZxVwCWAdgC60abVyXV4KK4A89DAHxwAsgAoAlByoVWbTokQIA7LThgAvHESp2cqgF8sBoA===)

Do you know of any other syntax where the pre-increment should be used?

**Comment by jhinder** [comment]
Passing arguments (`M(i += 1)`), array indexing (`a[i += 1]`) -- basically anything where the += expression is used as an expression and not just a statement, by the looks of it.

And of course it's not just the increment operator, this affects the decrement operator as well.

**Comment by JosefPihrt** [comment]
I came to this conclusion:

If an assignment expression is used as a part of statement, post-increment should be used:
`i += 1;` > `i++;`

Every other use of `i += 1` should be replaced with pre-increment.

Same logic applies to decrement operation.
