### ISSUE TITLE
RCS1156 should change (s == "") to (string.IsNullOrEmpty(s)) instead of (s?.Length == 0)

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [JosefPihrt/Roslynator#650]
RCS1156 suggests changing `s == ""` to `s?.Length == 0`, but it should instead change it to `string.IsNullOrEmpty(s)`.

.NET already implements this functionality with the IsNullOrEmpty functionality, I don't think it should be reimplemented using the Length field and a null check. The in-built function also increases readability.

**Comment by JosefPihrt** [comment]
That makes sense.

**Comment by davidnmbond** [comment]
@JosefPihrt - please revert this.  It is perfectly valid to compare a string JUST with string.Empty.

**Comment by levihb** [comment]
@davidnmbond fair point, but reverting it wouldn't fix the issue. The original suggestion was to change:

    s == ""

To:

    s?.Length == 0

Which is functionally identical to what I suggested to change it to. My suggestion was literally just a style change.

Maybe instead it should be split into two different checks? The following forms (and all different ways you could write them, and obviously their inverse):

    s == null || s != ""
    s?.Length == 0
    s == null || s.Length == 0

Should be suggested to switch to:

    string.IsNullOrEmpty(s)

And the second check of form:

    s == ""
    s == string.Empty

Should be suggested to change to:

    s.Length == 0

I think that should fix both problems. When I initially made this suggestion I was focused on the aesthetic change that I (nor @JosefPihrt it seems) noticed that  the original suggestion and the new one were both flawed.
