### ISSUE TITLE
Cannot activate the 'Roslynator' extension because it depends on an unknown 'ms-vscode.csharp' extension .

### ISSUE THREAD

**Issue by solrevdev** [JosefPihrt/Roslynator#653]
Cannot activate the 'Roslynator' extension because it depends on an unknown 'ms-vscode.csharp' extension.

It looks like the csharp extension has renamed itself from 'ms-vscode.csharp' to 'ms-dotnettools.csharp'

**Comment by JosefPihrt** [comment]
Fixed with #649 

Release is coming soon!

**Comment by solrevdev** [comment]
WOW, that was quick. thank you. This is an excellent extension by the way sir. 🙏

**Comment by JosefPihrt** [comment]
@solrevdev Thanks!

**Comment by n7commanderjohn** [comment]
thanks for the update!

**Comment by KristofKlein** [comment]
While waiting for this fix to be released: 
Open your VS Code Extensions folder. Find roslynator. Modify the package.json file. Find: 
"extensionDependencies": 
and change the value from ms-vscode.csharp to ms-dotnettools.csharp - should do the trick

**Comment by n7commanderjohn** [comment]
Thanks!

**Comment by TomasEkeli** [comment]
Just tagging onto @KristofKlein's comment: 

If you (like me) don't remember where the VS Code Extensions folder is: 
https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions

**Comment by JosefPihrt** [comment]
2.9.0 was just released!
