### ISSUE TITLE
RCS1077: Redundant replace First() with [0] on IList<>

### ISSUE THREAD

**Issue by ogix** [JosefPihrt/Roslynator#654]
**Product and Version Used**: 
Roslynator.Analyzers v2.3.0

RCS1077 rule suggests to replace `First()` call on `IList<>` type with `[0]` but internally `First() ` extension checks if type is `IList<>` and does the same. See here: https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/System.Linq/src/System/Linq/First.cs#L55

**Comment by JosefPihrt** [comment]
I understand that the runtime will try to cast the expression to `IList<T>`. But I think that it is still worthy to replace `x.First()` with `x[0]` because it is slightly faster, shorter and more readable because you can see that the expression has an indexer.

**Comment by ogix** [comment]
IMO `x.First()` is more readable when you have a LINQ method chain. And access by index is marginally faster - just doesn't do some additional checks.
I agree that for some people this rule is useful but I would like to have an option to disable this without other Linq optimizations.

**Comment by JosefPihrt** [comment]
Possible solution would be to introduce a new analyzer "UseElementAccess" that would cover two following cases:
```cs
x.First()
```
```cs
x[0]
```
and
```cs
x.ElementAt(1)
```
```cs
x[1]
```

Analyzer would be enabled by default (same as RCS1077) but you would have an option to disable it.

**Comment by ogix** [comment]
Sounds great!
