### ISSUE TITLE
Feature Request: IEnumerable to foreach refactoring

### ISSUE THREAD

**Issue by Lej** [JosefPihrt/Roslynator#657]
Feature Request: IEnumerable to foreach refactoring 

Expand lone IEnumerable to foreach loop:

From:

```
public void Bar()
{
    var numbers = new [] { 1, 2, 3 };
    numbers 
}
```

To:

```
public void Bar()
{
    var numbers = new [] { 1, 2, 3 };
    foreach (var number in numbers)
    {

    }
}
```

**Comment by xtqqczze** [comment]
This is not a refactoring, it is something different, like "Create Source Code Using Live Templates" from ReSharper:
<https://www.jetbrains.com/help/resharper/Templates__Applying_Templates__Creating_Source_Code_Using_Live_Templates.html>

@JosefPihrt Is this kind of feature in scope for Roslynator?

**Comment by JosefPihrt** [comment]
@xtqqczze you are right. This proposal not suitable as refactoring. It is rather a code snippet (or "live template").
