### ISSUE TITLE
NuGet doesn't have version 2.9.0

### ISSUE THREAD

**Issue by krisztiankocsis** [JosefPihrt/Roslynator#660]
**Product and Version Used**: 

2.9.0

**Steps to Reproduce**:

https://www.nuget.org/packages/Roslynator.Analyzers/

**Actual Behavior**:

The latest version is only 2.3.0.

**Expected Behavior**:

The latest version is 2.9.0.

**Comment by JosefPihrt** [comment]
Not every version is released as nuget package. Next version of nuget package will be probably 3.0 and it will reference Roslyn 3.x. I'm working on it.

Typical approach goes as follows:
1) add new features (new analyzers)
2) release extension for VS/VS Code
3) fix bugs
4) release nuget package

**Comment by krisztiankocsis** [comment]
Okay, got it.

**Comment by JosefPihrt** [comment]
https://www.nuget.org/packages/Roslynator.Analyzers/3.0.0-rc
