### ISSUE TITLE
RCS1113: Use 'string.IsNullOrEmpty' method is suggested incorrectly

### ISSUE THREAD

**Issue by danielabbatt** [JosefPihrt/Roslynator#662]
**Product and Version Used**: 
Roslynator 2019 2.9.0 extension

**Steps to Reproduce**:

with nullable enabled in a c#8.0 project

```csharp
if (connectedSystem.Credentials.Account == "")
```

connectedSystem is not nullable

connectedSystem.Credentials is not nullable

connectedSystem.Credentials.Account is string?

**Actual Behavior**:
The message below is suggested

Message	RCS1113	Use 'string.IsNullOrEmpty' method

**Expected Behavior**:
No suggestion to be made as the intention is to check that connectedSystem.Credentials.Account is not null but is empty. The same suggestion is made when string.Empty is used instead of "".

On looking at the documentation page, the second diagnostic message shows the same behaviour which also appears incorrect. 
```csharp
if (s == "") // RCS1113
{
}
```
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1113.md

I can see this was probably introduced as https://github.com/JosefPihrt/Roslynator/issues/650 which incorrectly assumes the intention of whether the original string being null is different to it being empty.

**Comment by davidnmbond** [comment]
Yes - #650 was a mistake.

**Comment by JosefPihrt** [comment]
@danielabbatt Thanks for the report!
