### ISSUE TITLE
cli fix --format uses spaces

### ISSUE THREAD

**Issue by keenam** [JosefPihrt/Roslynator#663]
Is there a way to keep tab when using --format?

**Product and Version Used**: Roslynator 0.1.0.4 (CLI)

**Steps to Reproduce**:

Roslynator.exe fix --format

**Original**:
```csharp
<tab>/// <summary>
```

**Actual Behavior**:
```csharp
<spaces>/// <summary>
```

**Expected Behavior**:
```csharp
<tab>/// <summary>
```

**Comment by JosefPihrt** [comment]
I have to say that from your post I don't have full understanding what you are trying to achieve. I would be better to provide real code sample.

Roslynator uses Roslyn API, namely [Formatter.FormatAsync](https://github.com/dotnet/roslyn/blob/3002f57904616f717d6eaee4a9f787b312df5d95/src/Workspaces/Core/Portable/Formatting/Formatter.cs#L83), to format document so I assume it should honor your settings (such as .editorconfig).

If you only want to format documents it is probably better to use [format](https://github.com/JosefPihrt/Roslynator/blob/master/docs/cli/format-command.md) command.

**Comment by keenam** [comment]
Thank you for your reply.
Hoping to clarify a few things, I tested on the following code (indented with tabs)

`RCS1101: Format documentation summary on multiple lines`

`Program.cs` that has `<tab>` for indent.
```
	/// <summary>Test multi-line summary: RCS1101</summary>
	class Program
	{
		static void Main(string[] args)
		{
		}
	}
```

1. CLI to fix solution not use `.editorconfig` file. I added RCS1101 to be an error in `.editorconfig`. 

`.editorconfig`
```
# NOTE: Requires **VS2019 16.3** or later

root = true

# Code files
[*.{cs,vb}]
indent_size = 4
indent_style = tab

# this doesn't have impact from cli
dotnet_diagnostic.RCS1101.severity = error

```

When the CLI is run, the error is not fixed. The solution file includes .editorconfig and I get an error from IDE - I can fix it from IDE.
```
Roslynator Command Line Tool version 0.1.0.4
Copyright (c) Josef Pihrt. All rights reserved.

Load solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
Done loading solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
Fix 'TestCli' 1/1
  No analyzers found to analyze 'TestCli'
Done fixing 'TestCli' in 00:00.38
```

I used a `.ruleset` file to indicate RCS1101 to be an error

2. RCS1101 fix indent problem
after running CLI to fix the summary to multi-lines
notice the formatting of comments, single space for indent.
**This is the same for both CLI and IDE**
```
	/// <summary>
 /// Test multi-line summary: RCS1101
 /// </summary>
	class Program
	{
		static void Main(string[] args)
		{
		}
	}
```

so, I added `--format` option to fix mis-aligned comments
```
Roslynator.exe fix --severity-level error TestCli.sln --format

Roslynator Command Line Tool version 0.1.0.4
Copyright (c) Josef Pihrt. All rights reserved.

Load solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
Done loading solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
Fix 'TestCli' 1/1
  Compile 'TestCli'
  Analyze 'TestCli'
  Found 1 diagnostic in 'TestCli'
  Fix 1 RCS1101 'Format documentation summary on multiple lines.'
  Compile 'TestCli' iteration 2
  Analyze 'TestCli'
  Format  'TestCli'
Done fixing 'TestCli' in 00:02.20
Done fixing solution 'C:\dev\rsolyntest\TestCli\TestCli.sln' in 00:02.20
```

Then the tabs are replaced with spaces. **Can I have my tabs back?**
```
    /// <summary>
    /// Test multi-line summary: RCS1101
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
```

3. tested fix and format separately.

after the fix, I am left with
```
	/// <summary>
 /// Test multi-line summary: RCS1101
 /// </summary>
	class Program
	{
		static void Main(string[] args)
		{
		}
	}
```

then I call `format` command which doesn't change anything but indicates the document is formatted: from verbose
```
Roslynator.exe format TestCli.sln -v d
Roslynator Command Line Tool version 0.1.0.4
Copyright (c) Josef Pihrt. All rights reserved.

Load solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
  Resolve   00:00.19  TestCli.csproj
Done loading solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
Analyze solution 'C:\dev\rsolyntest\TestCli\TestCli.sln'
  Analyze 'TestCli'
  Format 'Program.cs'
  Done analyzing 'TestCli'
```

**Comment by JosefPihrt** [comment]
Thanks for detailed explanation.

Now I understand where is the problem. This has nothing to do with CLI, it is just a bug in the analyzer RCS1101.
