### ISSUE TITLE
Update omnisharp.json when uninstalling Roslynator

### ISSUE THREAD

**Issue by JosefPihrt** [JosefPihrt/Roslynator#664]
Currently, references to Roslynator libraries are not removed from omnisharp.json when Roslynator extension is uninstalled.

Because uninstalled extensions are not removed from `.vscode/extensions`, Roslynator libraries are loaded even if extension has been uninstalled.

@AdrianWilczynski Would you be interested to do a PR? I think it would be a piece of cake for you.

**Comment by AdrianWilczynski** [comment]
Yeah, sure. I see there is an uninstall hook (https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook) and I can probably clean up `omnisharp.json`using it. I'll try it.

(Extensions do seem to get removed from `extensions` directory after uninstall but it seems to happen only after restarting VSCode. I guess even if that happens references pointing to not existing libraries might still be causing some trouble.)

**Comment by JosefPihrt** [comment]
Thanks!

**Comment by JosefPihrt** [comment]
Fixed with #666
