### ISSUE TITLE
RCS1102 Does not show in Code fixes options UI

### ISSUE THREAD

**Issue by ctolkien** [JosefPihrt/Roslynator#670]
**Product and Version Used**: 
Roslynator 2019 - 2.9.0

**Steps to Reproduce**:

![image](https://user-images.githubusercontent.com/515955/80433448-4b244c80-893a-11ea-8aa6-ebf1629e152b.png)

**Expected Behavior**:

RCS1102 should be in this list and able to be disabled?

**Comment by JosefPihrt** [comment]
Roslynator provides three main features:
1) Analyzers (+ usually code fix) (RCS....) - configurable through ruleset
2) Refactorings (RR....) - configurable through config file or VS Options
3) Code fixes for C# diagnostics (CS....) - configurable through config file or VS Options (your screenshot)

If you want to disable let's say RCS1102 you have to add following line to you ruleset file:
```xml
    <Rule Id="RCS1102" Action="None" />
```
My recommended way is to add ruleset file to your solution as a solution item. Then click on the file and you have built-in capacity to edit your ruleset.

Documentation:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md
