### ISSUE TITLE
Does Roslynator have a command-line interface that runs on mac or linux?

### ISSUE THREAD

**Issue by ikuosaito1989** [JosefPihrt/Roslynator#672]
Does Roslynator.CommandLine support anything other than Windows? Also, will the following .NET Core Global Tools be released to nuget?

https://github.com/JosefPihrt/Roslynator/commit/16d5b36a530e65aa5ad0c4a3a6163c287fed944f

**Comment by JosefPihrt** [comment]
Yes, .NET Core global tool will be released on nuget soon.

**Comment by ikuosaito1989** [comment]
Thank you! I'm looking forward to the next version!

**Comment by JosefPihrt** [comment]
https://www.nuget.org/packages/Roslynator.DotNet.Cli
