### ISSUE TITLE
Command-Line improvemnts to handle files more incrementally

### ISSUE THREAD

**Issue by ShadowXVII** [JosefPihrt/Roslynator#674]
**Product and Version Used**: 
Roslynator.commandline.0.1.0-rc3

**Steps to Reproduce**:
1. Create large project (i.e. huge classes) with many issues
2. Run fix

**Actual Behavior**:
This project has a metric tonne of classes (100Kb to 1MB .cs). It causes VS to crash when running code cleanup. 

The command line option for Roslynator works (thankfully!), but it really chugs -- no surprise with 200,000 fixes. I'm OK with waiting... but perhaps some batching logic might help write out completed fixes and not take up so much memory? It heavily pages -- easy taking up tens of GB of memory.

Or, an option to specify a single .cs file? I'll happily write a batch to do a file by file. I can leave it run overnight.

The analyze command wasn't too bad.

![image](https://user-images.githubusercontent.com/446329/81520618-242d3800-9388-11ea-990e-923d81aa3525.png)

Or, perhaps incremental saving so it doesn't have to re-process the same file twice should it be cancelled. Batching style.

**EDIT: Just noticed the parameter --batch-size**, though it still takes a massive amount of memory. Uses about 13GB for batches of 500.

**Expected Behavior**:
Lower memory usage.
OR
Incremental fix options (i.e. by .cs file, or folder)

**Comment by ShadowXVII** [comment]
Or, perhaps incremental saving so it doesn't have to re-process the same file twice should it be cancelled. Batching style.

**Comment by JosefPihrt** [comment]
I have potential fix in branch https://github.com/JosefPihrt/Roslynator/tree/cli/fixAllScope.

Could you test new option `-fix-all-scope document`?
