### ISSUE TITLE
Roslynator language is not equal to Visual Studio Code one in several places

### ISSUE THREAD

**Issue by Alvin-Seville** [JosefPihrt/Roslynator#675]
**Product and Version Used**: `16.0`

**Steps to Reproduce**:
![image](https://user-images.githubusercontent.com/42812113/81670934-b5d19e00-948b-11ea-84d7-632eddf1e7f3.png)

**Actual Behavior**:
Russian language in refactorings.

**Expected Behavior**:
English language in refactorings.

**Comment by JosefPihrt** [comment]
Roslynator supports only English. It is not localized to Russian or any other language.

**Comment by Alvin-Seville** [comment]
Please solve this problem somehow because they closed my Issue in their repository.

**Comment by JosefPihrt** [comment]
Your problem has nothing to do with Roslynator because Roslynator is NOT localized to Russian.

**Comment by Alvin-Seville** [comment]
I don't know but could it be Russian `Windows 10` problem?

**Comment by JosefPihrt** [comment]
I really don't know, sorry.
