### ISSUE TITLE
CLI: use severities defined in an .editorconfig file when fixing

### ISSUE THREAD

**Issue by BahKoo** [JosefPihrt/Roslynator#676]
**Product and Version Used**: 
Roslynator.CommandLine 0.1.0-rc3

When using `roslynator fix` for a solution that has rule severities defined in an .editorconfig file rather than a ruleset file, the severities are not considered when applying the fixes.

**Comment by JosefPihrt** [comment]
I agree, but I think that this behavior should be built into Roslyn.

**Comment by BahKoo** [comment]
Thanks for the response. I wasn't sure if the this was better handled in the roslynator code or yours. You can close the issue if you like.
