### ISSUE TITLE
Suggestion: Call 'HasFlag' instead of using a bitwise operation

### ISSUE THREAD

**Issue by xtqqczze** [JosefPihrt/Roslynator#679]
Reverse of [RCS1096](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1096.md). Calling `HasFlag` is more readable than using bitwise operations.

Since .NET Core 2.1, `Enum.HasFlag` is an JIT intrinsic, such that the JIT generates the same quality code as using bitwise operations.

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-2-1/

see also: #212

**Comment by xtqqczze** [comment]
Thanks!

**Comment by xtqqczze** [comment]
@JosefPihrt I would like to the new analyzer `ConvertBitwiseOperationToHasFlagCall`, does Roslynator have a public MyGet feed?

**Comment by JosefPihrt** [comment]
Roslynator current does not have MyGet feed but I will think about it.

Good news is that Roslynator 3.0 will be released soon.

**Comment by JosefPihrt** [comment]
If you don't want to wait it is simple to install latest bits:

1) Pull repo
2) Run `tools/build.cmd`
3) (Uninstall extension from VS)
4) Run `src/VisualStudio/bin/Release/Roslynator.VisualStudio.vsix`

**Comment by JosefPihrt** [comment]
Roslynator 3.0.0 has been released.

**Comment by xtqqczze** [comment]
How does one enable `RCS1096i`?

**Comment by JosefPihrt** [comment]
Just add to your ruleset:
```xml
<Rule Id="RCS1096i" Action="Info" />
```
Because "analyzer option" is a yes/no switch it doesn't matter if you set Hidden, Info, Warning or Error. For readability purposes it is good to specify same action as its parent analyzer which is Info for RCS1096.

If you would like to set action to Warning you have to add two lines:
```xml
<Rule Id="RCS1096" Action="Warning" />
<Rule Id="RCS1096i" Action="Warning" />
```

**Comment by xtqqczze** [comment]
I have now successfully enabled `RCS1096i` in Visual Studio, but messages are shown under the code `RCS1096` with the corresponding description: "Convert 'HasFlag' call to bitwise operation". Diagnostics of the form `ConvertHasFlagCallToBitwiseOperationAnalysis` are still showing as well.

**Comment by JosefPihrt** [comment]
`RCS1096i` is not analyzer, it is "analyzer option" for analyzer `RCS1096`. If you enable `RCS1096i` you will essentially invert behavior of analyzer `RCS1096`. In both cases diagnostic will be reported as `RCS1096`.

I'm not sure what does this mean:
> Diagnostics of the form ConvertHasFlagCallToBitwiseOperationAnalysis are still showing as well

**Comment by xtqqczze** [comment]
When `RCS1096i` is enabled, diagnostics are reported for both the original diagnostic and the inverse, which are reported as "RCS1096" with the original message in the diagnostic list.

**Comment by JosefPihrt** [comment]
I understand, it's a bug.
