### ISSUE TITLE
Failed to use Roslynator CLI with VS Code extension

### ISSUE THREAD

**Issue by deitry** [JosefPihrt/Roslynator#682]
**Product and Version Used**: 
Latest VS Code extension + Roslynator.CommandLine NuGet package

**Steps to Reproduce**:
Run
```posh
Roslynator.exe fix --msbuild-path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin" .\MySolution.sln --analyzer-assemblies C:\Users\User\.vscode\extensions\josefpihrt-vscode.roslynator-2.9.0\roslyn\analyzers\
```
Same with `Roslynator.exe analyze`

**Actual Behavior**:
```log
Roslynator Command Line Tool version 0.1.0.4
Copyright (c) Josef Pihrt. All rights reserved.

Load solution '...\MySolution.sln'
Done loading solution '...\MySolution.sln'
Fix 'MyProj' 1/3
The type initializer for 'Roslynator.Formatting.CSharp.DiagnosticDescriptors' threw an exception.
```

**Expected Behavior**:
Not to throw exception

**Comment by deitry** [comment]
Managed to run both after rebuild from source.

As I saw in the other thread, 
> Not every version is released as nuget package

so I close this one.

Thanks for the tool!

**Comment by JosefPihrt** [comment]
New version of CLI has been released: https://www.nuget.org/packages/Roslynator.CommandLine/0.1.0
