### ISSUE TITLE
Wrong RCS1158 with static readonly field using type parameter

### ISSUE THREAD

**Issue by WebFreak001** [JosefPihrt/Roslynator#684]
**Product and Version Used**: 
VSCode Roslynator extension v3.0.0

**Steps to Reproduce**:
I have the following code and get an RCS1158 warning for the "Scope" field saying "Static member in generic type should use a type parameter".

```csharp
public interface IBar<T>
{
}

public class ScopedFoo<T> : IBar<T>
{
	public static readonly string Scope = typeof(T).Name; // <-- RCS1158
}
```

**Expected Behavior**:

I think no RCS1158 should be emitted, I am using the generic type parameter after all.

**Comment by JosefPihrt** [comment]
Thank you for your post.

I think that this is a rare case and it is fine to suppress it:
```cs
using System.Diagnostics.CodeAnalysis;

public interface IBar<T>
{
}

public class ScopedFoo<T> : IBar<T>
{
    [SuppressMessage("Design", "RCS1158", Justification = "<Pending>")]
    public static readonly string Scope = typeof(T).Name;
}
```

**Comment by kiwiant** [comment]
Not so rare as also a problem with constants.
```
public class ScopedFoo<T> : IBar<T>
{
    public const string ProviderName = "MyProvider";
}
```

**Comment by code1line** [comment]
The sam here - with constants.

**Comment by glen-84** [comment]
And:

```cs
public static ModuleName ModuleName { get; } = T.ModuleName;
```

@JosefPihrt Would you reconsider this?

**Comment by JosefPihrt** [comment]
@glen-84  I tried your code snippet but I'm getting CS0704. Could you provide working sample (including enclosing class)?


Please consider opening new issue:
> ![image](https://github.com/JosefPihrt/Roslynator/assets/11931318/f6197947-432e-4eb6-8b2c-5327357fac6c)
