### ISSUE TITLE
Question: best way to call from code

### ISSUE THREAD

**Issue by dszryan** [JosefPihrt/Roslynator#689]
I have generated some code during the build. 

Instead of reinventing the wheel to make the document readable, I want to use this library to process the generated document/s and apply simple fixes like (not the exhaustive list):

- fix usings (sort. remove unused, remove duplicates)
- line wrap the code
- one line auto-properties

What is the best way to do this?
to clarify - more interested in how to leverage the code available/written in the many libraries.

**Comment by JosefPihrt** [comment]
You can use [Roslynator CLI](https://www.nuget.org/packages/Roslynator.CommandLine/) to apply fixes. CLI supports filtering by projects. It does not support filtering by files, but it can be implemented in a future. Working sample can be found [here](https://github.com/JosefPihrt/Roslynator/blob/master/tools/_fix.cmd).

**Comment by dszryan** [comment]
thanks
