### ISSUE TITLE
Warning	AD1000 with Visual Studio 2019 16.4.10

### ISSUE THREAD

**Issue by vivekkpatel** [JosefPihrt/Roslynator#690]
I've Installed Visual Studio extension (Roslynator 2019) nothing else, I can't upgrade Visual studio due to bug in Latest Version. 

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD1000	An instance of analyzer Roslynator.Formatting.UseCarriageReturnAndLinefeedAsNewLineAnalyzer cannot be created from C:\USERS\RYZEN2600X\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_ADC6585F\EXTENSIONS\ZLTULXVW.DQG\Roslynator.Formatting.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..			1	Active	Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
-----
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

-----
![image](https://user-images.githubusercontent.com/60865708/87304542-9c53dd80-c532-11ea-8502-da484e611d67.png)

**Comment by JosefPihrt** [comment]
Roslynator was moved to Roslyn 3.5.0 (and thus VS 16.5.x). I was necessary to be able to implement "nullable reference types" feature.

If you cannot install latest VS version then only solution seems to be to wait till the bug is fixed by Microsoft.

This is external issue which I cannot affect in any way, sorry.

**Comment by vivekkpatel** [comment]
The Problem is I have 2 PC both are using Visual Studio 2019 16.4.x with identical config but Roslynator is working on one PC and not working on another

**Comment by vivekkpatel** [comment]
Just Upgraded to vs 16.5.x, it's working on both PC now,
