### ISSUE TITLE
How does the Roslynator.DotNet.Cli fetch analysers from the ruleset?

### ISSUE THREAD

**Issue by mabez** [JosefPihrt/Roslynator#692]
**Product and Version Used**: Roslynator.DotNet.Cli 0.1.0

**Steps to Reproduce**:
```
roslynator analyze Solution.sln
```

**Actual Behavior**: 
```
Analyze '***.Application' 3/13
  No analyzers found to analyze 'WebMotors.ComprarVeiculos.Application'
  Authorization\Commands\HeaderAuthorization.cs(113,27): warning CS0109: O membro "HeaderAuthorization.ToString()" não oculta um membro acessível. A palavra-chave new não é necessária.
```

*No analyzers found* is the problem.

**Expected Behavior**: Apply an analyzer as the `Roslynator.Analyzers` or `Microsoft.CodeAnalysis.FxCopAnalyzers` preferably using a custom ruleset file.

How can I dot it?

**Comment by JosefPihrt** [comment]
Roslynator CLI will use analyzers that are referenced in csproj as `PackageReference`. It will not use analyzers that are part of VS extensions. You have to specify these analyzers using option `--analyzer-assemblies`. Working sample can be found [here](https://github.com/JosefPihrt/Roslynator/blob/master/tools/_fix.cmd).

**Comment by mabez** [comment]
Thanks, @JosefPihrt by the explanation.
In my case, I want to run the analyzers in a console CLI to get the alerts on CI.

My docker container doesn't will have a visual studio configuration, but your answer helped me to learn how to do it.

```
dotnet msbuild Solution.sln -v:m -m -t:Build -p:Configuration=Debug;RunCodeAnalysis=true;CodeAnalysisRuleSet=MyRuleset.ruleset
```

At the moment that command attends but I will want to use the `Roslynator.DotNet.Cli` features when I have more time, sure.
