### ISSUE TITLE
Do no suggest to use method group instead of lambda

### ISSUE THREAD

**Issue by jjavierdguezas** [JosefPihrt/Roslynator#694]
see this thread on Twitter
https://twitter.com/buhakmeh/status/1284148929714585607?s=19
specially the answers of David Fowler
https://twitter.com/davidfowl/status/1284325087693295617?s=19

**Comment by jjavierdguezas** [comment]
maybe @davidfowl could tell more about this

**Comment by JosefPihrt** [comment]
I tried some sample code on SharpLab and it seems that static method call are cached even if they are method groups.

**Comment by jjavierdguezas** [comment]
see [this SharpLab example](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGAdAGQEsA7ARwG4BYAKBpQGYsAmDAYQwG8aMetGcAbBmAB7EQBsMAFTiwAFCRgYAHgEpO3XlpQB2FRgB8GbGirUtAX009rfLABYMAWTnqu5rbwBuEBPoC8GMRwAO4YigDaJgC6Zp68tlo+flDYGIHKuADqABaIcHLK6UYy8mqqcfEYyRhQLBnZeQgFpTAVtlbUFkA=)

![image](https://user-images.githubusercontent.com/13673443/88683729-672fb980-d0f4-11ea-9d11-bc95190e2484.png)

See how
```csharp
var s1 = x.Where(x => Test(x));
```

Is transformed to
```csharp
Enumerable.Where(source, <>c.<>9__1_0 ?? (<>c.<>9__1_0 = new Func<int, bool>(<>c.<>9.<M>b__1_0)));
```
it caches the `Func`

but
```csharp
var s2 = x.Where(Test);
```

is transformed to
```csharp
Enumerable.Where(source, new Func<int, bool>(Test));
```
creating a `Func` always

**Comment by JosefPihrt** [comment]
It seems reasonable to disable this analyzer by default.
