### ISSUE TITLE
Use `is not null` instead of `!= null`

### ISSUE THREAD

**Issue by xtqqczze** [JosefPihrt/Roslynator#696]
<strike>In C# 7.0, where `foo` is reference type, the following fixes:

`foo == null` -> `foo is null`
`foo != null` -> `!(foo is null)`</strike>

In C# 9.0 (in preview), the following fix:

`foo != null` -> `foo is not null`

*Note: The Roslyn compiler ensures the behavior of the `==` and `is` operators is identical ([proof](https://sharplab.io/#v2:EYLgdgpgLgZgHgGiiAhgZwLYB8ACAmARgCgcBmAAn3IGFyBvI8p84Ae1YBtyBZAgClbAAVhADGUcnACU5ALwA+SeQCWacmACuHDgG4iASDaceeAcLETpcxXDmz1W3UQC+QA=)), unless the equality operators `==` and `!=` are overidden.*

**Comment by JosefPihrt** [comment]
Duplicate of #458 (partially)

**Comment by xtqqczze** [comment]
@JosefPihrt Updated to no longer duplicate #458

**Comment by JosefPihrt** [comment]
Where is the `is not null` feature specified?

**Comment by xtqqczze** [comment]
https://github.com/dotnet/csharplang/blob/master/proposals/patterns3.md

**Comment by JosefPihrt** [comment]
@xtqqczze thanks!

**Comment by Youssef1313** [comment]
Roslyn already has an analyzer with a codefix to that.

**Comment by JosefPihrt** [comment]
fixed with 432a8fea3147447536dbb8fac47598ad1db68158
