### ISSUE TITLE
Code inside conditional-compilation directive is ignored

### ISSUE THREAD

**Issue by xtqqczze** [JosefPihrt/Roslynator#697]
Code inside a conditional-compilation directive is ignored when the expression is not true at compile time.

For example, analyzers do not locate diagnostics inside `#if UNIX` etc.

**Comment by JosefPihrt** [comment]
1) If you are doing fixes from VS you can define constant in Properties > Build > General > Conditional compilation symbols. But this approach is not convenient if you have to define constant in multiple projects.

2) Or you can define constant in csproj or Directory.Build.props file:

```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <DefineConstants>UNIX</DefineConstants>
</PropertyGroup>
```

3) Other option is to run [Roslynator CLI](https://www.nuget.org/packages/Roslynator.CommandLine/) command `fix` with defined constant:

```
roslynator fix MySolution.sln" --properties DefineConstants=UNIX
```
