### ISSUE TITLE
Async suffix should be allowed on any awaitable methods, not just async methods

### ISSUE THREAD

**Issue by nvmkpk** [JosefPihrt/Roslynator#7]

**Comment by arabelaa** [comment]
This can be done quite easy in the **MethodDeclarationDiagnosticAnalyzer** class by adding some additional checks (see print screen)
![captureasyncchage](https://cloud.githubusercontent.com/assets/4593697/16950947/612d3f04-4dcb-11e6-813a-df6f15bdfc28.JPG)

**Comment by JosefPihrt** [comment]
Current behaviour of the analyzer 'RCS1046' is that it reports an async method whose name does not end with 'Async'. But the analyzer does not check if the method actually contains 'await' expression. I will fix it.
