### ISSUE TITLE
RCS1221 code fix introduces redundant blank link

### ISSUE THREAD

**Issue by xtqqczze** [JosefPihrt/Roslynator#702]
**Product and Version Used**: Roslynator 2019 3.0.0

**Code sample**:

```csharp
if (asyncResult == null)
{ }

PowerShellAsyncResult psAsyncResult = asyncResult as PowerShellAsyncResult;

if ((psAsyncResult == null) ||
    (psAsyncResult.OwnerId != InstanceId) ||
    (psAsyncResult.IsAssociatedWithAsyncInvoke != true))
{ }
```

**Actual Behavior**:
```csharp
if (asyncResult == null)
{ }


if ((!(asyncResult is PowerShellAsyncResult psAsyncResult)) ||
    (psAsyncResult.OwnerId != InstanceId) ||
    (psAsyncResult.IsAssociatedWithAsyncInvoke != true))
{ }
```

**Comment by xtqqczze** [comment]
@JosefPihrt I am so sorry, it appears my report was mistaken and it was IDE0019 not RCS1221 introducing the redundant blank line. Since you closed this with a commit, were blank lines being introduced in other cases?

**Comment by JosefPihrt** [comment]
I assumed that bug is present because there were no tests with empty line between local declaration and if statement. Anyway, I found other bug that caused a comment between local declaration and if statement to be deleted when a code fix is applied. So I definitely fixed that one.
