### ISSUE TITLE
Any way to not rename the method Xxx -> XxxAsync for CS4032 fix?

### ISSUE THREAD

**Issue by johnknoop** [JosefPihrt/Roslynator#703]
When I introduce an await statement inside a previously synchronous method, I use the roslynator fix "Make method async" (CS4032) to change it from `void` to `async Task`. It's super handy. But it also suffixes the method with "Async", which isn't at all what I want. Especially since I use this fix a lot in my unit tests, and I don't want them to be named "AxxAsync".

Is there any way I can turn this off?

**Comment by JosefPihrt** [comment]
Roslynator provides a lot of code fixes for CS diagnostics (full list is [here](https://github.com/JosefPihrt/Roslynator/blob/master/src/CodeFixes/README.md)). But fix for CS4032 is actually from Microsoft.

**Comment by johnknoop** [comment]
Oh, I see. Thanks anyway!

**Comment by johnknoop** [comment]
Note to anyone arriving here by googling the same thing:

I found this issue in the roslyn repo, and I added a comment to it:

https://github.com/dotnet/roslyn/issues/20348
