### ISSUE TITLE
RCS1097 - Don't trigger for value types

### ISSUE THREAD

**Issue by krisztiankocsis** [JosefPihrt/Roslynator#713]
**Product and Version Used**: 

Roslynator.Analyzers 3.0.0-rc (NuGet)

**Steps to Reproduce**:

See below.

**Actual Behavior**:
```csharp
var number = 10;
var text = $"'{number.ToString()}'"; // TRIGGERS RCS1097
```

**Expected Behavior**:
```csharp
var number = 10;
var text = $"'{number.ToString()}'"; // DOESN'T TRIGGER RCS1097
```

May be a configuration setting should be enough.
Rationale: For value types, in some places, calling ToString() will prevent boxing, so performance won't decrease.

**Comment by JosefPihrt** [comment]
RCS1097 is triggered only for references types:

https://github.com/JosefPihrt/Roslynator/blob/27a7678f3203ee6430037ee7b4edeaa55c7b801a/src/Analyzers/CSharp/Analysis/RemoveRedundantToStringCallAnalysis.cs#L59

You probably see IDE0071.
