### ISSUE TITLE
RCS1151 incorrectly triggers for explicit interface implementations

### ISSUE THREAD

**Issue by pgrm** [JosefPihrt/Roslynator#714]
**Product and Version Used**: 

```xml
    <PackageReference Include="Roslynator.Analyzers" Version="2.3.0" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="1.0.0-beta" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="1.0.0-rc" />
```

**Steps to Reproduce**:

For instance if you want to add an extension using [`void IDbContextOptionsBuilderInfrastructure.AddOrUpdateExtension<TExtension>(TExtension extension)`](https://github.com/dotnet/efcore/blob/release/5.0/src/EFCore/DbContextOptionsBuilder.cs#L622) and you only have an object of type `DbContextOptionsBuilder`, which implements the interface, but you still need to explicitly cast the the object to get access to the method.

**Actual Behavior**:
```csharp
        public static DbContextOptionsBuilder UseCustomFeatures(this DbContextOptionsBuilder optionsBuilder)
        {
            ((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(new CustomExtension()); // RCS1151

            return optionsBuilder;
        }
```

**Expected Behavior**:

no RCS1151 reported

**Comment by JosefPihrt** [comment]
I cannot reproduce the bug using this simple example:
```cs
public interface IC
{
    void M();
}

class C : IC
{
    void IC.M()
    {
        var x = new C();

        ((IC)x).M();
    }
}
```
It seems to be fixed.

**Comment by pgrm** [comment]
@JosefPihrt I can confirm that your sample code works for me, but when I use EF Core with [DbContextOptionsBuilder](https://github.com/dotnet/efcore/blob/release/5.0/src/EFCore/DbContextOptionsBuilder.cs#L622) it's still broken

**Comment by JosefPihrt** [comment]
Maybe I can try your code sample. Which nuget packages are necessary to build it?

P.S. It seems that you reference version 2.3.0. There is newer version 3.0.0-rc

**Comment by pgrm** [comment]
@JosefPihrt I tried testing the 3.0.0-rc, but I got a bunch of `TypeInitializationException` on every project I tried to build with it:

![image](https://user-images.githubusercontent.com/713456/91653223-e7a05c00-ea9e-11ea-9194-0a2e13f2bde3.png)

**Comment by JosefPihrt** [comment]
Roslynator 3.0 references Roslyn 3.5 which means that you have to install Visual Studio version that uses at least Roslyn 3.5.

Best solution would be to install latest VS version.

**Comment by pgrm** [comment]
@JosefPihrt I'm not using VS, I'm on MacOS with rider and .net core - I have `.NET Core SDK (3.1.401)`

**Comment by pgrm** [comment]
@JosefPihrt it took a while, but here is a repo with a Dockerfile which reproduces the issue (also can be reproduced on my MacOS setup) https://github.com/pgrm/code-analyzers-tests

**Comment by JosefPihrt** [comment]
Regardless of the IDE, TypeInitializationException is usually caused by the fact the IDE provides Roslyn libraries with lower version that is required by the analyzers (in this case 3.5.0).

**Comment by JosefPihrt** [comment]
Thanks for the sample repo! I'm able to reproduce the bug.
