### ISSUE TITLE
RCS1201 doesn't consider the return value for method chaining

### ISSUE THREAD

**Issue by pgrm** [JosefPihrt/Roslynator#715]
**Product and Version Used**: 

```xml
    <PackageReference Include="Roslynator.Analyzers" Version="2.3.0" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="1.0.0-beta" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="1.0.0-rc" />
```

**Steps to Reproduce**:

For instance when using EF Core entity type builder to create 2 indexes:

**Actual Behavior**:
```csharp
    public class ExampleEntityConfig : IEntityTypeConfiguration<ExampleEntity>
    {
        public void Configure(EntityTypeBuilder<ExampleEntity> builder)
        {
            builder.HasIndex(x => new { x.Id1 }); // RS1201
            builder.HasIndex(x => new { x.Id2 }).IsUnique();
        }
    }
```

after applying the auto fix, I get the following code (which doesn't compile):

```csharp
    public class ExampleEntityConfig : IEntityTypeConfiguration<ExampleEntity>
    {
        public void Configure(EntityTypeBuilder<ExampleEntity> builder)
        {
            builder.HasIndex(x => new { x.Id1 }); // RS1201
                .HasIndex(x => new { x.Id2 }).IsUnique();
        }
    }
```

**Expected Behavior**:

no RCS1201 should take the return value into account and only trigger if it's the same

**Comment by JosefPihrt** [comment]
I cannot reproduce this bug. Could you please provide code example that does not require EF?

Anyway, this analyzer does check if the return type is the same:
https://github.com/JosefPihrt/Roslynator/blob/716beb608db786db5d02ff5ee2616bc1f320b390/src/Common/CSharp/Analysis/UseMethodChaining/MethodChainingWithoutAssignmentAnalysis.cs#L40

**Comment by pgrm** [comment]
maybe it's something weird with the EF Core libraries? - same issue is here: https://github.com/JosefPihrt/Roslynator/issues/714 - your test example works, but for the EF Core library it's broken.

I'll try to reproduce it on an empty project

**Comment by pgrm** [comment]
@JosefPihrt it took a while, but here is a repo with a Dockerfile which reproduces the issue (also can be reproduced on my MacOS setup) https://github.com/pgrm/code-analyzers-tests

**Comment by JosefPihrt** [comment]
Thanks for the sample repo! I'm able to reproduce the bug.
