### ISSUE TITLE
Wrong RCS1182 behaviour when using the "new" keyword in Roslynator 2017

### ISSUE THREAD

**Issue by Satiriques** [JosefPihrt/Roslynator#717]
**Product and Version Used**: 
Visual Studio 2017 Professional Version 15.9.11
Roslynator 2017 Version 2.1.1

**Steps to Reproduce**:
```csharp
class Car : Vehicule, IVehicule
{
	new public void Start()
	{
		Console.WriteLine("Car is Starting");
	}
}

class Vehicule : IVehicule
{
	public void Start()
	{
		Console.WriteLine("Vehicule is Starting");
	}
}

interface IVehicule
{
	void Start();
}
```

**Actual Behavior**:
On the Car definition, the recommendation is RCS1182: Interface 'IVehicule' is already implemented by 'Vehicule'.

**Expected Behavior**:
No recommendation since the new keyword will hide both the Vehicule's and IVehicule's `Start()` method. In this case, the IVehicule interface is not redundant.

Works fine in roslynator 2019 Version 3.0.0 with Visual Studio 2019 Preview Version 16.6.0 Preview 6.0.

**Comment by JosefPihrt** [comment]
I'm sorry, but Roslynator 2017 is no longer in development.
