### ISSUE TITLE
Up2date Nuget vs VSX

### ISSUE THREAD

**Issue by silvioboehme** [JosefPihrt/Roslynator#72]
Hi!

The VSX extensions (for 2015+2017) in the marketplace matches the github released version, and are up2date.
But the NuGet package (analyzer only) is currently available as 1.2 (stable) or 1.3 (preview), but both are outdated.

Whats your release strategy for VSX vs NuGet?

I'm asking, because we use all analyzers only as NuGet packages.

Thanks
Silvio

**Comment by JosefPihrt** [comment]
Hi, I have a plan to release another preview shortly and final 1.3 in ~2 weeks.

**Comment by JosefPihrt** [comment]
@silvioboehme RC is out.

**Comment by JosefPihrt** [comment]
Fix #72: http://www.nuget.org/packages/Roslynator.Analyzers/1.3.0

**Comment by silvioboehme** [comment]
Sorry to reopen this one, but 3 month later I have the same effect.
VSX is available for the latest Version, but NuGet is 3 Month old (v 1.4.0).

Is it possible to release the Nuget version also frequently as the VSX version?
