### ISSUE TITLE
RCS1096i does not work

### ISSUE THREAD

**Issue by webczat** [JosefPihrt/Roslynator#724]
I am using both roslynator vscode extension version current latest, and roslynator analyzers nuget version 3.0.0.
Tried to modify RCS1096 to prefer using HasFlag over bitwise operations. I tried enabling RCS1096i in a project specific ruleset file or editorconfig, but in
both cases it does not seem to have any effect. I still get suggestion to use bitwise operations.

**Comment by JosefPihrt** [comment]
I'm sorry, this bug was fixed but new version has not been released yet.

Good news is that new veersion will be released in a few days.
