### ISSUE TITLE
What is Roslynator.Analyzers.Unity?

### ISSUE THREAD

**Issue by Gryhyphen** [JosefPihrt/Roslynator#725]
This on NuGet: https://www.nuget.org/packages/Roslynator.Analyzers.Unity/2.1.0

When I click on the links, it takes me here. Roslynator looks like an awesome linting / analyzer tool, but where is the documentation for Unity? There are like 4 issues that mention Unity here, and at least 1 deleted branch. Although some issues are closed, I can't figure out their resolution / associated rules.

Can someone explain the history of Roslynator's support for Unity and what it's current state is?

**Comment by JosefPihrt** [comment]
Roslynator.Analyzers.Unity is not official Roslynator package. Official packages are listed [here](https://www.nuget.org/profiles/jpihrt).

**Comment by Gryhyphen** [comment]
Thank you! I was getting pretty confused.
