### ISSUE TITLE
"Use exception filter" (RCS1236) should also detect the opposite term

### ISSUE THREAD

**Issue by tsahi** [JosefPihrt/Roslynator#731]
**Product and Version Used**: 
2019 3.0

**Steps to Reproduce**:
consider the follwoing code
```cs
try
{
}
catch (Exception ex)
{
    if (ex is InvalidOperationException)
    {
        throw;
    }

    return;
}
```
**Actual Behavior**:
Possible refactoring is not detected

**Expected Behavior**:
The following refactoring should be suggested
```csharp
try
{
}
catch (Exception ex) when (!(ex is InvalidOperationException))
{
    return;
}
```

**Comment by JosefPihrt** [comment]
Actually, the code fix is suggested:

![UseExceptionFilter](https://user-images.githubusercontent.com/11931318/97633519-83fdc500-1a34-11eb-85e4-ce67a2abc00d.png)
