### ISSUE TITLE
RCS1203: "Use AttributeUsageAttribute" only triggers if the class name ends with "Attribute"

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#733]
**Product and Version Used**:

Microsoft Visual Studio Enterprise 2019
Version 16.7.6

Roslynator 2019
Version 3.0.0

**Steps to Reproduce**:

Create a class that derives from `Attribute` or a subclass, but **do not name the new class ending with the text "Attribute"**. Note that RCS1203 is not suggested.

**Actual Behavior**:
```csharp
// no RCS1203
public class MyClass1 : Attribute
{

}

// RCS1203
public class MyClass2Attribute : Attribute
{

}
```

**Expected Behavior**:
```csharp
// RCS1203 should be suggested here
public class MyClass1 : Attribute
{

}
```

**Comment by JosefPihrt** [comment]
I could be done but it's faster to check class name. And every attribute's name ends with "Attribute" that's the convention.
