### ISSUE TITLE
Disable ConvertAll suggestion by default

### ISSUE THREAD

**Issue by Arithmomaniac** [JosefPihrt/Roslynator#736]
Consider reversing or muting #559. As discussed in https://github.com/dotnet/runtime/issues/38418#issuecomment-706803864, this scenario is optimized away inside the framework.

**Comment by JosefPihrt** [comment]
If I would have known about this optimization I would have consider if it's worthy to implement it but now when it's done it doesn't make sense to disable.

And I'm not sure if this optimization is available in .NET Framework or in .NET Core only.

**Comment by Arithmomaniac** [comment]
I couldn't find the class on referencesource, so I guess it's only Core.

**Comment by xtqqczze** [comment]
I found this diagnostic worthwhile, see https://github.com/PowerShell/PowerShell/pull/15140#issuecomment-816653482
