### ISSUE TITLE
RR0116 Invert LINQ method call does not preserve value 

### ISSUE THREAD

**Issue by ragnarstolsmark** [JosefPihrt/Roslynator#739]
**Product and Version Used**: 
Latest Roslynator
**Steps to Reproduce**:
```csharp
var bools = new List<bool> { true, false, false };
bools.All(b => !b) // returns false
//roslynator suggests: "Invert 'All'
--
```
**Actual Behavior**:
```csharp
//after fix
var bools = new List<bool> { true, false, false };
bools.Any(b => b) // returns true
```

**Expected Behavior**:
```csharp
//after fix
var bools = new List<bool> { true, false, false };
!bools.Any(b => b) // returns false
```

**Comment by JosefPihrt** [comment]
This refactoring actually rewrite LINQ method call so it returns inverted value. 

If you want to logically negate the method call you can put `!` before the expression but the result will be quite unreadable. So it's better to use this refactoring.

Logical negation of `bools.All(b => !b)` is more readable as
```cs
bools.Any(b => b)
```
than
```cs
!bools.All(b => !b)
```

Maybe the title of the refactoring can be improved to be more clear.

**Comment by ragnarstolsmark** [comment]
Yes, maybe. I was a bit surprised by the behaviour.

Last ned Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JosefPihrt** [comment]
I looked at the list of refactorings and found following refactorings:

* InvertBinaryExpression
* InvertBooleanLiteral
* InvertIsExpression
* InvertLinqMethodCall
* InvertConditionalExpression
* InvertIfElse

All these refactorings does the same thing: it provides convenient way to logically negates the expression in cases where is either impossible or unreadable to just add `!` operator before the expression.

So the convention is that "Invert..." means logical negation of the expression.
