### ISSUE TITLE
Invalid RCS1089 and RCS1059 suggestions for records

### ISSUE THREAD

**Issue by jhgbrt** [JosefPihrt/Roslynator#749]
**Product and Version Used**: 
Roslynator 3.0.1

**Steps to Reproduce**:

The code below suggests both RCS1089 (use ++ operator instead of assignment) and RCS1058 (use compound assignment), both of which are invalid.

```csharp
record MyRecord(int AnInt)
{
    public MyRecord F() => this with { AnInt = AnInt + 1 };
}
```

**Comment by JosefPihrt** [comment]
Fixed with #741
