### ISSUE TITLE
RCS1158 understanding / explanation

### ISSUE THREAD

**Issue by silvioboehme** [JosefPihrt/Roslynator#75]
Hi!
I do not understand, why is RCS1158 fired for the code below.
I have found some explanations about static members in generic classes. But a static method?
RCS1158 fires for this code:
```
public abstract class BaseModelTest<TModel>
    where TModel : BaseModel<TModel>, new()
{
    public static TModel CreateModel()
    {
        return new TModel();
    }
}
```
Why? Is this a bug in the analyzer or why should i avoid this?

Thanks

**Comment by JosefPihrt** [comment]
Hi,

I think that you code is fine.

I have looked at the implementation of that analyzer and it fires for every publicly visible static member in generic class which is not a proper rule.

I think that correct rule could be that it would fire for every static member in generic class where member's signature does not contain any type parameter.

**Comment by JosefPihrt** [comment]
Fixed with fc53c72e39c606c4cc8b027d0af5b4104c87b14f

**Comment by JosefPihrt** [comment]
Leave a comment

**Comment by silvioboehme** [comment]
Hi! Thanks for this nice analyzers.

I have tested the last fix with my code, and it Looks very good.
The new implementation is fine for me.

Thanks

**Comment by JosefPihrt** [comment]
I glad you like it.
