### ISSUE TITLE
Suggestion: Inline simple getter and setter

### ISSUE THREAD

**Issue by lechu445** [JosefPihrt/Roslynator#756]
Consider addition of refactoring that could do this:
```c#
        public string Id
        {
            get;
            set;
        }
```
to/from
```c#
        public string Id { get; set; }
```
It will save a lot of time spent on refactoring models.

**Comment by JosefPihrt** [comment]
This analyzer already exists:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS0042.md

Full list of formatting analyzers:
https://github.com/JosefPihrt/Roslynator/blob/master/src/Formatting.Analyzers/README.md
http://pihrt.net/Roslynator/Analyzers?Query=rcs0

Note: All formatting analyzers are disabled by default.
