### ISSUE TITLE
Release of version 3.0.1 in Nuget

### ISSUE THREAD

**Issue by anreton** [JosefPihrt/Roslynator#757]
**Product and Version Used**: 
Nuget Roslynator.Analyzers 3.0.0 - https://www.nuget.org/packages/Roslynator.Analyzers/

**Actual Behavior**:
Version 3.0.1 is unavailable in Nuget.

**Expected Behavior**:
Version 3.0.1 is available in Nuget.

P.S.
We wish you the best of holidays and a Happy New Year!

**Comment by JosefPihrt** [comment]
Just released: https://www.nuget.org/packages/Roslynator.Analyzers/3.1.0-rc

It is intentional that not every release is published as NuGet package.

P.S. I'm sending my best wishes to Russia!
