### ISSUE TITLE
[Question] Enable refactorings in vscode (RRxxxx)

### ISSUE THREAD

**Issue by lonix1** [JosefPihrt/Roslynator#764]
**Product and Version Used**: 
IDE: vscode latest
config: `.editorconfig` (not rulesets)

**Steps to Reproduce**:
I add the three [nuget packages](https://github.com/JosefPihrt/Roslynator#nuget-analyzers) to the project.

The RCS analyzers work automatically.

How do I enable the refactorings (RRxxxx)?

e.g. I tried `dotnet_diagnostic.RR0190.severity = warning` But that doesn't enable it.

**Comment by JosefPihrt** [comment]
Refactorings are not part of nuget packages and as far as I know it is not even possible to distribute refactorings as a part of nuget package (But it may be possible in the future).

To use Roslynator refactorings please install Roslynator for VS Code: https://marketplace.visualstudio.com/items?itemName=josefpihrt-vscode.roslynator

**Comment by lonix1** [comment]
Ohh I understand now... thanks!

**Comment by lonix1** [comment]
One more thing...

Why is it possible to apply "fixes" without an IDE extension, but not "refactorings"?

**Comment by JosefPihrt** [comment]
As it is stated in [this](https://github.com/JosefPihrt/Roslynator/blob/master/docs/AnalyzersVsRefactorings.md) document

> Refactoring represents a single operation that is provided on demand for a given span of text.

Which I think is quite self-explanatory.

You choose span of text then you choose a refactoring from a menu and then the refactoring is applied.

**Comment by lonix1** [comment]
Actually I haven't installed the vscode extension. But I can still fix some mistakes using the "lightbulb" feature.

From what I understand from your answer, I need the extension to use refactorings.

But even without the extension, I can still fix some things - that's what is confusing.

**Comment by JosefPihrt** [comment]
Short answer: They are code fixes.

Analyzer (+ code fix) vs. Refactoring is a common confusion. To explain the difference between these two features I created [this](https://github.com/JosefPihrt/Roslynator/blob/master/docs/AnalyzersVsRefactorings.md) document. Please look at it and tell me if there is something you don't understand.

**Comment by lonix1** [comment]
Yeah that doc is good.

I think the confusion is there are so many concepts. The heart of the matter is the difference between "fixes" and "refactorings":
- FIX: related to code that failed a specific analyzer rule
- REFACTORING: on-demand refactoring of code; unrelated to analyzers

But that leads to my previous question (*"Why is it possible to apply "fixes" without an IDE extension, but not "refactorings"?"*), which maybe I didn't explain properly - why can a fix be performed without an IDE extension, but a refactoring needs an IDE extension?
