### ISSUE TITLE
Fix with ignored diagnostic not working

### ISSUE THREAD

**Issue by Bouke** [JosefPihrt/Roslynator#768]
**Product and Version Used**: Roslynator.CommandLine master (a3b8ab9ab35499eb80d556b29ee8c88e19312a23)

I only want to fix a specific diagnostic. The command line doesn't seem to offer some whitelist/allowlist functionality, only to ignore certain diagnostics. So using `analyze` I've compiled the full list of warnings, and I'm providing that list back to `fix`, only leaving out the specific diagnostic I want to address (CS8603). To my surprise Roslynator fixed a diagnostic that I specifically asked _not_ to fix:

> &"C:\Users\Bouke\Developer\Roslynator\src\CommandLine\bin\Release\net48\Roslynator.exe" fix --ignored-diagnostics CA1000 CA1001 CA1008 CA1010 CA1018 CA1019 CA1024 CA1031 CA1032 CA1034 CA1036 CA1040 CA1041 CA1051 CA1052 CA1054 CA1056 CA1065 CA1066 CA1200 CA1303 CA1304 CA1305 CA1308 CA1310 CA1502 CA1506 CA1707 CA1708 CA1711 CA1714 CA1717 CA1720 CA1721 CA1724 CA1725 CA1801 CA1805 CA1806 CA1815 CA1816 CA1819 CA1820 CA1822 CA1824 CA1829 CA2000 CA2016 CA2201 CA2208 CA2213 CA2229 CA2234 CA2237 CA3075 CA5350 CA5351 CA5364 CA5369 CA5379 CA9998 CS0618 _**CS0659**_ CS8600 CS8601 CS8602 CS8604 CS8605 CS8618 CS8619 CS8620 CS8621 CS8622 CS8625 CS8629 CS8631 CS8634 CS8714 CS8765 CS8766 CS8767 IDISP001 IDISP002 IDISP003 IDISP004 IDISP005 IDISP006 IDISP007 IDISP013 IDISP014 IDISP015 IDISP019 IDISP023 IDISP024 SA1005 SA1009 SA1011 SA1101 SA1111 SA1116 SA1118 SA1122 SA1129 SA1200 SA1202 SA1208 SA1300 SA1305 SA1306 SA1402 SA1411 SA1413 SA1501 SA1503 SA1513 SA1514 SA1516 SA1600 SA1604 SA1605 SA1626 SA1627 SA1629 SA1633 SI0001 SYSLIB0003
> (...)
> Fixed diagnostics:
>  3 _**CS0659**_ Type overrides Object.Equals(object o) but does not override Object.GetHashCode()

**Comment by JosefPihrt** [comment]
This is a bug that occurs when you want to fix diagnostic that does not have corresponding analyzer (which is case of compiler diagnostic).

The fix will be available on master soon.

**Comment by Pentadome** [comment]
I have the same problem CS8625 is not being ignored

**Comment by JosefPihrt** [comment]
`CS8625` is compiler diagnostic/error.

If you want to suppress compiler diagnostic you can use `NoWarn` MSBuild property.

```
roslynator analyze --properties "NoWarn=CS8625"
```
