### ISSUE TITLE
Ability to only fix specific diagnostic (allow list)

### ISSUE THREAD

**Issue by Bouke** [JosefPihrt/Roslynator#769]
**Product and Version Used**: Roslynator.CommandLine master (a3b8ab9ab35499eb80d556b29ee8c88e19312a23)

With a solution producing 10k+ warnings, fixing all diagnostics at once is not something I want to do. Certain diagnostics are easy fixes and don't require a thorough review, while others might even introduce new behaviour/bugs. 

So I only want to fix a specific diagnostic. The command line doesn't seem to offer some allow list functionality, only to ignore certain diagnostics. It would be great if I could specify an allow list of diagnostics that I want fixed, ignoring all others. E.g. `roslynator fix --diagnostic CS8603`.

**Comment by JosefPihrt** [comment]
```
--supported-diagnostics <DIAGNOSTIC_ID>
```
is what you are looking for.

Nevertheless there is a bug that occurs when you want to fix diagnostic that does not have corresponding analyzer (which is case of compiler diagnostic). This bug will be resolved as a part of #768)
