### ISSUE TITLE
Suggest SpinLock should be read-only

### ISSUE THREAD

**Issue by nrandell** [JosefPihrt/Roslynator#77]
If you have a SpinLock as a field, it comes up with RCS1169 Mark field as read-only.

However as referenced in [http://stackoverflow.com/questions/11224130/spinlock-throwing-synchronizationlockexception](http://stackoverflow.com/questions/11224130/spinlock-throwing-synchronizationlockexception) this is not recommended behaviour and causes an exception to be thrown.

It's easy to supress in code, but should RCS1169 handle such a situation better?

**Comment by JosefPihrt** [comment]
Thanks for the report @nrandell !
