### ISSUE TITLE
warning AD0001 System.TypeInitializationException on old csproj Analyzer reference

### ISSUE THREAD

**Issue by Doraku** [JosefPihrt/Roslynator#774]
So I am not sure if this is the fault of roslynator analyzers or roslyn or even something else but some analyzers (Microsoft.Unity.Analyzers) works as expected thus this issue. My goal is to put in place roslyn analyzers on a unity game project to handle code quality. Unity automatically generates its csproj with the old format so I don't have our say on that :/ To add analyers I use the `Directory.Build.props` file with `PackageReference`. This works well in IDE (VS, VSCODE and even Rider I guess) but it is not picked up when building the project directly with msbuild or dotnet which is needed to create a CI check on pull request so I tried to directly reference the analyzer dll with a `<Analyzer>` item and got the error bellow.
Any help would be greatly appreciated, and thanks for your awesome products, long time happy user.

**Product and Version Used**: 
Roslynator.Analyzers version 3.1.0
Visual Studio 2019 version 16.8.4

**Steps to Reproduce**:
- Create an old framework library project
- Reference the analyzers dll the old way `<Analyzer Include="nuget path\roslynator.analyzers\3.1.0\analyzers\dotnet\cs\Roslynator.CSharp.Analyzers.dll" />`
- Build project using dotnet `dotnet build project.csproj --no-incremental`

**Actual Behavior**:
```
CSC : warning AD0001: L'analyseur 'Roslynator.CSharp.Analysis.NamedTypeSymbolAnalyzer' a levé une exception de type 'System.TypeInitializationException' avec le message 'The type initializer for 'Roslynator.CSharp.DiagnosticDescriptors' threw an exception.'. [D:\Playground\Playground\OldProject\OldProject.csproj]
CSC : warning AD0001: L'analyseur 'Roslynator.CSharp.Analysis.AddBracesToIfElseAnalyzer' a levé une exception de type 'System.TypeInitializationException' avec le message 'The type initializer for 'Roslynator.CSharp.DiagnosticDescriptors' threw an exception.'. [D:\Playground\Playground\OldProject\OldProject.csproj]
CSC : warning AD0001: L'analyseur 'Roslynator.CSharp.AnalyzerOptionsAnalyzer' a levé une exception de type 'System.TypeInitializationException' avec le message 'The type initializer for 'Roslynator.CSharp.AnalyzerOptions' threw an exception.'. [D:\Playground\Playground\OldProject\OldProject.csproj]
```
Lot of AD0001 warnings and no analyzer is actually checked

**Expected Behavior**:
Analyzers are run as espected.

**Comment by JosefPihrt** [comment]
Hi,

you have to reference following dlls:

```xml
<ItemGroup>
  <Analyzer Include="..\packages\Roslynator.Analyzers.3.1.0\analyzers\dotnet\cs\Roslynator.Common.dll" />
  <Analyzer Include="..\packages\Roslynator.Analyzers.3.1.0\analyzers\dotnet\cs\Roslynator.Core.dll" />
  <Analyzer Include="..\packages\Roslynator.Analyzers.3.1.0\analyzers\dotnet\cs\Roslynator.CSharp.Analyzers.dll" />
  <Analyzer Include="..\packages\Roslynator.Analyzers.3.1.0\analyzers\dotnet\cs\Roslynator.CSharp.dll" />
</ItemGroup>
```

**Comment by Doraku** [comment]
Thanks a lot that did the trick, I feel stupid >_> since the dependencies were next to the main Roslynator.CSharp.Analyzers.dll library I thought they would be loaded correctly, I guess roslyn is doing something different under the hood.
