### ISSUE TITLE
Not ignoring DataSet designers.

### ISSUE THREAD

**Issue by TrickUK** [JosefPihrt/Roslynator#78]
Having updated recently, it would seem that Roslynator isn't ignoring DataSet designer files anymore.

The classes aren't marked with any attributes, but the filenames are all .Desginer.cs so should be ignored anyway?

Regards, Richard.

**Comment by JosefPihrt** [comment]
Hi,

I did quick test with "*.Designer.cs" file using latest version (1.3.0) and the file is excluded as expected.

Could you tell me which version are you using and which analyzer is triggered?

Thanks.

**Comment by TrickUK** [comment]
1.3 as of this morning, was also doing it with the previous release (not the one before that though!)
![devenv_2017-04-03_10-22-52](https://cloud.githubusercontent.com/assets/1598146/24603173/a8acbfb0-1857-11e7-872e-7e54e8306b8c.png)

**Comment by TrickUK** [comment]
Just noticed it's doing it for Web references too.

**Comment by JosefPihrt** [comment]
Which product are you using (there are 4 extensions and 2 nuget packages)?

**Comment by TrickUK** [comment]
Oops sorry, Roslynator for VS2015 (refactoring + analysers) installed as an extension.
![devenv_2017-04-03_11-01-44](https://cloud.githubusercontent.com/assets/1598146/24604545/0dc2d6f0-185d-11e7-8d03-1dfcb8854c6d.png)

**Comment by JosefPihrt** [comment]
I found it, it's a bug.

Could you confirm that only RCS1033 and RCS1049 are fired in your generated files?

**Comment by TrickUK** [comment]
Yep I believe that is the case.  Curiously enough I thought I'd create a testbed app so I could send an example of it happening with my ruleset etc.  When I added the DataSet and a TableAdapter, the designer files aren't actually included in the solution tree (but are on disk).  No analysis errors.

Looked at my project exhibiting the problem and there is no way (via IDE) to exclude the designer/xss/xsc files.  Can't say I'd ever noticed they were there when they don't need to be before now!

**Comment by JosefPihrt** [comment]
Fixed with a1241d8a27845baeb90b020cb2ab6cd8a519bed0

**Comment by TrickUK** [comment]
Good stuff, thanks :-)

**Comment by JosefPihrt** [comment]
@TrickUK It's been released.

**Comment by TrickUK** [comment]
Awesome, now updated and a clear issue list :-)

Many thanks, better service than most commercial applications!

**Comment by JosefPihrt** [comment]
I'm glad to hear that!
