### ISSUE TITLE
Apply all fixes to a file

### ISSUE THREAD

**Issue by NGumby** [JosefPihrt/Roslynator#79]
Is there any way to apply all fixes for a rule to a file?

**Comment by JosefPihrt** [comment]
![fixalloccurrencesindocument](https://cloud.githubusercontent.com/assets/11931318/24818044/34ff55e2-1bdf-11e7-8a88-04aa71bcdb42.png)

**Comment by NGumby** [comment]
Thanks, I should have checked!
