### ISSUE TITLE
.NET Core Global Tool - Method not found: Boolean Roslynator.DiagnosticsExtensions.IsAnalyzerSuppressed

### ISSUE THREAD

**Issue by marodev** [JosefPihrt/Roslynator#795]
**Product and Version Used**: 

.NET Core Global Tool
```
dotnet tool install --global Roslynator.DotNet.Cli --version 0.1.2
```

Analyzers
```
dotnet add package Roslynator.Analyzers --version 3.1.0
```

- Project targets netcoreapp3.1
- We have .NET 3 and 5 installed
- `dotnet --version` prints 5.0.101
- Mac OS

**Steps to Reproduce**:

According to [RCS1077](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1077.md), I expect

```
if (myList.Count > 0) { ... }

```

to be

```
if (myList.Any()) { ... }

```

running the following command:
```
roslynator fix -v diag
```

results in something like:
```
Add analyzer assembly 'Roslynator.Workspaces.Core, Version=2.0.0.1, Culture=neutral, PublicKeyToken=926ea54d246a765e'
  189 supported diagnostics with prefix 'RCS' (RCS1001,

...

 189 fixable diagnostics with prefix 'RCS' (RCS1001,

...

Suppress the following diagnostics to disable this analyzer: RCS1015, RCS1068, RCS1077, RCS1080, RCS1097, RCS1107, RCS1112, RCS1112FadeOut, RCS1128, RCS1151, RCS1155, RCS1186, RCS1197, RCS1198, RCS1200, RCS1201, RCS1202, RCS1235, RCS1246
warning AD0001: Analyzer 'Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'Boolean Roslynator.DiagnosticsExtensions.IsAnalyzerSuppressed(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext, Microsoft.CodeAnalysis.DiagnosticDescriptor)'.'.
Exception occurred with following context:
Compilation: ConsoleApp2
SyntaxTree: RiderProjects/SolutionToPlay/ConsoleApp2/Foo.cs
SyntaxNode: myList.All(s => s.Contains("foo" ... [InvocationExpressionSyntax]@[550..584) (27,16)-(27,50)

System.MissingMethodException: Method not found: 'Boolean Roslynator.DiagnosticsExtensions.IsAnalyzerSuppressed(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext, Microsoft.CodeAnalysis.DiagnosticDescriptor)'.
   at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.AnalyzeInvocationExpression(SyntaxNodeAnalysisContext context)
   at Roslynator.CSharp.Analysis.InvocationExpressionAnalyzer.<>c.<Initialize>b__2_0(SyntaxNodeAnalysisContext f)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

...

Unfixed diagnostics:
  2 RCS1163 Unused parameter.

Fixed diagnostics:
  1 RCS1102 Make class static.

```

**Note**: RCS1102 worked, but RCS1077 and many others display the warning message shown above.

**Comment by JosefPihrt** [comment]
Hi,

I was able to reproduce this issue (on Windows, but that should be the same).

I have permanent fix that will be available with the next release of Roslynator CLI.

In the meantime I suggest you to update Roslynator.Analyzers to 3.2.0 which should fix the issue temporarily.

**Comment by marodev** [comment]
Hi @JosefPihrt,

Thanks for looking into this. Do you know by when the 3.2.0 version is available?

**Comment by JosefPihrt** [comment]
I've just published https://www.nuget.org/packages/Roslynator.DotNet.Cli/0.1.3 which should fix the issue.

Also I've published https://www.nuget.org/packages/Roslynator.Analyzers/3.2.0-rc.

**Comment by marodev** [comment]
Yep, I can confirm that it works on .NET Core 3.1. Thanks!

**Comment by JosefPihrt** [comment]
@marodev Great!

**Comment by JosefPihrt** [comment]
fixed with 14af8b18e0830c4f7ce19ee4efd948cb59c69c8a

**Comment by pgrm** [comment]
hello @JosefPihrt - this just popped up on my radar, because dependabot was trying to update Roslynator.Analyzers from 3.1.0 to 3.2.0. and Roslynator.Formatting.Analyzers from 1.1.0 to 1.2.0.

each update separately and both updates combined are causing a lot of these kinds of errors in my project. 3.1.0 and 1.1.0 worked fine though.

Any ideas? What detailed information could I provide you?

**Comment by JosefPihrt** [comment]
@pgrm Hi, can you please open a new issue?

Do you use latest version of CLI https://www.nuget.org/packages/Roslynator.DotNet.Cli/0.1.4 ?
