### ISSUE TITLE
Prefix field identifier with underscore

### ISSUE THREAD

**Issue by vborovikov** [JosefPihrt/Roslynator#80]
Roslynator continues to suggest variable names with a leading underscore even if the option 'Prefix field with underscore' is **unchecked**. I believe, it happens after the Visual Studio was closed unexpectedly or multiple instances were running the same time.

**Comment by vborovikov** [comment]
Unchecking 'Use config file' helped. By the way, where is the config file located? I was unable to find 'roslynator.config' on my PC.

**Comment by JosefPihrt** [comment]
By default, there is no config file. You have to create one.

Please see [How to Configure Refactorings](http://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureRefactorings.md).
