### ISSUE TITLE
Server Error in '/' Application. -> Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by p-bojkowski** [JosefPihrt/Roslynator#802]
![image](https://user-images.githubusercontent.com/74313141/118693237-2d5aab80-b80b-11eb-8486-b1b4e8998f31.png)

![image](https://user-images.githubusercontent.com/74313141/118693261-33508c80-b80b-11eb-90ea-e9b4e8042472.png)

**Comment by JosefPihrt** [comment]
Thanks for the report. It's back online.
