### ISSUE TITLE
msbuild-path found twice or not at all depending on if you add the --msbuild-path-flag

### ISSUE THREAD

**Issue by xJom** [JosefPihrt/Roslynator#805]
**Product and Version Used**: 
Roslynator 0.1.1.3

**Steps to Reproduce**:
C:\Users\<myname>\.nuget\packages\roslynator.commandline\0.1.3\tools\net48\Roslynator.exe analyze -p "Configuration=Debug Local" -v diag Routing\RoutingMicroKernel\RoutingMicroKernel.csproj

**Actual Behavior**:
```csharp
Multiple MSBuild locations found:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
Use option '--msbuild-path' to specify MSBuild location
```

**Expected Behavior**:
```csharp
Found C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
```

Something identifies the same path twice.

Pointing out that path 
C:\Users\<myname>\.nuget\packages\roslynator.commandline\0.1.3\tools\net48\Roslynator.exe analyze -p "Configuration=Debug Local" -v diag Routing\RoutingMicroKernel\RoutingMicroKernel.csproj --msbuild-path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin'
renders the error:

A directory or directories in "msbuildSearchPaths" do not exist

**Comment by JosefPihrt** [comment]
Ad 1) I think that method `MSBuildLocator.QueryVisualStudioInstances` should not return duplicated paths:

https://github.com/JosefPihrt/Roslynator/blob/67b75f8370c5aa7ca2cf50d208a8eb5adbdc0baf/src/CommandLine/Commands/MSBuildWorkspaceCommand.cs#L210

 so it seems to me as a bug in `Microsoft.Build.Locator` package. But I can fix this issue.

Ad 2) Error message `A directory or directories in "msbuildSearchPaths" do not exist` comes again from `MSBuildLocator` and according to code the error is throw when a directory does not exist:

https://github.com/microsoft/MSBuildLocator/blob/d83904bff187ce8245f430b93e8b5fbfefb6beef/src/MSBuildLocator/MSBuildLocator.cs#L185-L189
