### ISSUE TITLE
Msbuild fails for every csproj using 0.1.3

### ISSUE THREAD

**Issue by xJom** [JosefPihrt/Roslynator#806]
**Product and Version Used**: 
0.1.3

**Steps to Reproduce**:
dotnet add $item.AbsolutePath package Roslynator.CommandLine -v $Env:Roslynator_Cmdline_Version
& C:\Users\<user>\.nuget\packages\roslynator.commandline\$Env:Roslynator_Cmdline_Version\tools\net48\Roslynator.exe analyze -p "Configuration=Debug Local" -v diag $item.AbsolutePath --msbuild-path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin'

**Actual Behavior**:
```csharp
10:08:49   Evaluate 00:00.03 X.csproj
10:08:49   Msbuild failed when processing the file 'X.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets: (1720, 5): The "GetReferenceNearestTargetFrameworkTask" task could not be instantiated from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask' to type 'Microsoft.Build.Framework.ITask'.
```

**Expected Behavior**:
```csharp
11:04:24   Evaluate  00:00.03  X.csproj
11:04:24   Build     00:00.06  X.csproj
11:04:24   Resolve   00:00.00  X.csproj (netstandard2.0)
```

Going back to 0.1.1 makes it work better, but still fails for a few csprojs.

**Comment by JosefPihrt** [comment]
Which version of Visual Studio do you use?

**Comment by JosefPihrt** [comment]
There is no reason to add Roslynator CLI as a package to a project:
```
dotnet add $item.AbsolutePath package Roslynator.CommandLine -v $Env:Roslynator_Cmdline_Version
```

**Comment by JosefPihrt** [comment]
@xJom Do you still need a help or can this issue be closed?
