### ISSUE TITLE
Solution level roslynator.config in VS Code

### ISSUE THREAD

**Issue by jibbers42** [JosefPihrt/Roslynator#809]
I've tried this roslynator.config in the solution folder and the project folder (and restarted vsode), but the refactoring is still there.
```
<?xml version="1.0" encoding="utf-8"?>
<Roslynator>
  <Settings>
    <Refactorings>
      <!-- RR0064: Introduce and initialize field, handled by Roslyn -->
      <Refactoring Id="RR0064" IsEnabled="false" />
    </Refactorings>
  </Settings>
</Roslynator>
```

Does the Config File option detailed https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureRefactorings.md work in vscode?

**Comment by JosefPihrt** [comment]
Hi, you have to put config file into "local app data" folder, please see:

https://github.com/JosefPihrt/Roslynator/blob/master/src/VisualStudioCode/package/README.md#location-of-configuration-files

**Comment by jibbers42** [comment]
I was going to request the feature since my other analyzers and such are configured under source control and it seemed tidy to keep it all together, but it occurs to me that both config files may exist and precedence may not be as straightforward as "settings in closer file wins"... I'll just use the global file.

Thanks for the help.
