### ISSUE TITLE
Roslynator.CodeAnalysis.CSharp.InvocationExpressionAnalyzer threw an exception of type System.MissingMethodException

### ISSUE THREAD

**Issue by pgrm** [JosefPihrt/Roslynator#816]
**Product and Version Used**: 

- Roslynator.Analyzers 3.2.0
- Roslynator.CodeAnalysis.Analyzers 1.0.0
- Roslynator.Formatting.Analyzers 1.2.0

**Steps to Reproduce**:

This issue started when dependabot updated the Roslynator.Analyzers dependency from 3.1.0 and Roslynator.Formatting.Analyzers from 1.1.0

The issue persists regardless if I update one of the two packages or both of them.

The exact error shown (hundreds of times) by the compiler is:

>   Analyzer 'Roslynator.CodeAnalysis.CSharp.InvocationExpressionAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'Boolean Roslynator.DiagnosticsExtensions.IsAnalyzerSuppressed(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext, Microsoft.CodeAnalysis.DiagnosticDescriptor)'.'.

As suggested in https://github.com/JosefPihrt/Roslynator/issues/795#issuecomment-859929724 I tried to update the Roslynator.DotNet.Cli tool:

````
> dotnet tool update --global Roslynator.DotNet.Cli
Tool 'roslynator.dotnet.cli' was successfully updated from version '0.1.0' to version '0.1.4'.
````

but the error persisted. 

The first 3 projects which are my core dependencies are all configured with:

```xml
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>9</LangVersion>
    </PropertyGroup>
```

The dotnet SDK used is 5.0.301 on macOS Big Sur

I'll be moving everything to net5.0 soon, maybe that will help  🤷

In case the are additional information I can provide, I'm happy to do so.

**Comment by JosefPihrt** [comment]
Where does the error occur? Is it inside Visual Studio (for Mac) or during execution of Roslynator CLI (`roslynator fix ...` or something like that)?

The most helpful would be to create a small repro so I can see the error on my machine.

**Comment by pgrm** [comment]
It's happening in the command line when running `dotnet build Solution.sln` - I'll try to create a sample project, but I do believe that this library works just fine for everyone and it's something weird that I'm doing.

I tried running `roslynator fix` in the directory of a project but I get the error

```
One or more errors occurred. (Assembly with same name is already loaded)
  Inner exception: Assembly with same name is already loaded
```

However, this is also happening when I run it with the older libraries when `dotnet build` works just fine.

I'll try to create a new project with all the roslynator rules enabled to see if I run into any issues and let you know

**Comment by karl-sjogren** [comment]
I got the same error in a .Net 5 project on Windows after upgrading to Roslynator.Analyzers 3.2.0. We had Roslynator.CodeAnalysis.Analyzers installed in our project and removing that fixed this.

**Comment by JosefPihrt** [comment]
@karl-sjogren thanks for the report! Now I understand where is the problem, I will release updated version of `Roslynator.CodeAnalysis.Analyzers`.

Btw, I know that a lot of people will just install all available packages (including `Roslynator.CodeAnalysis.Analyzers`) and see the results which is fine. In this particular case the package `Roslynator.CodeAnalysis.Analyzers` is only useful for projects that reference Roslyn (Microsoft.CodeAnalysis* packages).

**Comment by kkankala** [comment]
Hi, Is this issue resolved?

**Comment by JosefPihrt** [comment]
@kkankala https://www.nuget.org/packages/Roslynator.CodeAnalysis.Analyzers/1.1.0
