### ISSUE TITLE
Update for Visual Studio 2022

### ISSUE THREAD

**Issue by ryanbuening** [JosefPihrt/Roslynator#819]
Was wondering if there are plans to update this extension for VS 2022? Migration guide can be found here: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension

**Comment by JosefPihrt** [comment]
Hi,

I have a plan to release "Roslynator 2022". I think that it should be within several weeks if the migration succeeds.

**Comment by JosefPihrt** [comment]
77ee33f27831e30bde5cb66d2305a1691a1f229b

**Comment by JosefPihrt** [comment]
https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2022
