### ISSUE TITLE
Add extension to open-vsx

### ISSUE THREAD

**Issue by pm4rcin** [JosefPihrt/Roslynator#820]
Hi, please consider adding extension to [open-vsx](https://open-vsx.org) so people who use VSCodium could easily install it.

**Comment by symbiogenesis** [comment]
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by JosefPihrt** [comment]
in progress, see https://github.com/EclipseFdn/open-vsx.org/issues/1029

**Comment by JosefPihrt** [comment]
Ok, so C# extension probably won't be published to open-vsx:

https://github.com/OmniSharp/omnisharp-vscode/issues/3853

**Comment by pm4rcin** [comment]
@JosefPihrt sorry for bump but could you tell what stops it? Can't you just change dependency name to the one that is in open-vsx?

**Comment by JosefPihrt** [comment]
@pm4rcin I have a plan to do it as part of next release of Roslynator. Please stay tuned.

**Comment by JosefPihrt** [comment]
https://open-vsx.org/extension/josefpihrt-vscode/roslynator

**Comment by pm4rcin** [comment]
It took a while but it's finally here. Thanks @JosefPihrt! Appreciate it.
