### ISSUE TITLE
RCS0052: not invertable with .editorconfig

### ISSUE THREAD

**Issue by Jupakabra** [JosefPihrt/Roslynator#823]
**Product and Version Used**: 
Roslynator 2019 - 3.2.1

**Steps to Reproduce**:
Use this `.editorconfig`
```ini
dotnet_diagnostic.RCS0052.severity = suggestion
roslynator.RCS0052.invert = true
```
with this code
```csharp
IFormFile[] files =
{
    new FormFile(new MemoryStream(), 0, 1, "1", "1.txt"),
    new FormFile(new MemoryStream(), 0, 2, "2", "2.txt")
};
```

**Actual Behavior**:
Getting suggestion of
```
RCS0052	Add newline before equals sign instead of after it.
```
with inverted true or false

**Expected Behavior**:
No error if inverted option is enabled.

**Comment by JosefPihrt** [comment]
@Jupakabra thanks for the report!
