### ISSUE TITLE
Getting CS8032 Warnings With Latest Package Version

### ISSUE THREAD

**Issue by pnquest** [JosefPihrt/Roslynator#824]
**Product and Version Used**: 
Roslynator.Analyzers nuget package. 3.2.0

**Steps to Reproduce**:
Install version `3.2.0` in your project and run dotnet build from a linux box. The output of dotnet info can be found below. This behavior *does not* exist with version `3.1.0`.

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.410
 Commit:    db62c6bbbb

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.410/

Host (useful for support):
  Version: 3.1.16
  Commit:  4c6b4aa257

.NET Core SDKs installed:
  3.1.410 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Actual Behavior**:
Get hundreds of warnings, it at least appears to be one for every Roslynator Analyzer of the below format. Explicitly taking a reference on version 3.8.0 of Microsoft.CodeAnalysis does not make these warnings go away.

```
CSC : warning CS8032: An instance of analyzer Roslynator.CSharp.Analysis.RemoveRedundantAutoPropertyInitializationAnalyzer cannot be created from /path/to/nuget-cache/nuget/packages/roslynator.analyzers/3.2.0/analyzers/dotnet/cs/Roslynator.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/path/to/csproj]
```

**Expected Behavior**:
There should be no warning.

**Comment by JosefPihrt** [comment]
I think that this problem can be solved by installing .NET Core SDK 5.0: https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by pnquest** [comment]
@JosefPihrt This is happening in our build pipeline. It feels a little odd to need to install an SDK I am not actually using (because we stick to LTS releases of .Net) to properly build a project targeting .net core 3.1. 

Is there any other way to resolve this? I am still not entirely clear on what is happening.

**Comment by JosefPihrt** [comment]
I had to move to Roslyn 3.8.0 to be able to fully support editorconfig options. This issue it unintentional side-effect.

It seems that .NET Core 3.1 (3.1.410) uses Roslyn 3.7.0 (`dotnet/sdk/3.1.410/Roslyn/bincore/Microsoft.CodeAnalysis*.dll`).

There are two options:
1) Use .NET Core 5.0
2) Use .NET Core 3.1 and stay on Roslynator.Analyzers.3.1.0

**Comment by pnquest** [comment]
That makes sense, We will just have to stay on 3.1.0 until we move to .Net 6
