### ISSUE TITLE
RCS1128: False positive

### ISSUE THREAD

**Issue by miraks31** [JosefPihrt/Roslynator#825]
Hi,

The following line:
`JObject refe = item == null ? null : Coco.Referential.GetReferential(item);`
returns a RCS1128 code.

This seems to be a false positive issue.

**Comment by JosefPihrt** [comment]
Hi,

Thanks for the report. I was not able to reproduce the bug. Can I ask you to provide a simple repro that does not contain external references?

Are you sure that the code is `RCS1128`? This diagnostic is reported on `if` statements.

**Comment by miraks31** [comment]
The false positive is on my side.
Sorry ! You can close this ticket.
