### ISSUE TITLE
RCS0054: consider option for null-conditional operator chaining

### ISSUE THREAD

**Issue by anreton** [JosefPihrt/Roslynator#827]
**Product and Version Used**: 
Microsoft Visual Studio Community 2019 Version 16.10.4
Roslynator.Formatting.Analyzers 1.2.1 via Nuget
[RCS0054](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS0054.md)

**Steps to Reproduce**:
```csharp
var list = new List<int>() { 1, 2, 3, 4, 5 };
var filteredList1 = list
	?.Where(item => item > 3)
	.ToList(); // Get diagnostic for RCS0054.
var filteredList2 = list?
	.Where(item => item > 3)
	.ToList(); // No diagnostic for RCS0054.
```

**Actual Behavior**:
There is no option to adjust the position of the null-conditional operator. I would like to place the null-conditional operator at the beginning of the line for readability.

**Expected Behavior**:
It would be great to add an analyzer option to adjust the position of the null-conditional operator at the beginning of the line, not at the end.

**Comment by JosefPihrt** [comment]
This is good idea. It is a question whether to add option to RCS0054 or to add a new rule.

**Comment by anreton** [comment]
> This is good idea. It is a question whether to add option to RCS0054 or to add a new rule.

Adding a new rule with invert option (e.g. [RCS0028](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS0028.md) be more convenient, I guess.
