### ISSUE TITLE
"Use expression body for properties" refactoring eats a newline

### ISSUE THREAD

**Issue by IanKemp** [JosefPihrt/Roslynator#83]
Given the following code:

    protected override Permission[] RequiredPermissions { get { return new Permission[0]; } }
    public Credentials Credentials { get; set; }

Executing the aforementioned refactoring **on the first property** (`RequiredPermissions `) results in the following:

    protected override Permission[] RequiredPermissions => new Permission[0]; public Credentials Credentials { get; set; }

As you can see the second property has been dragged onto the first line.

**Comment by JosefPihrt** [comment]
This fix is not provided by Roslynator.
