### ISSUE TITLE
RCS0053 / RCS0054  question

### ISSUE THREAD

**Issue by p-bojkowski** [JosefPihrt/Roslynator#834]
Hi!

what is the correct formating for this:

```cs
            var mutation = new Mutation().CreateRepository(new CreateRepositoryInput
            {
                Name = repositoryName,
                Visibility = RepositoryVisibility.Private,
                OwnerId = StaticData.PbodevAsOwner,
                Template = false
            })
            .Select(payload => new { payload.Repository.Id })
            .Compile();
```

![image](https://user-images.githubusercontent.com/74313141/128212247-1fc06ea5-56bf-4272-9cd4-3fedb7a807e8.png)

![image](https://user-images.githubusercontent.com/74313141/128212300-a2fd5c59-b270-435d-9b41-56180eaa6bf8.png)

![image](https://user-images.githubusercontent.com/74313141/128212379-952a0f4d-3aea-4b85-8b73-5d8e8f0b7a12.png)

**Comment by fgimian** [comment]
I suggest trying:

```c#
            var mutation = new Mutation()
                .CreateRepository(new CreateRepositoryInput
                {
                    Name = repositoryName,
                    Visibility = RepositoryVisibility.Private,
                    OwnerId = StaticData.PbodevAsOwner,
                    Template = false
                })
                .Select(payload => new { payload.Repository.Id })
                .Compile();
```

Cheers
Fotis

**Comment by Meligy** [comment]
@fgimian sorry for jumping on an old thread, but is there an analyzer that'd do this suggestion for us?

**Comment by fgimian** [comment]
> 

Hey there, I'm sorry but I'm not sure.  I'm just a user of the wonderful Roslynator analyzers package, so I'm not sure if it can refactor this particular issue for you.
