### ISSUE TITLE
RCS0056 long lines in attribute parameters?

### ISSUE THREAD

**Issue by fgimian** [JosefPihrt/Roslynator#838]
**Product and Version Used**: 3.2.0

**Steps to Reproduce**:

There are cases when a parameter to an attribute is very long;

e.g.

```csharp
        [SuppressMessage(
            "SonarAnalyzer.CSharp",
            "S3928:Parameter names used into ArgumentException constructors should match an existing one",
            Justification = "Qualifier variable won't be present due the fact we're mocking.")]
        [Fact]
        public void Invoke_PathHasInvalidQualifier_ShouldError()
        {
            // Arrange
            var pathUtils = Substitute.For<IPathUtils>();
...
```

Unfortunately to my knowledge, there's no way to concat these long strings in attributes.  So I wonder if Roslynator should allow long lines if they relate to an attribute paramater.

**Actual Behavior**:

The message `A line is too long (106 characters).` is thrown for such lines.

**Expected Behavior**:

Assuming that I'm not missing anything, there's simply no way to shorten long string parameters for attributes, and if this is indeed the case, then perhaps Roslynator needs to be more lenient on long lines in these specific scenarios.

**Comment by JosefPihrt** [comment]
You can split long string literal into multiple lines:

```cs
using System;

[Obsolete("looooooooooooooo"
    + "oooooooooooooooong")]
public class Foo
{
}
```

**Comment by fgimian** [comment]
You're absolutely spot on @JosefPihrt, thank you.  This does conflict with StyleCop's SA1118 but I think I'll raise an issue with them to request that they not enforce SA1118 for attributes.  I'll just disable SA1118 for now.

Huge thanks, I'll close this one now
Fotis
