### ISSUE TITLE
Roslynator CLI doesn't work with .NET 5 SDK

### ISSUE THREAD

**Issue by TFTomSun** [JosefPihrt/Roslynator#843]
**Product and Version Used**: 
Roslynator Command Line Tool version 0.1.5.0 (Roslyn version 3.10.0.0)
(dotnet global tool)

**Steps to Reproduce**:
* Install .NET 5 SDK
* Run the fix command with the .NET sdk folder as MsBuildPath (e.g. C:\Program Files\dotnet\sdk\5.0.400)

`
roslynator fix "D:\Git\WebBasedScreenEditor.sln"  --msbuild-path "C:\Program Files\dotnet\sdk\5.0.400" --verbosity diag`

**Actual Behavior**:
I get error messages like:

```
One or more errors occurred. (Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden.
```

**Expected Behavior**:
No error occurs

**Comment by JosefPihrt** [comment]
I would like to mention that `--msbuild-path` will be made optional in the next release. If it's not specified then the latest installed version will be used. I think that it's convenient because you usually want latest version anyway.

**Comment by TFTomSun** [comment]
@JosefPihrt thanks for your response. Is there a workaround to get the current version of the cli working with  .net 5? Or is it not yet supported?

**Comment by JosefPihrt** [comment]
Unfortunately not, but the good news is that a new version of CLI will be released within a week.

**Comment by JosefPihrt** [comment]
Possible workaround is to build CLI locally:

```
git clone "https://github.com/josefpihrt/roslynator.git" roslynator
cd roslynator
dotnet build "src/commandline.sln" -c Release /p:RoslynatorCoreCli=true
dotnet "src/commandline/bin/Release/net5.0/Roslynator.dll" --help
```

**Comment by JosefPihrt** [comment]
https://www.nuget.org/packages/Roslynator.DotNet.Cli/0.2.0
