### ISSUE TITLE
Can you create a single reference point for Roslynator via a nuget package?

### ISSUE THREAD

**Issue by NullVSNone** [JosefPihrt/Roslynator#844]
**Product and Version Used**: 
Roslynator.Analyzers | 3.2.2
Roslynator.CodeAnalysis.Analyzers | 1.1.1
Roslynator.Formatting.Analyzers | 1.2.2

**Steps to Reproduce**:
- Create a new project, let's name it "Shared.Roslyn.Analyzers"
- Have the below in the .csproj
```
    <PackageReference Include="Roslynator.Analyzers" Version="3.2.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="1.2.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```
- Publish as a nuget package
- Reference it from another project called "Main.ViewModel.Sample"
- Have a `.editorconfig` in root of the sample project

**Actual Behavior**:
Roslynator analyzers not available

**Expected Behavior**:
Roslynator analyzers available via editorconfig

-----

Might not be best related to this project, but wondering if anyone has done the same?
The goal is not to require the same `.editorconfig` along with the nuget packages for each project in the solution. Best case scenario, the new "Shared.Roslyn.Analyzers" would hold the Roslynator packages as well as the `.editorconfig` file. Then, when updating that project, it'll be propagated across all other projects.

I know you can have the editor config file in the solution roots, but there are also a number of solutions. For now, just hoping to have the single nuget package and can deal with the editor config if need be.

As an aside, I did have it working when it was Roslynator packages and editor config in the Sample project.

**Comment by JosefPihrt** [comment]
I think that `Directory.Build.props` could be the solution for you:

* https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019
* https://thomaslevesque.com/2017/09/18/common-msbuild-properties-and-items-with-directory-build-props/

**Comment by NullVSNone** [comment]
Thank you @JosefPihrt , that did it! For future reference, what you'd need is the following `Directory.Build.props` file in the project root:
```xml
<Project>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DocumentationFile>bin\Release\Savvyy.SharedKernel.Roslyn.Analysis.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers" Version="3.2.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="1.2.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

Once you have that, you can have a `.editorconfig` in the solution root that contains something like

```
dotnet_diagnostic.{RCSXXXX}.severity = error
```

Where `{RCSXXXX}` is something like `RCS0001`. If you attempt to build, and you do have that "error" - you won't be able to compile.

The last thing I'm trying to figure out is why my nested `.editorconfig` isn't overwriting the root, but not relevant here.
