### ISSUE TITLE
Properties marked as Parameter or CascadingParameter should not be read-only 

### ISSUE THREAD

**Issue by efthymios-ks** [JosefPihrt/Roslynator#845]
**Product and Version Used**: 
Roslynator 2019 (3.2.2) 

**Steps to Reproduce**:

1. Create a Blazor project (may be optional). 
2. Add a backing `cs` file to a page. E.g. `Index.razor` and `Index.razor.cs` (may be optional). 
3. Add a private property with attribute `Microsoft.AspNetCore.Components.ParameterAttribute` or `Microsoft.AspNetCore.Components.CascadingParameterAttribute`. 

**Actual Behavior**:  
I get an `RCS1170` message to turn the property to read-only.  

**Expected Behavior**:  
The thing is that `(Cascading)Parameter` should always have a setter. I understand that private `Parameter` doesn't make much sense. So my suggestion is that:  

1. For properties with `Parameter` attribute, they should always have get/set and maybe be public. If you cannot set them outside the component, there is no point in marking them as `Parameter` in the first place. 
2. For properties with `CascadingParameter` attribute, they should always have get/set. Access modifiers don't play a big role here, because these properties are set by the framework and not by the user.   

**Screenshots**:  
![image](https://user-images.githubusercontent.com/24625287/132121089-8f763a80-831a-4605-8ce8-72821c4aeae5.png)  

![image](https://user-images.githubusercontent.com/24625287/132121095-2fe695c3-49cd-46cb-bf33-ab8deb746fa3.png)

**Comment by JosefPihrt** [comment]
Hi,

Are you suggesting to suppress the diagnostic if the property is marked with either `CascadingParameterAttribute` or `ParameterAttribute`? I'm not sure if I understand point number 1.

**Comment by efthymios-ks** [comment]
Hello, thank you for the reply.
What I'm trying to say is:

If it is marked with Parameter, then it should always be public and have a
getter/setter. So yes suppress the warning. The public modifier here is
needed because when you mark it as Parameter, the user has access it in the
related Razor files. Manually by code.

If it is marked with CascadingParameter, it should also always have a
getter/setter, so again just suppress the stated warning.
The access modifier here is not really relevant, because CascadingParameter
can also be set by the .NET framework and not just by the user.

Efthymios Koktsidis

Στις Τετ, 15 Σεπ 2021, 9:39 μ.μ. ο χρήστης Josef Pihrt <
***@***.***> έγραψε:
