### ISSUE TITLE
RR0086 and RR0087 not appearing in VS 2019 Enterprise -v16.8.4 

### ISSUE THREAD

**Issue by TorreyGarland** [JosefPihrt/Roslynator#848]
Attempted on two different computerz.

The menu commands do not appear on in the light bulb menu.

I double checked the options for roslynator and both are checked.

Is there some magic to turn it on?

**Comment by JosefPihrt** [comment]
Hi, can you please provide a code sample and the text span on which you tried to invoke the refactoring?

**Comment by TorreyGarland** [comment]
Sure thing.
![remove-comment-1](https://user-images.githubusercontent.com/1054548/133944587-fba2b0ad-c2ac-4f1e-8632-71680d1a3a1c.png)

![remove-comment-2](https://user-images.githubusercontent.com/1054548/133944589-b031dd4a-2c77-48f8-a0a4-7e1a6e05db28.png)

![remove-comment-3](https://user-images.githubusercontent.com/1054548/133944591-01826390-5d4c-40d8-8b76-16464c337e97.png)

![remove-comment-4](https://user-images.githubusercontent.com/1054548/133944597-6e3c1c12-de01-448f-83c8-798b7d8961c3.png)

taken from my home computer (VS 2019 Community), but the effects are the same on work computer using VS 2019 Enterprise.

**Comment by TorreyGarland** [comment]
The "Remove Comment" menu item that does appear is from another VSIX product.

I have uninstalled the other one to ensure that it was not a conflict.

**Comment by JosefPihrt** [comment]
I see what's the problem.

[this](https://github.com/JosefPihrt/Roslynator/commit/35417532d44a27d2f35c28458eb0c4170ea4a9c9) commit introduce a change that the comments that should be removed have to be selected. So if you want to remove all comments you have to select entire document/file.

Basically the refactoring "Remove all comments" was merged with "Remove selected comments".

Reason for this change was that the operation "remove all comments" is not very frequent so I does not make sense to show it every time the cursor is inside comment.

From the practical point of view you just press ctrl+a then invoke the refactoring and then optionally "navigate backward" which is ctrl+- on my keyboard layout.

**Comment by TorreyGarland** [comment]
This works for me.  Thank you for the clarification.
