### ISSUE TITLE
Roslynator.CodeAnalysis.Analyzers and Roslynator.Formatting.Analyzers throw an error: An instance of analyzer Roslynator.... cannot be created from ...\Roslynator.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis'

### ISSUE THREAD

**Issue by IsaacGS2709** [JosefPihrt/Roslynator#853]
**Product and Version Used**: 
Roslynator.Analyzers 3.2.2
Roslynator.CodeAnalysis.Analyzers 1.1.1
Roslynator.Formatting.Analyzers 1.2.2
Roslynator.CommandLine 0.1.5

.NetFramework 4.7.2
Visual Studio 2019

**Steps to Reproduce**:
**Actual Behavior**:
1. Create an MVC Web application targetting NetFramework 4.7.2
2. Add the following Nuggets:
    * Roslynator.Analyzers 3.2.2
    * Roslynator.CodeAnalysis.Analyzers 1.1.1
    * Roslynator.Formatting.Analyzers 1.2.2
    * Roslynator.CommandLine 0.1.5

3. Build the application from Visual Studio 2019
4. The output from the build command shows lots of exceptions. Examples:
`An instance of analyzer Roslynator.CSharp.Analysis.RemoveRendandAsyncAwaitAnalyzer cannot be created from C:\...\pacages\Roslynator.Analyzers.3.2.2\analyzers\dotnet\cs\Roslynator.CSharp.Analyzers.dll: Could not load file or assembly  'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=###' or one of its dependencies. The system cannon find the file specified..`
```csharp
```
![image](https://user-images.githubusercontent.com/83312408/137398415-b07a75e4-ef68-4a22-b78e-fda166bd0234.png)

**Expected Behavior**:
There are lots of warnings produced in the output when using those Nuget packages together but it is not consistent. From our entire team, only one developer is getting these warnings and all the remainings are not.

**Comment by kevinoid** [comment]
I encountered what I think is the same issue with `Roslynator.Analyzers` 4.0.0 and the .NET SDK 5.0.404.  To reproduce:

```sh
dotnet new console
dotnet add package Roslynator.Analyzers --version 4.0.0
dotnet build
```
This produces ~350 CS8032 warnings such as:

> CSC : warning CS8032: An instance of analyzer Roslynator.CSharp.Analysis.AbstractTypeShouldNotHavePublicConstructorsAnalyzer cannot be created from /home/username/.nuget/packages/roslynator.analyzers/4.0.0/analyzers/dotnet/cs/Roslynator.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/path/to/csproj]

I don't think `Microsoft.CodeAnalysis.dll` ships with .NET SDK 5.0.404.  To test, I ran the following program:

```csharp
using System;
using System.Reflection;

Assembly codeAnalysis = Assembly.Load("Microsoft.CodeAnalysis");
Console.WriteLine(codeAnalysis.FullName);
```

Which printed

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Perhaps `Roslynator.Analyzers` should depend on [`Microsoft.CodeAnalysis`](https://www.nuget.org/packages/Microsoft.CodeAnalysis)?

**Comment by IsaacGS2709** [comment]
Thanks @JosefPihrt 
I resolved the above issue updating the Visual Studio 2019 as you mentioned. I think we can close this ticket.
