### ISSUE TITLE
Change category of Roslynator analyzers

### ISSUE THREAD

**Issue by JosefPihrt** [JosefPihrt/Roslynator#866]
As a part of 4.0 release I would like to change category of all Roslynator analyzers.

### Current state
Each analyzer has category such as `Readability`, `Usage` etc. I believe that these values have little to no benefit to users.

### Proposed state
Change category for each analyzer in a following way:

* Category `Roslynator_Core` for analyzers in package Roslynator.Analyzers
* Category `Roslynator_CodeAnalysis` for analyzers in package Roslynator.CodeAnalysis.Analyzers
* Category `Roslynator_Formatting` for analyzers in package Roslynator.Formatting.Analyzers

This change will make possible to enable/disable (or change the severity) for each analyzer with just 1-3 entries in EditorConfig:

```editorconfig
dotnet_analyzer_diagnostic.category-Roslynator_Core.severity = <severity>
dotnet_analyzer_diagnostic.category-Roslynator_CodeAnalysis.severity = <severity>
dotnet_analyzer_diagnostic.category-Roslynator_Formatting.severity = <severity>
```

### Drawbacks

Someone may be already using current categories values => it is a breaking change.

**Comment by tiesmaster** [comment]
> This change will make possible to enable/disable (or change the severity) for each analyzer with just 1-3 entries in EditorConfig:

This would be awesome!! I'd definitely appreciate a change like that
