### ISSUE TITLE
CLI - net6.0 compatibility

### ISSUE THREAD

**Issue by chanakya-svt** [JosefPihrt/Roslynator#869]
**Product and Version Used**: 
VSCode: v1.62.3
OS: macOS v12
.Net: v6
Roslynator CLI: v0.3.0

**Steps to Reproduce**:
1. created new dotnet `dotnet new webapi --framework "net6.0" -o test-roslynator-net6` 
2. Install Roslynator as global tool: `dotnet tool install -g roslynator.dotnet.cli`
3. Run `roslynator analyze|fix|format` command

**Actual Behavior**:
From the Discussion in https://github.com/JosefPihrt/Roslynator/discussions/868

<div type='discussions-op-text'>

<sup>Originally posted by **chanakya-svt** December  6, 2021</sup>
Using Roslynator CLI v0.3.0 with .net v6 and getting the following error when running 

`roslynator analyze` or `fix` or `format` commands.

Are there any extra configuration steps for CLI to work with .net v6?

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      3.1.21 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      6.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=osx.11.1-x64
```

**Note**: All the above commands are working with .net v3.1</div>

**Expected Behavior**:
Analyze, Fix, Format or any other commands to work with dotnet v6 similar to previous versions.

**Comment by chanakya-svt** [comment]
Any ETA on when these changes are gonna be released?

**Comment by JosefPihrt** [comment]
I have a plan to release it till the end of the week.

**Comment by JosefPihrt** [comment]
https://www.nuget.org/packages/Roslynator.DotNet.Cli/0.3.1
