### ISSUE TITLE
Roslynator stopped add '_' for private variables. Also setting is missing

### ISSUE THREAD

**Issue by peterM** [JosefPihrt/Roslynator#877]
Last version from 21.1.2022 is used in VS 2022.

I am not able to make roslynator use `Introduce and initialize field` with `_`

In settings there was checkbox for it but now there is no checkbox. Tere are only Open config location, Export settings, Export settings. I  uninstalled and installed extension but no change.

![image](https://user-images.githubusercontent.com/2149830/150771020-2c464272-c3ac-4d0e-b05c-dc8a07a675d0.png)

Thanks for fast help.

**Comment by JosefPihrt** [comment]
Hi,

This checkbox was removed in Roslynator 4.0 and all options are now available through editorconfig (or .roslynatorconfig)

You can easily configure this option with .roslynatorconfig file

1) Open/create file at `C:/Users/<USERNAME>/AppData/Local/.roslynatorconfig`
2) Edit file:
```editorconfig
is_global = true

roslynator_prefix_field_identifier_with_underscore = true
```

Configuration is documented [here](https://github.com/JosefPihrt/Roslynator/blob/master/docs/Configuration.md)

**Comment by peterM** [comment]
Hi 
What a fast response 🤩  
But did not help

Still give me name without `_`

**Comment by JosefPihrt** [comment]
I investigated this issue and I found a bug that causes that value is not properly propagated from .roslynatorconfig file.

Until the fix is released, the solution is to set this option in your .editorconfig file (in your project's folder).

**Comment by peterM** [comment]
I put it into `.editorconfig` and solved problem. Thank you for fast support and help.

**Comment by JosefPihrt** [comment]
I'm glad it helped.
