### ISSUE TITLE
Settings errors when rebuilding

### ISSUE THREAD

**Issue by Richard-Payne** [JosefPihrt/Roslynator#879]
**Product and Version Used**: 
VS Code 1.63.2
dotnet v6.0.101

**Steps to Reproduce**:
Place file "editorconfig" next to the csproj file containing:
```
roslynator_accessibility_modifiers = implicit
roslynator_enum_has_flag_style = method
dotnet_analyzer_diagnostic.category-roslynator.severity = error
roslynator_analyzers.enabled_by_default = true
roslynator_refactorings.enabled = true
```

1st run of "dotnet build" throws out warnings:

> CSC : warning ROS0003: Analyzer RCS1018 requires config option to be specified: roslynator_accessibility_modifiers [/home/richard/git/workitem-automation/WorkItemAutomation/WorkItemAutomation.csproj]
> CSC : warning ROS0003: Analyzer RCS1096 requires config option to be specified: roslynator_enum_has_flag_style [/home/richard/git/workitem-automation/WorkItemAutomation/WorkItemAutomation.csproj]

2nd run of "dotnet build" completes with no warnings.

I can produce the above warnings every time using "dotnet build --no-incremental".

**Actual Behavior**:
Clean build on first build

**Expected Behavior**:
Dirty build on first build

**Comment by JosefPihrt** [comment]
New version should be released within a few days.

**Comment by JosefPihrt** [comment]
@Richard-Payne  Newer version of Roslynator for VS Code was just released.
