### ISSUE TITLE
Fix for CS0164 erases entire line, not just unused label.

### ISSUE THREAD

**Issue by ZaneDubya** [JosefPihrt/Roslynator#880]
**Product and Version Used**: 
VS 2022

**Steps to Reproduce**:
Write this code:
```csharp
        private void test() {
            L0003: int a = 0;
            L001D: return;
        }
```
Then run Roslynator fix for CS0164.

**Actual Behavior**:
Roslynator removes all lines:
```csharp
        private void test() {
        }
```

**Expected Behavior**:
Roslynator should remove only unused labels:
```csharp
        private void test() {
            int a = 0;
            return;
        }
```

**Comment by JosefPihrt** [comment]
Hi,

Sorry for the delay.

It makes sense to me to remove label including the code because the code will be executed only if the label is used.
