### ISSUE TITLE
roslynator CLI argument -o (--output) doesn't work. 

### ISSUE THREAD

**Issue by 1026908346** [JosefPihrt/Roslynator#897]
**Product and Version Used**: 
dotnet sdk: 6.0.202 
roslynator: Roslynator Command Line Tool version 0.3.2.0 (Roslyn version 4.1.0.0)

**Steps to Reproduce**:

**Actual Behavior**:
```csharp
```
roslynator cli worked, but the argument -o(output) doesn't work!  
<img width="1109" alt="actually" src="https://user-images.githubusercontent.com/35002543/165730971-ae8e9c58-4a77-4d70-b2be-149e2fad3a27.png">

**Expected Behavior**:
```csharp
```
the argument -o(output) will store reported diagnostics in XML format.

**Comment by 1026908346** [comment]
what's the next release time about the roslynator CLI probobaly？🌹

**Comment by JosefPihrt** [comment]
Very soon, probably during this weekend.

**Comment by mac2000** [comment]
Not sure if it relates but seems like this one appeared once again

<img width="842" alt="image" src="https://user-images.githubusercontent.com/88868/224646255-de534af1-423b-4c95-8f86-e78c579946de.png">

<details>
<summary>logs</summary>

```log
mba:adminapi mac$ roslynator --version
0.5.0.0
mba:adminapi mac$ dotnet --version
7.0.201
mba:adminapi mac$ roslynator analyze --output results.xml
Load solution '/Users/mac/github.com/rabotaua/adminapi/AdminApi.sln'
Done loading solution '/Users/mac/github.com/rabotaua/adminapi/AdminApi.sln'
Analyze solution '/Users/mac/github.com/rabotaua/adminapi/AdminApi.sln'
Analyze 'AdminApi' 1/2
  Startup.cs(200,13): warning CS0618: 'ConsoleLoggerExtensions.AddConsole(ILoggerFactory)' is obsolete: 'This method is obsolete and will be removed in a future version. The recommended alternative is AddConsole(this ILoggingBuilder builder).'
  Startup.cs(201,13): warning CS0618: 'DebugLoggerFactoryExtensions.AddDebug(ILoggerFactory)' is obsolete: 'This method is obsolete and will be removed in a future version. The recommended alternative is AddDebug(this ILoggingBuilder builder).'
Analyze 'AdminApi.Tests' 2/2
Done analyzing solution '/Users/mac/github.com/rabotaua/adminapi/AdminApi.sln' in 00:01.00

2 CS0618 Type or member is obsolete

2 diagnostics found
mba:adminapi mac$ ls -la | grep results.xml
```

</details>

> should not be really important but just in case I'm on arm macos
