### ISSUE TITLE
Missing release notes for 4.1.1

### ISSUE THREAD

**Issue by xt0rted** [JosefPihrt/Roslynator#909]
The [changelog](https://github.com/JosefPihrt/Roslynator/blob/master/ChangeLog.md) and [github release](https://github.com/JosefPihrt/Roslynator/releases/tag/v4.1.1) don't have any release notes for this version.

**Comment by JosefPihrt** [comment]
Release contains a lot of small bug fixes, no new features.

I agree that it I would be better to list each bug fix, I'll work on it for the next release.

**Comment by JosefPihrt** [comment]
Fixed with https://github.com/JosefPihrt/Roslynator/pull/915
