### ISSUE TITLE
`RR0038 Expand initializer`: parens not added

### ISSUE THREAD

**Issue by jtheisen** [JosefPihrt/Roslynator#92]
A tiny annoyance, the refactoring makes from this:

```
var x = new X { M = m };
```

this

```
var x = new X;
x.M = m;
```

So that the parens are missing.

PS: You want to hear about ideas for refactoring in the form of feature requests?

**Comment by JosefPihrt** [comment]
This has been fixed with #90.

I will appreciate any idea for a new refactoring. Please create a new issue so we can discuss it. Thanks.
