### ISSUE TITLE
RCS1197 bug in optimization suggest when calculation is involved.

### ISSUE THREAD

**Issue by jafin** [JosefPihrt/Roslynator#923]
**Product and Version Used**: 

Roslynator 4.11

**Steps to Reproduce**:

Given this code

```csharp
sb.Append(s.Substring(start + len));
```

**Actual Behavior**:

The suggested optimization is

```csharp
sb.Append(s, start + len, s.Length - start + len);
```

but possibly should be

**Expected Behavior**:
```csharp
sb.Append(s, start + len, s.Length - (start + len));
```

**Comment by karl-sjogren** [comment]
In the best case this would throw an `ArgumentOutOfRangeException` and in the worst case the wrong data would be appended without anyone noticing.

I've created a PR for fixing this.
