### ISSUE TITLE
Crash when lambda expression used instead of return (with parameter) after version 1.3.11 update

### ISSUE THREAD

**Issue by jsabrooke** [JosefPihrt/Roslynator#94]
Visual Studio 2015 crashes as soon as a completed line with a method (with a parameter) that uses lambda expression instead of a return statement is encountered. For example, it will crash on
`private bool Test(int i) => true;` or
`private bool Test(int i) => i == 1;

`,
but not  on
`private bool Test() => true;` or
`private bool Test(int i) 
{ 
    return i == 1;
}`

Here's my ActivityLog, but I'm not not sure that it contains the relevant error:
[ActivityLog.txt](https://github.com/JosefPihrt/Roslynator/files/1011620/ActivityLog.txt)

Also here's my Event Viewer error:
[RoslynatorEventLog1.txt](https://github.com/JosefPihrt/Roslynator/files/1011626/RoslynatorEventLog1.txt)

**Comment by JosefPihrt** [comment]
@jsabrooke Please install latest version that fixes the issue.
