### ISSUE TITLE
RR0062: Inline Method refactoring not appearing

### ISSUE THREAD

**Issue by tiesmaster** [JosefPihrt/Roslynator#95]
I love this project, it's impressing how many refactoring you've wrote in a limited amount of time. Though, I have a bug in a refactoring.

In the shown code, the refactoring "RR0062: Inline Method" doesn't appear. As you can see in the screenshot below, I do have Roslynator installed (latest version, v1.3.11), and it's firing RCS1008, but not Inline Method.

![image](https://cloud.githubusercontent.com/assets/460904/26305563/1b809854-3ef0-11e7-98cd-8570e8e31f24.png)

I'm running VS 2017 (15.2, (26430.6). What do you need to reproduce this issue? I cannot zip the source, since it's work, but maybe you have a suggestion to make a minimal reproduction case.

**Comment by JosefPihrt** [comment]
I'm glad that you like Roslynator!

I need to know how the method declaration look like. Could you send it to me, please?

**Comment by tiesmaster** [comment]
Ah, that might be it, they're expression bodied members:

````git
-        private PricingRecommendationService<PricingRecommendationDto> CreateNonPromotionalSut()
-            => _fixture.Create<PricingRecommendationService<PricingRecommendationDto>>();
-
-        private PricingRecommendationService<PromotionalPricingRecommendationDto> CreatePromotionalSut()
-            => _fixture.Create<PricingRecommendationService<PromotionalPricingRecommendationDto>>();
````
