### ISSUE TITLE
Support <inheritdoc/> when generating documentation

### ISSUE THREAD

**Issue by jmasek** [JosefPihrt/Roslynator#954]
**Product and Version Used**: 
Roslynator Command Line Tool version 0.3.3.0 (Roslyn version 4.2.0.0)

**Steps to Reproduce**:
* Create an interface and document its methods. 
* Create a class that implements the interface and use `/// <inheritdoc/>` directive to use the documentation from interface.

**Actual Behavior**:
```csharp
public interface IClient
{
    /// <summary>
    /// Sends the message to the stream
    /// </summary>
   public Task SendMessageAsync();
}

public sealed class Client: IClient
{
    /// <inheritdoc/>
    public async Task SendMessageAsync(){...}
}
```
No description is shown in documentation for `Client:SendMessageAsync()`

**Expected Behavior**:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#inheritdoc

Description is shown in documentation for `Client:SendMessageAsync()`

**Comment by JosefPihrt** [comment]
https://tunnelvisionlabs.github.io/SHFB/docs-master/SandcastleBuilder/html/79897974-ffc9-4b84-91a5-e50c66a0221d.htm
