### ISSUE TITLE
What is the suggestion of analysers based on?

### ISSUE THREAD

**Issue by Bartolomeus-649** [JosefPihrt/Roslynator#98]
It should be possible to determine if what an analyser suggest is "opinion based" or if there is a real and substantial reason for what is suggested, and what that reason is.

**Comment by JosefPihrt** [comment]
General rule is that if the analyzer is what you called "opinion based" then it is disabled by default (see [List of Analyzers](http://github.com/JosefPihrt/Roslynator/blob/master/source/Analyzers/README.md)).

**Comment by Bartolomeus-649** [comment]
There is still no way of knowing or finding out what the suggestion of analysers based on.
For me it seems like a trivial task to write down why a specific analyser exist, after all you do know which problem an analyser is trying to address when you write it, right?
