### ISSUE TITLE
Wrap in condition was not showing up after label

### ISSUE THREAD

**Issue by wmjordan** [JosefPihrt/Roslynator#984]
**Product and Version Used**: 
Latest

**Steps to Reproduce**:
The following code should reproduce the issue:
````C#
void Main() {
START:
   Console.WriteLine();
   Console.WriteLine();
}
````

Select the above two `Console.WriteLine();` and go for the refactor margin.
_Wrap in Condition_ refactoring will not show up.

The problem is that the selection does not cover two statements on same syntax tree hierarchy completely.
The first `Console.WriteLine();` statement is a child of a `LabeledStatementSyntax` statement and the latter `WriteLine` statement is a sibling of the the `LabeledStatementSyntax`.

**Comment by JosefPihrt** [comment]
I would say that it is correct that the refactoring won't show up when these two statements are selected.

What do you think should be the desired behavior?

**Comment by wmjordan** [comment]
If those two `WriteLine`s were selected, the above code could be refactored to:

````C#
void Main() {
START:
   if () {
      Console.WriteLine();
      Console.WriteLine();
   }
}
````

**Comment by JosefPihrt** [comment]
I agree with the first code sample. I disagree with the second code sample.

If there are selected two consecutive statements that are from different "levels" of syntax tree it should not be suggested to put them into same block (like `if` block in the second code sample).

**Comment by wmjordan** [comment]
Ok. Just let it be there.
VS's _Extract Method_ refactoring also supports the first case but not the second case.

Anyway, I myself do not think the second case is an unreasonable operation and have implemented that in my own VS extension to support both cases, with an especially included treatment for the `LabeledStatementSyntax` when it is the first statement.

**Comment by wmjordan** [comment]
Let's look at the following code:
````C#
if (1 != 2 && 2 != 3 && 3 != 4 && 4 != 5) {
}
````
If we place the caret at the first `&&` operator and a refactor to break those conditions into nested `if` statement is provided.

Actually `1 != 2` is the `Left` of a `BinaryExpressionSyntax` and `2 !=3` is the `Right`, and `3 != 4` and `4 != 5` are the `Right`s of higher level of outer `BinaryExpressionSyntax`es which encompass one by one. After the refactoring, those three `BinaryExpressionSyntax`es are broken and then regrouped.

![image](https://user-images.githubusercontent.com/12182730/201555740-e8eae06a-ef12-4767-a3b9-c1780c81b8c1.png)

If `ExpressionSyntax`es can be broken and regrouped to another set of `ExpressionSyntax`es, why not `StatementSyntax`es?
