### ISSUE TITLE
Feature Request: Arm64 Visual Studio 2022 Extension

### ISSUE THREAD

**Issue by snickler** [JosefPihrt/Roslynator#989]
With the release of Visual Studio 2022 17.4, Arm64 support for extensions have arrived. 

Extensions targeting `ProductArchitecture` of `amd64` are incompatible with the fully Arm64-native version of Visual Studio, and won't install, nor appear in the Extension Manager within VS. Updating the extension to support Arm64 means enabling more access to developers using Windows on Arm.

**Comment by JosefPihrt** [comment]
Hi,

Roslynator 2022 extension already supports Arm64, please see https://github.com/JosefPihrt/Roslynator/blob/main/src/VisualStudio/source.extension.vsixmanifest#L15-L23.

**Comment by snickler** [comment]
> Hi,
> 
> Roslynator 2022 extension already supports Arm64, please see https://github.com/JosefPihrt/Roslynator/blob/main/src/VisualStudio/source.extension.vsixmanifest#L15-L23.

That's for amd64 (x64), not arm64 :).

**Comment by JosefPihrt** [comment]
Ok, I understand now 👍
