### ISSUE TITLE
DefaultCodeRefactoringProvider encountered an error and has been disabled

### ISSUE THREAD

**Issue by StephanBis** [JosefPihrt/Roslynator#99]
Seems like a new Visual Studio update has caused some issues with Roslynator.

**Stack trace:**
> System.IO.FileNotFoundException : Could not load file or assembly 'Roslynator.Common, Version=1.4.1.0, Culture=neutral, PublicKeyToken=ba9e36134d755ccb' or one of its dependencies. The system cannot find the file specified.
>    at async Roslynator.CSharp.Refactorings.MethodDeclarationRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
>    at Roslynator.CSharp.Refactorings.MethodDeclarationRefactoring.ComputeRefactoringsAsync(RefactoringContext context,MethodDeclarationSyntax methodDeclaration)
>    at async Roslynator.CSharp.Refactorings.MemberDeclarationRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
>    at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsForNodeAsync(<Unknown Parameters>)
>    at async Roslynator.CSharp.Refactorings.RefactoringContext.ComputeRefactoringsAsync(<Unknown Parameters>)
>    at async Roslynator.CSharp.Refactorings.DefaultCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
>    at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

**Versions:**
Visual Studio 2017 15.2 (26430.12)
Roslynator 1.4.1

**Comment by JosefPihrt** [comment]
Please check if you have multiple installations of Roslynator in your extensions folder: 

**%LocalAppData%\Microsoft\VisualStudio\15.0_xxxxxxxx\Extensions**

If you find multiple installations, uninstall all versions and install newest version.

Let me know if it helps.

**Comment by StephanBis** [comment]
I only had one installation of Roslynator and tried a second reinstall. It's still giving me the same error.

**Comment by JosefPihrt** [comment]
Could you please check if the file "Roslynator.Common.dll" exists in the Roslynator extension folder and if so which version is it?

**Comment by StephanBis** [comment]
How weird.. it is actually missing, no wonder I get the FileNotFoundException. But that is kind of weird because I just did another reinstall and it doesn't show up.

**Comment by JosefPihrt** [comment]
Are you using **Roslynator 2017** or **Roslynator Refactorings 2017**?

**Comment by StephanBis** [comment]
Roslynator Refactorings 2017 (latest 1.4.1)

**Comment by JosefPihrt** [comment]
That dll has been really left out in the latest version of RR2017.

I will release update immediately.

**Comment by JosefPihrt** [comment]
Please install latest version 1.4.11.

**Comment by StephanBis** [comment]
Seems like it's fixed now, thank you.

**Comment by JosefPihrt** [comment]
I'm glad it helps.

Sorry for the inconvenience.
